(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (ontable block1) (on block2 block4) (clear block2) (on block3 block1) (on block4 block5) (ontable block5) (ontable block6) (clear block6) (on block7 block3) (clear block7) (ontable block8) (clear block8) (handempty))
	(:goal (and (ontable block1) (on block2 block7) (on block3 block2) (on block4 block5) (on block5 block1) (on block6 block3) (clear block6) (on block7 block4) (ontable block8) (clear block8))))