(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (on block1 block7) (clear block1) (on block2 block5) (ontable block3) (on block4 block3) (on block5 block4) (on block6 block2) (on block7 block8) (on block8 block6) (handempty))
	(:goal (and (on block1 block2) (clear block1) (ontable block2) (ontable block3) (on block4 block3) (on block5 block4) (on block6 block5) (ontable block7) (clear block7) (on block8 block6) (clear block8))))