(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite5 - satellite
	instrument20 - instrument
	spectrograph3 - mode
	image4 - mode
	image5 - mode
	image1 - mode
	infrared2 - mode
	image0 - mode
	GroundStation5 - direction
	Star3 - direction
	GroundStation2 - direction
	Star4 - direction
	Star0 - direction
	GroundStation1 - direction
	Planet6 - direction
	Star7 - direction
	Phenomenon8 - direction
	Star9 - direction
	Planet10 - direction
	Phenomenon11 - direction
)
(:init
	(supports instrument0 image0)
	(supports instrument0 infrared2)
	(supports instrument0 spectrograph3)
	(calibration_target instrument0 GroundStation1)
	(calibration_target instrument0 Star3)
	(supports instrument1 image0)
	(supports instrument1 spectrograph3)
	(calibration_target instrument1 Star4)
	(supports instrument2 image0)
	(supports instrument2 spectrograph3)
	(supports instrument2 image1)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation5)
	(supports instrument3 infrared2)
	(supports instrument3 image4)
	(calibration_target instrument3 Star4)
	(supports instrument4 spectrograph3)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation1)
	(supports instrument5 image1)
	(calibration_target instrument5 Star3)
	(supports instrument6 spectrograph3)
	(supports instrument6 image0)
	(supports instrument6 image5)
	(calibration_target instrument6 GroundStation5)
	(calibration_target instrument6 Star0)
	(supports instrument7 image4)
	(calibration_target instrument7 GroundStation1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument8 image0)
	(supports instrument8 infrared2)
	(supports instrument8 image5)
	(calibration_target instrument8 Star3)
	(calibration_target instrument8 GroundStation1)
	(supports instrument9 spectrograph3)
	(supports instrument9 image4)
	(supports instrument9 image1)
	(calibration_target instrument9 Star0)
	(supports instrument10 spectrograph3)
	(supports instrument10 infrared2)
	(supports instrument10 image4)
	(calibration_target instrument10 Star4)
	(calibration_target instrument10 GroundStation5)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon11)
	(supports instrument11 image0)
	(calibration_target instrument11 GroundStation2)
	(supports instrument12 image4)
	(supports instrument12 image1)
	(supports instrument12 image0)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 GroundStation1)
	(supports instrument13 image4)
	(calibration_target instrument13 Star4)
	(calibration_target instrument13 GroundStation5)
	(supports instrument14 infrared2)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 Star0)
	(supports instrument15 image4)
	(supports instrument15 image1)
	(supports instrument15 infrared2)
	(calibration_target instrument15 Star3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star4)
	(supports instrument16 image5)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 Star3)
	(supports instrument17 image0)
	(supports instrument17 image1)
	(supports instrument17 image5)
	(calibration_target instrument17 Star4)
	(calibration_target instrument17 GroundStation2)
	(supports instrument18 image4)
	(calibration_target instrument18 Star4)
	(calibration_target instrument18 Star0)
	(supports instrument19 image5)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 GroundStation1)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon11)
	(supports instrument20 image0)
	(supports instrument20 infrared2)
	(supports instrument20 image1)
	(calibration_target instrument20 GroundStation1)
	(on_board instrument20 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation1)
)
(:goal (and
	(pointing satellite0 Phenomenon11)
	(pointing satellite5 Star9)
	(have_image Star7 image1)
	(have_image Phenomenon8 spectrograph3)
	(have_image Phenomenon8 image4)
	(have_image Star9 image5)
	(have_image Star9 image4)
))

)
