(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite3 - satellite
	instrument14 - instrument
	satellite4 - satellite
	instrument15 - instrument
	satellite5 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	infrared1 - mode
	spectrograph4 - mode
	image3 - mode
	image2 - mode
	image0 - mode
	thermograph5 - mode
	Star4 - direction
	Star5 - direction
	GroundStation3 - direction
	Star2 - direction
	Star0 - direction
	GroundStation1 - direction
	Phenomenon6 - direction
	Star7 - direction
	Planet8 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Phenomenon11 - direction
)
(:init
	(supports instrument0 image3)
	(calibration_target instrument0 Star0)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 image3)
	(supports instrument1 thermograph5)
	(calibration_target instrument1 GroundStation3)
	(supports instrument2 image3)
	(supports instrument2 image2)
	(supports instrument2 spectrograph4)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star7)
	(supports instrument3 image3)
	(supports instrument3 spectrograph4)
	(supports instrument3 image2)
	(calibration_target instrument3 Star2)
	(calibration_target instrument3 Star5)
	(supports instrument4 infrared1)
	(supports instrument4 thermograph5)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation1)
	(supports instrument5 image0)
	(calibration_target instrument5 Star2)
	(supports instrument6 image2)
	(supports instrument6 spectrograph4)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star4)
	(supports instrument7 spectrograph4)
	(supports instrument7 infrared1)
	(supports instrument7 image2)
	(calibration_target instrument7 Star0)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon11)
	(supports instrument8 image2)
	(supports instrument8 thermograph5)
	(supports instrument8 infrared1)
	(calibration_target instrument8 Star5)
	(supports instrument9 thermograph5)
	(calibration_target instrument9 GroundStation3)
	(supports instrument10 image2)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 thermograph5)
	(supports instrument11 image0)
	(supports instrument11 image2)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 infrared1)
	(supports instrument12 image2)
	(calibration_target instrument12 Star0)
	(supports instrument13 spectrograph4)
	(supports instrument13 image0)
	(supports instrument13 image3)
	(calibration_target instrument13 GroundStation3)
	(calibration_target instrument13 Star5)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star2)
	(supports instrument14 thermograph5)
	(supports instrument14 image2)
	(supports instrument14 image0)
	(calibration_target instrument14 Star5)
	(on_board instrument14 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(supports instrument15 spectrograph4)
	(supports instrument15 image0)
	(supports instrument15 infrared1)
	(calibration_target instrument15 GroundStation1)
	(calibration_target instrument15 Star0)
	(on_board instrument15 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation1)
	(supports instrument16 image3)
	(calibration_target instrument16 Star4)
	(calibration_target instrument16 Star0)
	(supports instrument17 infrared1)
	(supports instrument17 thermograph5)
	(calibration_target instrument17 GroundStation3)
	(calibration_target instrument17 Star5)
	(supports instrument18 spectrograph4)
	(calibration_target instrument18 GroundStation1)
	(calibration_target instrument18 GroundStation3)
	(supports instrument19 image2)
	(supports instrument19 image0)
	(supports instrument19 image3)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 Star2)
	(supports instrument20 thermograph5)
	(supports instrument20 image0)
	(calibration_target instrument20 GroundStation1)
	(calibration_target instrument20 Star0)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star2)
)
(:goal (and
	(pointing satellite1 Star4)
	(pointing satellite2 Planet9)
	(pointing satellite5 Star7)
	(have_image Phenomenon6 thermograph5)
	(have_image Phenomenon6 infrared1)
	(have_image Star7 image3)
	(have_image Star7 infrared1)
	(have_image Planet8 image3)
	(have_image Planet8 thermograph5)
	(have_image Phenomenon10 image2)
	(have_image Phenomenon11 image3)
	(have_image Phenomenon11 thermograph5)
))

)
