(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite3 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite5 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	image4 - mode
	spectrograph3 - mode
	image2 - mode
	thermograph0 - mode
	image5 - mode
	spectrograph1 - mode
	Star3 - direction
	GroundStation2 - direction
	Star0 - direction
	GroundStation1 - direction
	Star4 - direction
	Star5 - direction
	Planet6 - direction
	Phenomenon7 - direction
	Phenomenon8 - direction
	Star9 - direction
	Star10 - direction
	Planet11 - direction
)
(:init
	(supports instrument0 image4)
	(supports instrument0 thermograph0)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 spectrograph1)
	(supports instrument1 thermograph0)
	(supports instrument1 spectrograph3)
	(calibration_target instrument1 Star5)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 GroundStation1)
	(supports instrument3 spectrograph3)
	(supports instrument3 image2)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 Star5)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star4)
	(supports instrument4 image2)
	(supports instrument4 image5)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 Star5)
	(supports instrument5 spectrograph3)
	(calibration_target instrument5 Star4)
	(supports instrument6 image2)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 Star3)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 Star4)
	(calibration_target instrument7 Star3)
	(supports instrument8 spectrograph3)
	(supports instrument8 image2)
	(supports instrument8 image5)
	(calibration_target instrument8 Star0)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation1)
	(supports instrument9 spectrograph1)
	(supports instrument9 thermograph0)
	(supports instrument9 spectrograph3)
	(calibration_target instrument9 Star0)
	(supports instrument10 spectrograph1)
	(supports instrument10 image5)
	(calibration_target instrument10 GroundStation1)
	(calibration_target instrument10 GroundStation2)
	(supports instrument11 spectrograph3)
	(supports instrument11 image4)
	(supports instrument11 thermograph0)
	(calibration_target instrument11 GroundStation2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon7)
	(supports instrument12 spectrograph1)
	(supports instrument12 thermograph0)
	(supports instrument12 image5)
	(calibration_target instrument12 Star4)
	(calibration_target instrument12 Star0)
	(supports instrument13 image5)
	(supports instrument13 thermograph0)
	(supports instrument13 spectrograph3)
	(calibration_target instrument13 Star0)
	(supports instrument14 spectrograph3)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 Star0)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 GroundStation1)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon8)
	(supports instrument16 image2)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 Star4)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 GroundStation1)
	(supports instrument18 image5)
	(supports instrument18 spectrograph3)
	(calibration_target instrument18 GroundStation2)
	(calibration_target instrument18 Star5)
	(supports instrument19 thermograph0)
	(supports instrument19 image5)
	(supports instrument19 spectrograph1)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 Star5)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation2)
	(supports instrument20 image2)
	(supports instrument20 image5)
	(supports instrument20 spectrograph3)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 Star4)
	(supports instrument21 image2)
	(supports instrument21 spectrograph1)
	(supports instrument21 thermograph0)
	(calibration_target instrument21 Star4)
	(supports instrument22 thermograph0)
	(supports instrument22 spectrograph1)
	(supports instrument22 image2)
	(calibration_target instrument22 GroundStation1)
	(calibration_target instrument22 Star0)
	(supports instrument23 image5)
	(supports instrument23 thermograph0)
	(supports instrument23 image2)
	(calibration_target instrument23 Star4)
	(supports instrument24 spectrograph1)
	(supports instrument24 image5)
	(calibration_target instrument24 Star5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star5)
)
(:goal (and
	(pointing satellite0 Planet11)
	(pointing satellite1 GroundStation2)
	(pointing satellite3 GroundStation2)
	(have_image Planet6 image4)
	(have_image Planet6 spectrograph3)
	(have_image Phenomenon7 thermograph0)
	(have_image Star9 image4)
	(have_image Star10 image5)
	(have_image Star10 image4)
	(have_image Planet11 thermograph0)
	(have_image Planet11 spectrograph1)
))

)
