(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	infrared2 - mode
	spectrograph5 - mode
	thermograph1 - mode
	image3 - mode
	thermograph4 - mode
	image0 - mode
	GroundStation0 - direction
	GroundStation2 - direction
	Star1 - direction
	Star5 - direction
	Star4 - direction
	Star3 - direction
	Phenomenon6 - direction
	Planet7 - direction
	Phenomenon8 - direction
	Phenomenon9 - direction
	Phenomenon10 - direction
	Phenomenon11 - direction
)
(:init
	(supports instrument0 spectrograph5)
	(supports instrument0 image3)
	(supports instrument0 thermograph1)
	(calibration_target instrument0 Star1)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 Star1)
	(supports instrument2 image3)
	(supports instrument2 image0)
	(calibration_target instrument2 Star5)
	(supports instrument3 thermograph4)
	(supports instrument3 image3)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 Star4)
	(calibration_target instrument3 GroundStation0)
	(supports instrument4 thermograph4)
	(supports instrument4 image0)
	(supports instrument4 thermograph1)
	(calibration_target instrument4 GroundStation2)
	(calibration_target instrument4 Star4)
	(supports instrument5 spectrograph5)
	(calibration_target instrument5 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star4)
	(supports instrument6 thermograph1)
	(calibration_target instrument6 Star1)
	(supports instrument7 thermograph1)
	(supports instrument7 thermograph4)
	(supports instrument7 spectrograph5)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 Star1)
	(supports instrument8 image3)
	(supports instrument8 infrared2)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 Star3)
	(calibration_target instrument8 GroundStation2)
	(supports instrument9 infrared2)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 Star4)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star4)
	(supports instrument10 image0)
	(calibration_target instrument10 Star3)
	(supports instrument11 image3)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 Star3)
	(supports instrument12 thermograph1)
	(supports instrument12 image0)
	(calibration_target instrument12 GroundStation2)
	(calibration_target instrument12 Star3)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star1)
	(supports instrument13 image0)
	(supports instrument13 image3)
	(supports instrument13 spectrograph5)
	(calibration_target instrument13 GroundStation2)
	(calibration_target instrument13 Star1)
	(supports instrument14 image0)
	(supports instrument14 spectrograph5)
	(supports instrument14 image3)
	(calibration_target instrument14 Star1)
	(calibration_target instrument14 Star5)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 Star1)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star1)
	(supports instrument16 spectrograph5)
	(supports instrument16 image0)
	(calibration_target instrument16 Star5)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star3)
	(supports instrument17 image3)
	(supports instrument17 thermograph1)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 Star4)
	(supports instrument18 image0)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 Star3)
	(supports instrument19 image0)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 Star3)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star4)
)
(:goal (and
	(pointing satellite0 Planet7)
	(pointing satellite1 Phenomenon10)
	(pointing satellite2 Phenomenon8)
	(pointing satellite4 GroundStation2)
	(have_image Phenomenon6 image3)
	(have_image Planet7 thermograph1)
	(have_image Planet7 spectrograph5)
	(have_image Phenomenon8 thermograph1)
	(have_image Phenomenon10 image3)
	(have_image Phenomenon11 image0)
))

)
