(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite5 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	spectrograph3 - mode
	spectrograph2 - mode
	infrared5 - mode
	image1 - mode
	thermograph0 - mode
	image4 - mode
	GroundStation0 - direction
	GroundStation2 - direction
	Star1 - direction
	GroundStation5 - direction
	GroundStation3 - direction
	GroundStation4 - direction
	Star6 - direction
	Phenomenon7 - direction
	Phenomenon8 - direction
	Planet9 - direction
	Star10 - direction
	Star11 - direction
)
(:init
	(supports instrument0 infrared5)
	(calibration_target instrument0 GroundStation4)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon8)
	(supports instrument1 thermograph0)
	(supports instrument1 image4)
	(supports instrument1 infrared5)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 GroundStation0)
	(supports instrument2 spectrograph2)
	(supports instrument2 infrared5)
	(supports instrument2 image4)
	(calibration_target instrument2 GroundStation3)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star6)
	(supports instrument3 image1)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 GroundStation4)
	(supports instrument4 spectrograph3)
	(supports instrument4 infrared5)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 GroundStation0)
	(calibration_target instrument4 GroundStation5)
	(supports instrument5 spectrograph3)
	(supports instrument5 image1)
	(supports instrument5 image4)
	(calibration_target instrument5 GroundStation0)
	(calibration_target instrument5 GroundStation3)
	(supports instrument6 spectrograph2)
	(supports instrument6 image1)
	(calibration_target instrument6 Star1)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star6)
	(supports instrument7 infrared5)
	(supports instrument7 image4)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 GroundStation0)
	(supports instrument8 spectrograph3)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 GroundStation3)
	(supports instrument9 thermograph0)
	(supports instrument9 image4)
	(calibration_target instrument9 GroundStation3)
	(supports instrument10 spectrograph2)
	(supports instrument10 thermograph0)
	(supports instrument10 infrared5)
	(calibration_target instrument10 Star1)
	(calibration_target instrument10 GroundStation5)
	(supports instrument11 spectrograph2)
	(supports instrument11 image4)
	(calibration_target instrument11 GroundStation0)
	(calibration_target instrument11 GroundStation3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet9)
	(supports instrument12 image1)
	(calibration_target instrument12 GroundStation5)
	(supports instrument13 image1)
	(calibration_target instrument13 Star1)
	(supports instrument14 spectrograph3)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 Star1)
	(supports instrument15 spectrograph3)
	(supports instrument15 image4)
	(calibration_target instrument15 Star1)
	(calibration_target instrument15 GroundStation2)
	(supports instrument16 thermograph0)
	(calibration_target instrument16 GroundStation2)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 GroundStation3)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star6)
	(supports instrument18 spectrograph3)
	(supports instrument18 infrared5)
	(calibration_target instrument18 GroundStation5)
	(calibration_target instrument18 GroundStation4)
	(supports instrument19 spectrograph2)
	(supports instrument19 image1)
	(calibration_target instrument19 Star1)
	(supports instrument20 spectrograph2)
	(supports instrument20 image4)
	(calibration_target instrument20 GroundStation5)
	(calibration_target instrument20 Star1)
	(supports instrument21 thermograph0)
	(supports instrument21 image1)
	(supports instrument21 infrared5)
	(calibration_target instrument21 GroundStation3)
	(calibration_target instrument21 GroundStation4)
	(supports instrument22 image4)
	(calibration_target instrument22 GroundStation4)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation5)
)
(:goal (and
	(pointing satellite0 Planet9)
	(pointing satellite2 GroundStation3)
	(pointing satellite3 GroundStation4)
	(pointing satellite4 GroundStation3)
	(have_image Star6 infrared5)
	(have_image Phenomenon7 image4)
	(have_image Phenomenon7 infrared5)
	(have_image Phenomenon8 image1)
	(have_image Planet9 infrared5)
	(have_image Star11 infrared5)
	(have_image Star11 spectrograph3)
))

)
