(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	thermograph0 - mode
	image5 - mode
	thermograph4 - mode
	thermograph2 - mode
	thermograph1 - mode
	image3 - mode
	Star3 - direction
	GroundStation4 - direction
	GroundStation1 - direction
	Star0 - direction
	GroundStation5 - direction
	Star2 - direction
	Phenomenon6 - direction
	Star7 - direction
	Phenomenon8 - direction
	Planet9 - direction
	Planet10 - direction
	Planet11 - direction
)
(:init
	(supports instrument0 image3)
	(supports instrument0 thermograph4)
	(supports instrument0 thermograph0)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 thermograph1)
	(supports instrument1 image5)
	(calibration_target instrument1 Star2)
	(supports instrument2 image3)
	(calibration_target instrument2 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon8)
	(supports instrument3 thermograph2)
	(supports instrument3 thermograph0)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 Star2)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation5)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 Star3)
	(supports instrument5 image5)
	(supports instrument5 thermograph0)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 Star2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon8)
	(supports instrument6 thermograph0)
	(supports instrument6 image3)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 GroundStation5)
	(supports instrument8 thermograph4)
	(supports instrument8 thermograph1)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 GroundStation4)
	(supports instrument9 image5)
	(supports instrument9 thermograph2)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 GroundStation5)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation1)
	(supports instrument10 thermograph0)
	(supports instrument10 image5)
	(supports instrument10 thermograph2)
	(calibration_target instrument10 GroundStation5)
	(supports instrument11 thermograph2)
	(supports instrument11 thermograph4)
	(supports instrument11 image5)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 GroundStation4)
	(supports instrument12 image5)
	(supports instrument12 thermograph1)
	(supports instrument12 image3)
	(calibration_target instrument12 GroundStation1)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star3)
	(supports instrument13 thermograph2)
	(calibration_target instrument13 Star2)
	(calibration_target instrument13 GroundStation5)
	(supports instrument14 thermograph0)
	(supports instrument14 image5)
	(calibration_target instrument14 GroundStation1)
	(calibration_target instrument14 GroundStation4)
	(supports instrument15 thermograph4)
	(supports instrument15 thermograph0)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 Star0)
	(supports instrument16 thermograph4)
	(supports instrument16 image5)
	(supports instrument16 thermograph0)
	(calibration_target instrument16 GroundStation5)
	(supports instrument17 image3)
	(supports instrument17 thermograph1)
	(supports instrument17 thermograph2)
	(calibration_target instrument17 Star2)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet11)
)
(:goal (and
	(pointing satellite0 GroundStation5)
	(have_image Phenomenon6 image5)
	(have_image Star7 thermograph1)
	(have_image Phenomenon8 image3)
	(have_image Phenomenon8 image5)
	(have_image Planet9 thermograph4)
	(have_image Planet9 thermograph0)
	(have_image Planet10 image5)
	(have_image Planet10 thermograph0)
	(have_image Planet11 thermograph0)
	(have_image Planet11 image5)
))

)
