(define (problem pb2)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (on block1 block7) (clear block1) (ontable block2) (ontable block3) (on block4 block6) (clear block4) (on block5 block11) (ontable block6) (on block7 block3) (on block8 block2) (on block9 block5) (on block10 block9) (clear block10) (on block11 block8) (handempty))
	(:goal (and (ontable block1) (clear block1) (ontable block2) (on block3 block8) (on block4 block9) (on block5 block2) (on block6 block5) (on block7 block3) (on block8 block4) (ontable block9) (on block10 block7) (clear block10) (on block11 block6) (clear block11))))