(define (problem pb9)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (ontable block1) (clear block1) (ontable block2) (on block3 block4) (on block4 block6) (on block5 block3) (clear block5) (ontable block6) (on block7 block9) (clear block7) (on block8 block11) (clear block8) (ontable block9) (on block10 block2) (on block11 block10) (handempty))
	(:goal (and (on block1 block5) (on block2 block6) (clear block2) (on block3 block11) (on block4 block1) (on block5 block10) (on block6 block9) (ontable block7) (on block8 block4) (clear block8) (on block9 block3) (ontable block10) (on block11 block7))))