(define (problem pb5)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (on block1 block5) (on block2 block1) (clear block2) (on block3 block4) (on block4 block6) (ontable block5) (on block6 block11) (on block7 block3) (on block8 block7) (clear block8) (on block9 block10) (clear block9) (ontable block10) (ontable block11) (handempty))
	(:goal (and (ontable block1) (on block2 block4) (ontable block3) (clear block3) (on block4 block1) (on block5 block10) (clear block5) (ontable block6) (on block7 block6) (clear block7) (on block8 block11) (on block9 block8) (clear block9) (ontable block10) (on block11 block2))))