(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite5 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite6 - satellite
	instrument31 - instrument
	satellite7 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite8 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	satellite9 - satellite
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	infrared3 - mode
	image6 - mode
	spectrograph1 - mode
	infrared2 - mode
	thermograph4 - mode
	image8 - mode
	image5 - mode
	image7 - mode
	thermograph9 - mode
	infrared0 - mode
	Star7 - direction
	Star6 - direction
	Star2 - direction
	GroundStation3 - direction
	Star1 - direction
	Star5 - direction
	Star9 - direction
	GroundStation0 - direction
	Star4 - direction
	GroundStation8 - direction
	Phenomenon10 - direction
	Star11 - direction
	Star12 - direction
	Planet13 - direction
	Star14 - direction
	Phenomenon15 - direction
	Planet16 - direction
	Phenomenon17 - direction
	Phenomenon18 - direction
	Planet19 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(supports instrument0 image7)
	(supports instrument0 image8)
	(calibration_target instrument0 Star5)
	(supports instrument1 infrared0)
	(supports instrument1 thermograph4)
	(supports instrument1 image6)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 GroundStation3)
	(supports instrument2 image6)
	(supports instrument2 infrared0)
	(supports instrument2 image5)
	(calibration_target instrument2 Star7)
	(calibration_target instrument2 Star2)
	(supports instrument3 image8)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star7)
	(supports instrument4 infrared0)
	(calibration_target instrument4 GroundStation0)
	(calibration_target instrument4 GroundStation8)
	(supports instrument5 image8)
	(supports instrument5 thermograph9)
	(calibration_target instrument5 Star1)
	(calibration_target instrument5 Star2)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star6)
	(supports instrument6 infrared0)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 GroundStation3)
	(calibration_target instrument6 Star1)
	(calibration_target instrument6 GroundStation8)
	(supports instrument7 image6)
	(supports instrument7 thermograph4)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star6)
	(calibration_target instrument7 GroundStation0)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon15)
	(supports instrument8 image8)
	(calibration_target instrument8 Star9)
	(calibration_target instrument8 GroundStation3)
	(supports instrument9 image7)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 GroundStation3)
	(supports instrument10 spectrograph1)
	(supports instrument10 image6)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 Star4)
	(supports instrument11 infrared0)
	(supports instrument11 image5)
	(supports instrument11 image7)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 Star1)
	(supports instrument12 thermograph9)
	(supports instrument12 image7)
	(supports instrument12 spectrograph1)
	(calibration_target instrument12 Star4)
	(calibration_target instrument12 Star5)
	(supports instrument13 image5)
	(calibration_target instrument13 GroundStation8)
	(calibration_target instrument13 Star6)
	(supports instrument14 infrared2)
	(calibration_target instrument14 GroundStation8)
	(supports instrument15 infrared3)
	(supports instrument15 image6)
	(calibration_target instrument15 GroundStation8)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet13)
	(supports instrument16 infrared0)
	(calibration_target instrument16 GroundStation8)
	(supports instrument17 thermograph4)
	(supports instrument17 thermograph9)
	(calibration_target instrument17 Star9)
	(supports instrument18 image5)
	(supports instrument18 infrared0)
	(supports instrument18 thermograph9)
	(calibration_target instrument18 Star4)
	(calibration_target instrument18 Star5)
	(supports instrument19 image5)
	(supports instrument19 infrared3)
	(supports instrument19 infrared0)
	(calibration_target instrument19 Star4)
	(calibration_target instrument19 Star6)
	(supports instrument20 image7)
	(supports instrument20 infrared2)
	(calibration_target instrument20 GroundStation8)
	(calibration_target instrument20 Star2)
	(supports instrument21 image5)
	(calibration_target instrument21 Star4)
	(supports instrument22 image8)
	(supports instrument22 image6)
	(supports instrument22 image7)
	(calibration_target instrument22 GroundStation8)
	(calibration_target instrument22 Star1)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet13)
	(supports instrument23 thermograph9)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 Star5)
	(calibration_target instrument23 Star4)
	(calibration_target instrument23 GroundStation0)
	(supports instrument24 thermograph4)
	(supports instrument24 infrared2)
	(supports instrument24 image6)
	(calibration_target instrument24 Star9)
	(supports instrument25 spectrograph1)
	(supports instrument25 image5)
	(calibration_target instrument25 Star2)
	(supports instrument26 image6)
	(supports instrument26 image5)
	(supports instrument26 spectrograph1)
	(calibration_target instrument26 Star5)
	(calibration_target instrument26 Star2)
	(calibration_target instrument26 GroundStation8)
	(supports instrument27 thermograph4)
	(supports instrument27 image8)
	(supports instrument27 infrared0)
	(calibration_target instrument27 GroundStation0)
	(calibration_target instrument27 Star1)
	(supports instrument28 infrared3)
	(supports instrument28 image5)
	(supports instrument28 image7)
	(calibration_target instrument28 GroundStation0)
	(calibration_target instrument28 Star7)
	(calibration_target instrument28 GroundStation3)
	(supports instrument29 thermograph9)
	(calibration_target instrument29 GroundStation0)
	(calibration_target instrument29 GroundStation3)
	(supports instrument30 infrared0)
	(supports instrument30 infrared2)
	(calibration_target instrument30 Star4)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star9)
	(supports instrument31 image7)
	(calibration_target instrument31 Star2)
	(calibration_target instrument31 GroundStation8)
	(on_board instrument31 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation8)
	(supports instrument32 thermograph9)
	(supports instrument32 infrared3)
	(calibration_target instrument32 Star6)
	(calibration_target instrument32 Star2)
	(supports instrument33 thermograph4)
	(calibration_target instrument33 GroundStation3)
	(calibration_target instrument33 GroundStation0)
	(supports instrument34 image5)
	(supports instrument34 infrared2)
	(supports instrument34 image8)
	(calibration_target instrument34 Star6)
	(calibration_target instrument34 GroundStation8)
	(calibration_target instrument34 Star1)
	(supports instrument35 infrared2)
	(supports instrument35 thermograph9)
	(supports instrument35 image8)
	(calibration_target instrument35 Star7)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation0)
	(supports instrument36 infrared2)
	(supports instrument36 image7)
	(supports instrument36 image6)
	(calibration_target instrument36 GroundStation0)
	(supports instrument37 image6)
	(supports instrument37 thermograph4)
	(calibration_target instrument37 GroundStation3)
	(calibration_target instrument37 Star9)
	(supports instrument38 infrared2)
	(supports instrument38 thermograph9)
	(supports instrument38 image7)
	(calibration_target instrument38 GroundStation8)
	(calibration_target instrument38 GroundStation3)
	(supports instrument39 image8)
	(supports instrument39 thermograph4)
	(supports instrument39 image6)
	(calibration_target instrument39 Star5)
	(calibration_target instrument39 Star7)
	(calibration_target instrument39 GroundStation0)
	(supports instrument40 infrared3)
	(calibration_target instrument40 GroundStation0)
	(calibration_target instrument40 Star4)
	(calibration_target instrument40 Star1)
	(supports instrument41 infrared0)
	(supports instrument41 spectrograph1)
	(supports instrument41 image6)
	(calibration_target instrument41 Star4)
	(calibration_target instrument41 Star2)
	(calibration_target instrument41 Star6)
	(supports instrument42 image5)
	(supports instrument42 image8)
	(calibration_target instrument42 Star2)
	(supports instrument43 thermograph4)
	(supports instrument43 spectrograph1)
	(calibration_target instrument43 Star9)
	(calibration_target instrument43 Star4)
	(supports instrument44 thermograph4)
	(supports instrument44 spectrograph1)
	(calibration_target instrument44 Star1)
	(calibration_target instrument44 GroundStation3)
	(calibration_target instrument44 Star2)
	(supports instrument45 thermograph4)
	(supports instrument45 infrared2)
	(calibration_target instrument45 Star9)
	(calibration_target instrument45 Star1)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(on_board instrument38 satellite8)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon17)
	(supports instrument46 image8)
	(calibration_target instrument46 Star9)
	(supports instrument47 image5)
	(calibration_target instrument47 Star9)
	(calibration_target instrument47 Star5)
	(supports instrument48 infrared0)
	(supports instrument48 thermograph9)
	(supports instrument48 image7)
	(calibration_target instrument48 GroundStation8)
	(calibration_target instrument48 Star4)
	(calibration_target instrument48 GroundStation0)
	(on_board instrument46 satellite9)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation8)
)
(:goal (and
	(pointing satellite4 Phenomenon10)
	(pointing satellite8 Phenomenon17)
	(have_image Phenomenon10 infrared0)
	(have_image Star11 thermograph4)
	(have_image Planet13 thermograph4)
	(have_image Star14 infrared2)
	(have_image Star14 image5)
	(have_image Star14 infrared3)
	(have_image Planet16 image7)
	(have_image Planet16 thermograph4)
	(have_image Phenomenon17 image6)
	(have_image Phenomenon17 infrared0)
	(have_image Phenomenon17 thermograph4)
	(have_image Phenomenon18 infrared2)
	(have_image Planet19 infrared2)
))

)
