(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite3 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite4 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite5 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite6 - satellite
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	satellite7 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	satellite8 - satellite
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	satellite9 - satellite
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	spectrograph4 - mode
	infrared3 - mode
	infrared2 - mode
	infrared5 - mode
	image1 - mode
	thermograph8 - mode
	image9 - mode
	spectrograph7 - mode
	infrared0 - mode
	thermograph6 - mode
	GroundStation0 - direction
	GroundStation4 - direction
	Star2 - direction
	Star8 - direction
	Star1 - direction
	GroundStation5 - direction
	Star3 - direction
	GroundStation6 - direction
	Star9 - direction
	Star7 - direction
	Planet10 - direction
	Phenomenon11 - direction
	Phenomenon12 - direction
	Star13 - direction
	Phenomenon14 - direction
	Phenomenon15 - direction
	Planet16 - direction
	Phenomenon17 - direction
	Star18 - direction
	Star19 - direction
)
(:init
	(supports instrument0 image1)
	(supports instrument0 image9)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 Star9)
	(supports instrument1 thermograph6)
	(supports instrument1 image1)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation4)
	(supports instrument2 infrared5)
	(calibration_target instrument2 Star8)
	(supports instrument3 infrared5)
	(supports instrument3 spectrograph4)
	(calibration_target instrument3 GroundStation4)
	(supports instrument4 infrared3)
	(supports instrument4 image1)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 Star8)
	(supports instrument5 infrared2)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 Star2)
	(supports instrument6 thermograph8)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 GroundStation4)
	(supports instrument7 infrared3)
	(supports instrument7 thermograph8)
	(calibration_target instrument7 GroundStation0)
	(calibration_target instrument7 GroundStation5)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation6)
	(supports instrument8 image9)
	(supports instrument8 infrared0)
	(supports instrument8 thermograph6)
	(calibration_target instrument8 GroundStation6)
	(calibration_target instrument8 Star9)
	(calibration_target instrument8 Star7)
	(supports instrument9 infrared0)
	(supports instrument9 image9)
	(calibration_target instrument9 Star8)
	(calibration_target instrument9 GroundStation5)
	(supports instrument10 thermograph6)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 Star1)
	(supports instrument11 image1)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 GroundStation5)
	(calibration_target instrument11 Star3)
	(supports instrument12 image9)
	(supports instrument12 infrared5)
	(calibration_target instrument12 Star1)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 Star3)
	(supports instrument13 image1)
	(calibration_target instrument13 Star7)
	(supports instrument14 infrared3)
	(supports instrument14 infrared5)
	(supports instrument14 spectrograph7)
	(calibration_target instrument14 GroundStation0)
	(calibration_target instrument14 Star7)
	(calibration_target instrument14 Star1)
	(supports instrument15 image9)
	(calibration_target instrument15 Star3)
	(supports instrument16 infrared2)
	(supports instrument16 infrared0)
	(calibration_target instrument16 GroundStation0)
	(calibration_target instrument16 Star9)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star1)
	(supports instrument17 thermograph6)
	(supports instrument17 spectrograph7)
	(supports instrument17 image9)
	(calibration_target instrument17 Star1)
	(calibration_target instrument17 Star7)
	(calibration_target instrument17 Star9)
	(supports instrument18 spectrograph7)
	(calibration_target instrument18 Star9)
	(calibration_target instrument18 Star7)
	(calibration_target instrument18 Star8)
	(supports instrument19 image1)
	(supports instrument19 infrared3)
	(supports instrument19 infrared5)
	(calibration_target instrument19 Star7)
	(calibration_target instrument19 Star8)
	(calibration_target instrument19 Star2)
	(supports instrument20 image1)
	(calibration_target instrument20 Star7)
	(supports instrument21 thermograph6)
	(supports instrument21 spectrograph7)
	(supports instrument21 infrared3)
	(calibration_target instrument21 GroundStation5)
	(calibration_target instrument21 GroundStation6)
	(calibration_target instrument21 Star2)
	(supports instrument22 image1)
	(supports instrument22 infrared3)
	(calibration_target instrument22 Star9)
	(supports instrument23 thermograph6)
	(supports instrument23 spectrograph7)
	(calibration_target instrument23 Star2)
	(calibration_target instrument23 GroundStation5)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon14)
	(supports instrument24 infrared5)
	(supports instrument24 spectrograph4)
	(supports instrument24 infrared3)
	(calibration_target instrument24 Star3)
	(calibration_target instrument24 Star1)
	(calibration_target instrument24 GroundStation5)
	(supports instrument25 image1)
	(supports instrument25 spectrograph7)
	(calibration_target instrument25 GroundStation6)
	(calibration_target instrument25 GroundStation0)
	(calibration_target instrument25 GroundStation5)
	(supports instrument26 spectrograph4)
	(calibration_target instrument26 Star2)
	(calibration_target instrument26 GroundStation6)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation0)
	(supports instrument27 infrared3)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 Star1)
	(supports instrument28 spectrograph4)
	(supports instrument28 spectrograph7)
	(supports instrument28 infrared3)
	(calibration_target instrument28 Star1)
	(supports instrument29 thermograph6)
	(supports instrument29 spectrograph4)
	(calibration_target instrument29 Star7)
	(calibration_target instrument29 GroundStation6)
	(supports instrument30 thermograph8)
	(supports instrument30 infrared2)
	(calibration_target instrument30 GroundStation0)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation0)
	(supports instrument31 image1)
	(supports instrument31 thermograph8)
	(supports instrument31 infrared2)
	(calibration_target instrument31 GroundStation6)
	(supports instrument32 spectrograph4)
	(supports instrument32 spectrograph7)
	(calibration_target instrument32 Star8)
	(supports instrument33 infrared5)
	(supports instrument33 infrared0)
	(calibration_target instrument33 Star2)
	(calibration_target instrument33 GroundStation4)
	(supports instrument34 infrared3)
	(supports instrument34 spectrograph7)
	(calibration_target instrument34 Star3)
	(supports instrument35 infrared0)
	(supports instrument35 infrared3)
	(supports instrument35 thermograph8)
	(calibration_target instrument35 Star7)
	(calibration_target instrument35 GroundStation6)
	(supports instrument36 image1)
	(calibration_target instrument36 Star3)
	(supports instrument37 infrared3)
	(calibration_target instrument37 GroundStation6)
	(calibration_target instrument37 Star9)
	(supports instrument38 image1)
	(supports instrument38 image9)
	(calibration_target instrument38 Star8)
	(calibration_target instrument38 GroundStation0)
	(calibration_target instrument38 Star7)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation0)
	(supports instrument39 infrared5)
	(supports instrument39 infrared2)
	(supports instrument39 spectrograph7)
	(calibration_target instrument39 GroundStation0)
	(calibration_target instrument39 Star1)
	(supports instrument40 thermograph8)
	(supports instrument40 image1)
	(calibration_target instrument40 GroundStation6)
	(calibration_target instrument40 GroundStation5)
	(calibration_target instrument40 Star8)
	(supports instrument41 image9)
	(supports instrument41 infrared3)
	(supports instrument41 spectrograph4)
	(calibration_target instrument41 Star7)
	(supports instrument42 thermograph6)
	(supports instrument42 thermograph8)
	(calibration_target instrument42 GroundStation4)
	(calibration_target instrument42 Star8)
	(supports instrument43 infrared0)
	(supports instrument43 spectrograph7)
	(supports instrument43 infrared2)
	(calibration_target instrument43 GroundStation6)
	(calibration_target instrument43 GroundStation0)
	(supports instrument44 infrared3)
	(supports instrument44 spectrograph4)
	(calibration_target instrument44 GroundStation6)
	(supports instrument45 infrared0)
	(calibration_target instrument45 GroundStation5)
	(calibration_target instrument45 GroundStation6)
	(calibration_target instrument45 GroundStation4)
	(supports instrument46 spectrograph4)
	(supports instrument46 infrared2)
	(supports instrument46 infrared0)
	(calibration_target instrument46 Star1)
	(calibration_target instrument46 Star2)
	(supports instrument47 thermograph8)
	(calibration_target instrument47 GroundStation5)
	(calibration_target instrument47 Star2)
	(calibration_target instrument47 GroundStation4)
	(supports instrument48 image9)
	(supports instrument48 thermograph8)
	(calibration_target instrument48 Star7)
	(calibration_target instrument48 GroundStation4)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star8)
	(supports instrument49 infrared3)
	(calibration_target instrument49 GroundStation6)
	(supports instrument50 thermograph8)
	(supports instrument50 spectrograph4)
	(calibration_target instrument50 GroundStation4)
	(calibration_target instrument50 GroundStation0)
	(calibration_target instrument50 Star2)
	(supports instrument51 spectrograph4)
	(supports instrument51 thermograph8)
	(calibration_target instrument51 Star1)
	(calibration_target instrument51 Star8)
	(supports instrument52 infrared3)
	(supports instrument52 thermograph8)
	(supports instrument52 infrared0)
	(calibration_target instrument52 GroundStation5)
	(calibration_target instrument52 Star9)
	(supports instrument53 thermograph6)
	(supports instrument53 thermograph8)
	(calibration_target instrument53 Star8)
	(supports instrument54 infrared2)
	(supports instrument54 spectrograph7)
	(supports instrument54 image9)
	(calibration_target instrument54 Star9)
	(calibration_target instrument54 GroundStation5)
	(calibration_target instrument54 GroundStation4)
	(supports instrument55 infrared5)
	(supports instrument55 infrared2)
	(calibration_target instrument55 GroundStation4)
	(calibration_target instrument55 GroundStation5)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon11)
	(supports instrument56 image1)
	(supports instrument56 thermograph8)
	(calibration_target instrument56 Star8)
	(calibration_target instrument56 GroundStation6)
	(calibration_target instrument56 Star2)
	(supports instrument57 image9)
	(supports instrument57 thermograph8)
	(calibration_target instrument57 Star3)
	(calibration_target instrument57 GroundStation5)
	(calibration_target instrument57 Star1)
	(supports instrument58 thermograph6)
	(supports instrument58 infrared0)
	(supports instrument58 spectrograph7)
	(calibration_target instrument58 Star7)
	(calibration_target instrument58 Star9)
	(calibration_target instrument58 GroundStation6)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation4)
)
(:goal (and
	(pointing satellite0 Star18)
	(pointing satellite1 Planet16)
	(pointing satellite4 Star7)
	(pointing satellite5 GroundStation6)
	(pointing satellite9 Planet16)
	(have_image Planet10 thermograph6)
	(have_image Phenomenon11 infrared5)
	(have_image Phenomenon12 infrared3)
	(have_image Phenomenon12 thermograph8)
	(have_image Star13 infrared2)
	(have_image Star13 infrared0)
	(have_image Star13 thermograph8)
	(have_image Phenomenon14 infrared3)
	(have_image Phenomenon14 image1)
	(have_image Phenomenon14 image9)
	(have_image Phenomenon15 infrared5)
	(have_image Phenomenon15 image9)
	(have_image Planet16 image9)
	(have_image Planet16 infrared5)
	(have_image Planet16 image1)
	(have_image Phenomenon17 infrared0)
	(have_image Phenomenon17 spectrograph4)
	(have_image Star18 spectrograph4)
	(have_image Star18 infrared0)
	(have_image Star18 image9)
	(have_image Star19 spectrograph4)
	(have_image Star19 infrared2)
))

)
