(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	satellite4 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite5 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite6 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite7 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite8 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	satellite9 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	image2 - mode
	infrared1 - mode
	infrared7 - mode
	spectrograph9 - mode
	image3 - mode
	infrared6 - mode
	image8 - mode
	thermograph5 - mode
	image0 - mode
	spectrograph4 - mode
	Star0 - direction
	Star5 - direction
	Star8 - direction
	GroundStation3 - direction
	Star2 - direction
	Star6 - direction
	Star4 - direction
	GroundStation9 - direction
	GroundStation7 - direction
	Star1 - direction
	Star10 - direction
	Phenomenon11 - direction
	Planet12 - direction
	Planet13 - direction
	Star14 - direction
	Planet15 - direction
	Phenomenon16 - direction
	Phenomenon17 - direction
	Planet18 - direction
	Planet19 - direction
)
(:init
	(supports instrument0 image2)
	(supports instrument0 image0)
	(supports instrument0 infrared1)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 Star4)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star14)
	(supports instrument1 infrared6)
	(supports instrument1 infrared7)
	(supports instrument1 thermograph5)
	(calibration_target instrument1 Star0)
	(supports instrument2 image2)
	(supports instrument2 infrared6)
	(calibration_target instrument2 Star0)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation9)
	(supports instrument3 spectrograph9)
	(supports instrument3 image8)
	(calibration_target instrument3 GroundStation7)
	(supports instrument4 image0)
	(supports instrument4 image8)
	(calibration_target instrument4 Star6)
	(calibration_target instrument4 Star8)
	(supports instrument5 spectrograph9)
	(supports instrument5 image8)
	(supports instrument5 thermograph5)
	(calibration_target instrument5 Star4)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument6 image8)
	(calibration_target instrument6 Star8)
	(on_board instrument6 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation9)
	(supports instrument7 infrared7)
	(supports instrument7 image2)
	(supports instrument7 infrared6)
	(calibration_target instrument7 GroundStation9)
	(supports instrument8 infrared7)
	(calibration_target instrument8 Star6)
	(supports instrument9 image3)
	(supports instrument9 infrared7)
	(calibration_target instrument9 GroundStation7)
	(calibration_target instrument9 Star1)
	(supports instrument10 image3)
	(supports instrument10 thermograph5)
	(supports instrument10 image2)
	(calibration_target instrument10 Star5)
	(supports instrument11 image2)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 Star6)
	(supports instrument12 image2)
	(calibration_target instrument12 Star0)
	(supports instrument13 image8)
	(supports instrument13 thermograph5)
	(supports instrument13 spectrograph9)
	(calibration_target instrument13 Star5)
	(calibration_target instrument13 Star8)
	(calibration_target instrument13 Star1)
	(supports instrument14 infrared6)
	(calibration_target instrument14 Star6)
	(on_board instrument7 satellite4)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star4)
	(supports instrument15 spectrograph9)
	(calibration_target instrument15 GroundStation9)
	(supports instrument16 image2)
	(calibration_target instrument16 Star2)
	(calibration_target instrument16 GroundStation3)
	(calibration_target instrument16 Star1)
	(supports instrument17 image3)
	(supports instrument17 infrared6)
	(supports instrument17 infrared7)
	(calibration_target instrument17 GroundStation3)
	(calibration_target instrument17 GroundStation9)
	(calibration_target instrument17 Star2)
	(supports instrument18 spectrograph9)
	(calibration_target instrument18 GroundStation9)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 Star6)
	(supports instrument19 image3)
	(supports instrument19 infrared7)
	(calibration_target instrument19 Star2)
	(supports instrument20 spectrograph4)
	(calibration_target instrument20 Star2)
	(calibration_target instrument20 Star8)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star5)
	(supports instrument21 image8)
	(supports instrument21 infrared7)
	(calibration_target instrument21 Star1)
	(supports instrument22 infrared7)
	(supports instrument22 image3)
	(calibration_target instrument22 Star6)
	(calibration_target instrument22 GroundStation7)
	(calibration_target instrument22 Star8)
	(supports instrument23 image2)
	(supports instrument23 thermograph5)
	(supports instrument23 infrared6)
	(calibration_target instrument23 Star8)
	(supports instrument24 thermograph5)
	(supports instrument24 spectrograph4)
	(supports instrument24 image2)
	(calibration_target instrument24 Star8)
	(calibration_target instrument24 Star6)
	(calibration_target instrument24 GroundStation3)
	(supports instrument25 infrared6)
	(supports instrument25 image3)
	(calibration_target instrument25 Star2)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation9)
	(supports instrument26 infrared6)
	(calibration_target instrument26 GroundStation9)
	(supports instrument27 infrared6)
	(supports instrument27 infrared1)
	(supports instrument27 thermograph5)
	(calibration_target instrument27 GroundStation9)
	(calibration_target instrument27 Star6)
	(supports instrument28 infrared1)
	(supports instrument28 image8)
	(supports instrument28 infrared6)
	(calibration_target instrument28 GroundStation9)
	(calibration_target instrument28 GroundStation7)
	(supports instrument29 thermograph5)
	(supports instrument29 infrared7)
	(calibration_target instrument29 Star5)
	(supports instrument30 spectrograph9)
	(supports instrument30 image3)
	(calibration_target instrument30 GroundStation3)
	(calibration_target instrument30 GroundStation7)
	(supports instrument31 spectrograph9)
	(supports instrument31 image0)
	(supports instrument31 spectrograph4)
	(calibration_target instrument31 Star5)
	(calibration_target instrument31 Star6)
	(calibration_target instrument31 GroundStation7)
	(supports instrument32 image0)
	(supports instrument32 image2)
	(supports instrument32 image8)
	(calibration_target instrument32 Star2)
	(calibration_target instrument32 Star6)
	(supports instrument33 thermograph5)
	(supports instrument33 infrared1)
	(supports instrument33 spectrograph4)
	(calibration_target instrument33 GroundStation3)
	(calibration_target instrument33 Star4)
	(supports instrument34 infrared6)
	(supports instrument34 infrared7)
	(supports instrument34 infrared1)
	(calibration_target instrument34 Star8)
	(on_board instrument26 satellite7)
	(on_board instrument27 satellite7)
	(on_board instrument28 satellite7)
	(on_board instrument29 satellite7)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet19)
	(supports instrument35 thermograph5)
	(calibration_target instrument35 Star6)
	(calibration_target instrument35 Star0)
	(supports instrument36 spectrograph9)
	(supports instrument36 thermograph5)
	(supports instrument36 image3)
	(calibration_target instrument36 Star5)
	(calibration_target instrument36 GroundStation3)
	(supports instrument37 infrared6)
	(supports instrument37 image0)
	(supports instrument37 image8)
	(calibration_target instrument37 Star4)
	(calibration_target instrument37 GroundStation7)
	(supports instrument38 spectrograph9)
	(calibration_target instrument38 Star8)
	(on_board instrument35 satellite8)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(on_board instrument38 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet18)
	(supports instrument39 infrared6)
	(supports instrument39 image3)
	(calibration_target instrument39 Star4)
	(calibration_target instrument39 GroundStation9)
	(supports instrument40 spectrograph4)
	(supports instrument40 thermograph5)
	(supports instrument40 image8)
	(calibration_target instrument40 GroundStation3)
	(calibration_target instrument40 GroundStation9)
	(supports instrument41 image0)
	(calibration_target instrument41 Star4)
	(calibration_target instrument41 Star6)
	(calibration_target instrument41 Star2)
	(supports instrument42 spectrograph4)
	(calibration_target instrument42 Star1)
	(calibration_target instrument42 GroundStation7)
	(calibration_target instrument42 GroundStation9)
	(on_board instrument39 satellite9)
	(on_board instrument40 satellite9)
	(on_board instrument41 satellite9)
	(on_board instrument42 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star6)
)
(:goal (and
	(pointing satellite0 Planet13)
	(pointing satellite1 GroundStation9)
	(pointing satellite7 GroundStation3)
	(pointing satellite8 Phenomenon16)
	(pointing satellite9 Star10)
	(have_image Star10 image3)
	(have_image Phenomenon11 spectrograph9)
	(have_image Phenomenon11 spectrograph4)
	(have_image Planet12 thermograph5)
	(have_image Planet12 spectrograph4)
	(have_image Planet13 thermograph5)
	(have_image Planet13 image3)
	(have_image Planet13 spectrograph4)
	(have_image Star14 image2)
	(have_image Planet15 spectrograph9)
	(have_image Phenomenon16 spectrograph9)
	(have_image Phenomenon17 infrared7)
	(have_image Planet18 spectrograph4)
	(have_image Planet18 image2)
	(have_image Planet18 image0)
	(have_image Planet19 image3)
))

)
