(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite1 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite2 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite4 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite5 - satellite
	instrument35 - instrument
	instrument36 - instrument
	satellite6 - satellite
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite7 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite8 - satellite
	instrument48 - instrument
	satellite9 - satellite
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	thermograph9 - mode
	thermograph1 - mode
	thermograph2 - mode
	infrared5 - mode
	thermograph7 - mode
	image0 - mode
	spectrograph8 - mode
	thermograph3 - mode
	image4 - mode
	spectrograph6 - mode
	Star1 - direction
	GroundStation0 - direction
	GroundStation6 - direction
	Star7 - direction
	Star3 - direction
	GroundStation9 - direction
	GroundStation8 - direction
	GroundStation5 - direction
	Star2 - direction
	Star4 - direction
	Star10 - direction
	Planet11 - direction
	Star12 - direction
	Phenomenon13 - direction
	Star14 - direction
	Star15 - direction
	Phenomenon16 - direction
	Star17 - direction
	Planet18 - direction
	Phenomenon19 - direction
)
(:init
	(supports instrument0 thermograph1)
	(supports instrument0 image0)
	(supports instrument0 thermograph9)
	(calibration_target instrument0 GroundStation6)
	(supports instrument1 spectrograph6)
	(calibration_target instrument1 GroundStation5)
	(supports instrument2 image4)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 Star1)
	(supports instrument3 thermograph9)
	(supports instrument3 image4)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 Star2)
	(supports instrument4 image4)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 Star7)
	(supports instrument5 spectrograph8)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 Star1)
	(calibration_target instrument5 GroundStation0)
	(supports instrument6 spectrograph6)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 Star2)
	(supports instrument7 infrared5)
	(supports instrument7 thermograph3)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 GroundStation9)
	(supports instrument8 image0)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 GroundStation5)
	(supports instrument9 thermograph2)
	(supports instrument9 spectrograph6)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 GroundStation9)
	(calibration_target instrument9 GroundStation8)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(on_board instrument9 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon16)
	(supports instrument10 spectrograph8)
	(supports instrument10 infrared5)
	(supports instrument10 thermograph7)
	(calibration_target instrument10 GroundStation6)
	(calibration_target instrument10 Star1)
	(calibration_target instrument10 GroundStation9)
	(supports instrument11 thermograph2)
	(supports instrument11 thermograph9)
	(calibration_target instrument11 Star1)
	(calibration_target instrument11 Star7)
	(calibration_target instrument11 GroundStation9)
	(supports instrument12 spectrograph8)
	(supports instrument12 thermograph2)
	(calibration_target instrument12 GroundStation9)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star10)
	(supports instrument13 spectrograph6)
	(calibration_target instrument13 Star1)
	(supports instrument14 spectrograph6)
	(supports instrument14 thermograph7)
	(calibration_target instrument14 GroundStation6)
	(supports instrument15 infrared5)
	(calibration_target instrument15 GroundStation6)
	(calibration_target instrument15 Star3)
	(supports instrument16 thermograph7)
	(supports instrument16 spectrograph6)
	(supports instrument16 thermograph1)
	(calibration_target instrument16 GroundStation5)
	(calibration_target instrument16 GroundStation6)
	(supports instrument17 image4)
	(calibration_target instrument17 Star1)
	(supports instrument18 thermograph1)
	(supports instrument18 thermograph3)
	(calibration_target instrument18 Star2)
	(calibration_target instrument18 Star4)
	(calibration_target instrument18 GroundStation9)
	(supports instrument19 image0)
	(supports instrument19 thermograph7)
	(calibration_target instrument19 GroundStation6)
	(calibration_target instrument19 GroundStation5)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star14)
	(supports instrument20 infrared5)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 GroundStation0)
	(calibration_target instrument20 GroundStation8)
	(supports instrument21 infrared5)
	(supports instrument21 thermograph2)
	(supports instrument21 spectrograph6)
	(calibration_target instrument21 GroundStation0)
	(calibration_target instrument21 Star4)
	(supports instrument22 thermograph1)
	(supports instrument22 thermograph3)
	(supports instrument22 thermograph7)
	(calibration_target instrument22 Star3)
	(calibration_target instrument22 GroundStation8)
	(calibration_target instrument22 Star7)
	(supports instrument23 spectrograph8)
	(supports instrument23 thermograph3)
	(calibration_target instrument23 Star3)
	(calibration_target instrument23 GroundStation9)
	(calibration_target instrument23 GroundStation8)
	(supports instrument24 thermograph9)
	(calibration_target instrument24 Star2)
	(calibration_target instrument24 Star4)
	(supports instrument25 image4)
	(supports instrument25 thermograph9)
	(supports instrument25 thermograph7)
	(calibration_target instrument25 GroundStation6)
	(calibration_target instrument25 Star1)
	(supports instrument26 infrared5)
	(supports instrument26 spectrograph6)
	(supports instrument26 thermograph2)
	(calibration_target instrument26 Star4)
	(calibration_target instrument26 GroundStation8)
	(calibration_target instrument26 Star1)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star7)
	(supports instrument27 image4)
	(calibration_target instrument27 GroundStation9)
	(calibration_target instrument27 Star7)
	(calibration_target instrument27 GroundStation8)
	(supports instrument28 image4)
	(supports instrument28 thermograph7)
	(calibration_target instrument28 Star4)
	(calibration_target instrument28 GroundStation8)
	(supports instrument29 spectrograph8)
	(supports instrument29 thermograph3)
	(supports instrument29 spectrograph6)
	(calibration_target instrument29 GroundStation6)
	(calibration_target instrument29 Star1)
	(calibration_target instrument29 Star2)
	(supports instrument30 spectrograph8)
	(supports instrument30 thermograph9)
	(supports instrument30 thermograph1)
	(calibration_target instrument30 GroundStation5)
	(calibration_target instrument30 GroundStation8)
	(supports instrument31 thermograph9)
	(supports instrument31 image0)
	(supports instrument31 infrared5)
	(calibration_target instrument31 Star2)
	(calibration_target instrument31 GroundStation6)
	(calibration_target instrument31 GroundStation9)
	(supports instrument32 infrared5)
	(calibration_target instrument32 GroundStation8)
	(calibration_target instrument32 GroundStation9)
	(supports instrument33 spectrograph8)
	(calibration_target instrument33 GroundStation6)
	(calibration_target instrument33 Star1)
	(calibration_target instrument33 GroundStation9)
	(supports instrument34 thermograph7)
	(supports instrument34 spectrograph6)
	(supports instrument34 thermograph9)
	(calibration_target instrument34 GroundStation0)
	(calibration_target instrument34 GroundStation9)
	(calibration_target instrument34 GroundStation6)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation0)
	(supports instrument35 spectrograph8)
	(calibration_target instrument35 Star7)
	(supports instrument36 spectrograph8)
	(supports instrument36 thermograph1)
	(supports instrument36 image0)
	(calibration_target instrument36 GroundStation5)
	(calibration_target instrument36 Star3)
	(calibration_target instrument36 Star4)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star2)
	(supports instrument37 thermograph9)
	(supports instrument37 thermograph2)
	(supports instrument37 thermograph1)
	(calibration_target instrument37 Star7)
	(supports instrument38 thermograph1)
	(calibration_target instrument38 GroundStation6)
	(calibration_target instrument38 GroundStation5)
	(supports instrument39 spectrograph8)
	(supports instrument39 image0)
	(supports instrument39 thermograph7)
	(calibration_target instrument39 Star7)
	(calibration_target instrument39 Star4)
	(calibration_target instrument39 GroundStation6)
	(supports instrument40 infrared5)
	(supports instrument40 image4)
	(supports instrument40 image0)
	(calibration_target instrument40 GroundStation5)
	(calibration_target instrument40 GroundStation0)
	(supports instrument41 image4)
	(supports instrument41 thermograph9)
	(calibration_target instrument41 Star2)
	(supports instrument42 thermograph7)
	(supports instrument42 image4)
	(calibration_target instrument42 Star7)
	(calibration_target instrument42 GroundStation5)
	(calibration_target instrument42 Star3)
	(supports instrument43 thermograph3)
	(calibration_target instrument43 Star7)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon19)
	(supports instrument44 infrared5)
	(calibration_target instrument44 GroundStation0)
	(supports instrument45 image4)
	(supports instrument45 image0)
	(calibration_target instrument45 GroundStation9)
	(calibration_target instrument45 GroundStation0)
	(supports instrument46 thermograph9)
	(supports instrument46 thermograph7)
	(calibration_target instrument46 GroundStation0)
	(supports instrument47 thermograph7)
	(calibration_target instrument47 GroundStation0)
	(calibration_target instrument47 GroundStation5)
	(calibration_target instrument47 Star3)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star17)
	(supports instrument48 thermograph3)
	(supports instrument48 image4)
	(supports instrument48 thermograph1)
	(calibration_target instrument48 GroundStation0)
	(on_board instrument48 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation9)
	(supports instrument49 thermograph3)
	(supports instrument49 thermograph1)
	(calibration_target instrument49 GroundStation0)
	(calibration_target instrument49 Star7)
	(supports instrument50 image0)
	(supports instrument50 spectrograph6)
	(calibration_target instrument50 GroundStation6)
	(supports instrument51 infrared5)
	(supports instrument51 thermograph1)
	(calibration_target instrument51 GroundStation5)
	(supports instrument52 image0)
	(supports instrument52 thermograph9)
	(calibration_target instrument52 Star3)
	(calibration_target instrument52 Star4)
	(supports instrument53 thermograph3)
	(supports instrument53 thermograph1)
	(supports instrument53 thermograph7)
	(calibration_target instrument53 Star7)
	(calibration_target instrument53 GroundStation6)
	(supports instrument54 thermograph3)
	(supports instrument54 infrared5)
	(supports instrument54 thermograph2)
	(calibration_target instrument54 Star3)
	(supports instrument55 spectrograph6)
	(supports instrument55 thermograph7)
	(calibration_target instrument55 GroundStation9)
	(supports instrument56 thermograph7)
	(supports instrument56 spectrograph8)
	(calibration_target instrument56 GroundStation5)
	(calibration_target instrument56 Star4)
	(calibration_target instrument56 GroundStation9)
	(supports instrument57 spectrograph8)
	(supports instrument57 image0)
	(calibration_target instrument57 Star2)
	(calibration_target instrument57 GroundStation5)
	(calibration_target instrument57 GroundStation8)
	(supports instrument58 spectrograph6)
	(supports instrument58 image4)
	(supports instrument58 thermograph3)
	(calibration_target instrument58 Star4)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star10)
)
(:goal (and
	(pointing satellite0 Star7)
	(pointing satellite2 Star4)
	(pointing satellite4 GroundStation0)
	(pointing satellite8 Star15)
	(have_image Star10 image4)
	(have_image Star10 infrared5)
	(have_image Planet11 image4)
	(have_image Planet11 thermograph2)
	(have_image Planet11 infrared5)
	(have_image Star12 spectrograph6)
	(have_image Star12 thermograph3)
	(have_image Star12 infrared5)
	(have_image Star14 thermograph3)
	(have_image Star14 infrared5)
	(have_image Star15 thermograph2)
	(have_image Star15 thermograph1)
	(have_image Star15 image0)
	(have_image Phenomenon16 thermograph3)
	(have_image Phenomenon16 spectrograph8)
	(have_image Star17 thermograph9)
	(have_image Planet18 image4)
	(have_image Phenomenon19 thermograph9)
	(have_image Phenomenon19 thermograph3)
))

)
