(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	satellite3 - satellite
	instrument4 - instrument
	satellite4 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite5 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite6 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite7 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite8 - satellite
	instrument25 - instrument
	satellite9 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	image1 - mode
	spectrograph9 - mode
	infrared0 - mode
	image6 - mode
	thermograph4 - mode
	image5 - mode
	thermograph2 - mode
	thermograph7 - mode
	image3 - mode
	spectrograph8 - mode
	GroundStation6 - direction
	Star5 - direction
	GroundStation0 - direction
	Star3 - direction
	GroundStation7 - direction
	Star1 - direction
	Star9 - direction
	GroundStation4 - direction
	Star2 - direction
	Star8 - direction
	Star10 - direction
	Phenomenon11 - direction
	Planet12 - direction
	Phenomenon13 - direction
	Star14 - direction
	Planet15 - direction
	Star16 - direction
	Phenomenon17 - direction
	Planet18 - direction
	Star19 - direction
)
(:init
	(supports instrument0 thermograph2)
	(supports instrument0 spectrograph8)
	(supports instrument0 image3)
	(calibration_target instrument0 Star2)
	(calibration_target instrument0 Star1)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star5)
	(supports instrument1 infrared0)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 Star1)
	(supports instrument2 image3)
	(supports instrument2 infrared0)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 GroundStation0)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star8)
	(supports instrument3 image6)
	(supports instrument3 image5)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 Star5)
	(calibration_target instrument3 GroundStation4)
	(on_board instrument3 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star1)
	(supports instrument4 infrared0)
	(supports instrument4 thermograph4)
	(supports instrument4 image3)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 Star3)
	(on_board instrument4 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star1)
	(supports instrument5 image3)
	(supports instrument5 thermograph7)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 GroundStation0)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 Star2)
	(calibration_target instrument6 Star1)
	(calibration_target instrument6 GroundStation6)
	(supports instrument7 thermograph4)
	(supports instrument7 thermograph7)
	(calibration_target instrument7 GroundStation7)
	(calibration_target instrument7 Star8)
	(supports instrument8 image6)
	(supports instrument8 thermograph7)
	(supports instrument8 infrared0)
	(calibration_target instrument8 Star2)
	(calibration_target instrument8 Star3)
	(calibration_target instrument8 Star1)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 GroundStation4)
	(calibration_target instrument9 GroundStation7)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 Star2)
	(calibration_target instrument10 Star1)
	(supports instrument11 spectrograph9)
	(supports instrument11 thermograph7)
	(supports instrument11 image6)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 GroundStation7)
	(supports instrument12 image1)
	(supports instrument12 image6)
	(supports instrument12 thermograph2)
	(calibration_target instrument12 Star3)
	(supports instrument13 infrared0)
	(calibration_target instrument13 Star2)
	(calibration_target instrument13 Star9)
	(calibration_target instrument13 Star3)
	(on_board instrument5 satellite4)
	(on_board instrument6 satellite4)
	(on_board instrument7 satellite4)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star3)
	(supports instrument14 thermograph2)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 GroundStation6)
	(supports instrument15 image3)
	(calibration_target instrument15 Star2)
	(supports instrument16 image5)
	(calibration_target instrument16 GroundStation7)
	(calibration_target instrument16 Star3)
	(calibration_target instrument16 GroundStation4)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star8)
	(supports instrument17 thermograph4)
	(supports instrument17 image1)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 GroundStation7)
	(supports instrument18 image6)
	(supports instrument18 spectrograph8)
	(calibration_target instrument18 GroundStation6)
	(calibration_target instrument18 GroundStation7)
	(calibration_target instrument18 Star9)
	(supports instrument19 image3)
	(calibration_target instrument19 Star5)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon11)
	(supports instrument20 image3)
	(supports instrument20 image1)
	(supports instrument20 thermograph2)
	(calibration_target instrument20 Star2)
	(calibration_target instrument20 Star3)
	(supports instrument21 image5)
	(supports instrument21 infrared0)
	(supports instrument21 thermograph2)
	(calibration_target instrument21 Star8)
	(calibration_target instrument21 Star1)
	(calibration_target instrument21 GroundStation6)
	(supports instrument22 image5)
	(supports instrument22 thermograph7)
	(calibration_target instrument22 Star8)
	(calibration_target instrument22 Star1)
	(supports instrument23 infrared0)
	(supports instrument23 image6)
	(calibration_target instrument23 GroundStation6)
	(calibration_target instrument23 Star8)
	(supports instrument24 spectrograph8)
	(calibration_target instrument24 Star3)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(on_board instrument23 satellite7)
	(on_board instrument24 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet18)
	(supports instrument25 image6)
	(calibration_target instrument25 Star2)
	(calibration_target instrument25 Star8)
	(calibration_target instrument25 GroundStation0)
	(on_board instrument25 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet18)
	(supports instrument26 image5)
	(supports instrument26 image1)
	(supports instrument26 spectrograph9)
	(calibration_target instrument26 GroundStation6)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 Star2)
	(supports instrument27 thermograph7)
	(supports instrument27 image5)
	(calibration_target instrument27 Star5)
	(calibration_target instrument27 Star8)
	(supports instrument28 image6)
	(supports instrument28 thermograph7)
	(calibration_target instrument28 Star2)
	(supports instrument29 image6)
	(supports instrument29 spectrograph8)
	(calibration_target instrument29 Star8)
	(calibration_target instrument29 GroundStation0)
	(supports instrument30 infrared0)
	(supports instrument30 thermograph2)
	(supports instrument30 spectrograph9)
	(calibration_target instrument30 GroundStation7)
	(calibration_target instrument30 Star3)
	(calibration_target instrument30 Star1)
	(supports instrument31 spectrograph8)
	(supports instrument31 thermograph4)
	(supports instrument31 image6)
	(calibration_target instrument31 GroundStation4)
	(supports instrument32 spectrograph8)
	(supports instrument32 image3)
	(supports instrument32 image5)
	(calibration_target instrument32 Star1)
	(supports instrument33 thermograph7)
	(supports instrument33 spectrograph8)
	(supports instrument33 thermograph2)
	(calibration_target instrument33 Star2)
	(calibration_target instrument33 Star9)
	(supports instrument34 image3)
	(calibration_target instrument34 GroundStation4)
	(calibration_target instrument34 Star2)
	(calibration_target instrument34 Star9)
	(supports instrument35 spectrograph8)
	(calibration_target instrument35 Star8)
	(calibration_target instrument35 Star2)
	(on_board instrument26 satellite9)
	(on_board instrument27 satellite9)
	(on_board instrument28 satellite9)
	(on_board instrument29 satellite9)
	(on_board instrument30 satellite9)
	(on_board instrument31 satellite9)
	(on_board instrument32 satellite9)
	(on_board instrument33 satellite9)
	(on_board instrument34 satellite9)
	(on_board instrument35 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation6)
)
(:goal (and
	(pointing satellite0 Star5)
	(pointing satellite1 Phenomenon13)
	(pointing satellite5 Star1)
	(pointing satellite6 GroundStation4)
	(have_image Star10 image3)
	(have_image Star10 image5)
	(have_image Phenomenon11 image5)
	(have_image Planet12 spectrograph9)
	(have_image Planet12 image6)
	(have_image Phenomenon13 thermograph4)
	(have_image Star14 thermograph7)
	(have_image Star14 image6)
	(have_image Planet15 infrared0)
	(have_image Planet15 thermograph7)
	(have_image Planet15 image6)
	(have_image Star16 spectrograph9)
	(have_image Phenomenon17 spectrograph8)
	(have_image Planet18 spectrograph8)
	(have_image Planet18 spectrograph9)
	(have_image Planet18 image1)
	(have_image Star19 image5)
	(have_image Star19 image3)
	(have_image Star19 infrared0)
))

)
