(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite4 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite5 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite6 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	satellite7 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite8 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	satellite9 - satellite
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	infrared5 - mode
	image3 - mode
	spectrograph6 - mode
	thermograph4 - mode
	spectrograph9 - mode
	infrared8 - mode
	infrared0 - mode
	spectrograph2 - mode
	image1 - mode
	infrared7 - mode
	GroundStation0 - direction
	Star2 - direction
	Star1 - direction
	GroundStation5 - direction
	GroundStation4 - direction
	Star6 - direction
	GroundStation7 - direction
	Star3 - direction
	GroundStation8 - direction
	GroundStation9 - direction
	Star10 - direction
	Planet11 - direction
	Planet12 - direction
	Star13 - direction
	Phenomenon14 - direction
	Phenomenon15 - direction
	Star16 - direction
	Planet17 - direction
	Star18 - direction
	Planet19 - direction
)
(:init
	(supports instrument0 image1)
	(supports instrument0 spectrograph9)
	(supports instrument0 infrared7)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 GroundStation9)
	(supports instrument1 infrared7)
	(supports instrument1 spectrograph9)
	(supports instrument1 image3)
	(calibration_target instrument1 Star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation8)
	(supports instrument2 infrared7)
	(supports instrument2 infrared0)
	(calibration_target instrument2 GroundStation5)
	(supports instrument3 infrared8)
	(supports instrument3 spectrograph6)
	(supports instrument3 spectrograph2)
	(calibration_target instrument3 Star2)
	(calibration_target instrument3 GroundStation9)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet11)
	(supports instrument4 spectrograph6)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 Star1)
	(supports instrument5 image3)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 GroundStation0)
	(supports instrument6 infrared0)
	(supports instrument6 image1)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 GroundStation5)
	(calibration_target instrument6 GroundStation0)
	(calibration_target instrument6 Star3)
	(supports instrument7 spectrograph6)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation5)
	(supports instrument8 spectrograph9)
	(calibration_target instrument8 GroundStation7)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation4)
	(supports instrument9 spectrograph9)
	(supports instrument9 infrared8)
	(calibration_target instrument9 Star6)
	(calibration_target instrument9 Star2)
	(supports instrument10 image3)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 GroundStation9)
	(supports instrument11 spectrograph2)
	(supports instrument11 infrared7)
	(supports instrument11 image1)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 Star1)
	(supports instrument12 infrared7)
	(supports instrument12 spectrograph9)
	(calibration_target instrument12 GroundStation8)
	(calibration_target instrument12 GroundStation7)
	(supports instrument13 thermograph4)
	(supports instrument13 spectrograph2)
	(supports instrument13 image1)
	(calibration_target instrument13 GroundStation4)
	(calibration_target instrument13 GroundStation7)
	(supports instrument14 image3)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation5)
	(supports instrument15 image1)
	(calibration_target instrument15 Star1)
	(supports instrument16 image1)
	(supports instrument16 spectrograph9)
	(calibration_target instrument16 GroundStation4)
	(calibration_target instrument16 Star2)
	(calibration_target instrument16 Star3)
	(supports instrument17 infrared8)
	(supports instrument17 spectrograph6)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 Star3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet19)
	(supports instrument18 infrared8)
	(calibration_target instrument18 Star1)
	(calibration_target instrument18 Star6)
	(supports instrument19 infrared8)
	(supports instrument19 infrared0)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 GroundStation7)
	(supports instrument20 infrared7)
	(calibration_target instrument20 Star2)
	(calibration_target instrument20 GroundStation4)
	(supports instrument21 spectrograph9)
	(calibration_target instrument21 GroundStation5)
	(supports instrument22 infrared7)
	(supports instrument22 spectrograph2)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 Star1)
	(calibration_target instrument22 GroundStation4)
	(calibration_target instrument22 GroundStation7)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 GroundStation7)
	(calibration_target instrument23 Star3)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star10)
	(supports instrument24 infrared8)
	(supports instrument24 thermograph4)
	(supports instrument24 infrared5)
	(calibration_target instrument24 Star2)
	(calibration_target instrument24 Star1)
	(calibration_target instrument24 GroundStation4)
	(supports instrument25 infrared7)
	(supports instrument25 image1)
	(calibration_target instrument25 GroundStation5)
	(calibration_target instrument25 Star6)
	(calibration_target instrument25 GroundStation9)
	(supports instrument26 infrared5)
	(supports instrument26 thermograph4)
	(calibration_target instrument26 GroundStation4)
	(calibration_target instrument26 Star1)
	(calibration_target instrument26 Star2)
	(supports instrument27 spectrograph9)
	(supports instrument27 image3)
	(calibration_target instrument27 GroundStation8)
	(calibration_target instrument27 Star6)
	(supports instrument28 spectrograph6)
	(supports instrument28 infrared7)
	(calibration_target instrument28 Star1)
	(calibration_target instrument28 GroundStation4)
	(calibration_target instrument28 Star6)
	(supports instrument29 infrared7)
	(calibration_target instrument29 GroundStation4)
	(calibration_target instrument29 GroundStation9)
	(calibration_target instrument29 Star2)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument30 infrared8)
	(supports instrument30 infrared7)
	(calibration_target instrument30 Star3)
	(calibration_target instrument30 GroundStation5)
	(supports instrument31 spectrograph2)
	(calibration_target instrument31 GroundStation5)
	(calibration_target instrument31 GroundStation8)
	(supports instrument32 thermograph4)
	(supports instrument32 infrared7)
	(calibration_target instrument32 Star3)
	(calibration_target instrument32 Star6)
	(supports instrument33 image1)
	(calibration_target instrument33 GroundStation0)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star6)
	(supports instrument34 infrared5)
	(supports instrument34 infrared8)
	(calibration_target instrument34 Star2)
	(supports instrument35 infrared0)
	(supports instrument35 infrared5)
	(calibration_target instrument35 Star2)
	(supports instrument36 image1)
	(supports instrument36 infrared5)
	(calibration_target instrument36 Star2)
	(supports instrument37 spectrograph9)
	(supports instrument37 image1)
	(supports instrument37 infrared0)
	(calibration_target instrument37 GroundStation8)
	(supports instrument38 infrared7)
	(calibration_target instrument38 Star3)
	(calibration_target instrument38 Star1)
	(supports instrument39 spectrograph9)
	(calibration_target instrument39 Star6)
	(calibration_target instrument39 GroundStation0)
	(supports instrument40 spectrograph2)
	(supports instrument40 infrared5)
	(calibration_target instrument40 Star1)
	(calibration_target instrument40 GroundStation9)
	(calibration_target instrument40 Star3)
	(supports instrument41 thermograph4)
	(supports instrument41 image1)
	(calibration_target instrument41 Star2)
	(calibration_target instrument41 GroundStation7)
	(supports instrument42 spectrograph2)
	(supports instrument42 infrared8)
	(calibration_target instrument42 GroundStation5)
	(calibration_target instrument42 Star3)
	(supports instrument43 infrared7)
	(supports instrument43 infrared5)
	(supports instrument43 image3)
	(calibration_target instrument43 GroundStation4)
	(calibration_target instrument43 GroundStation0)
	(calibration_target instrument43 Star1)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation7)
	(supports instrument44 infrared0)
	(supports instrument44 infrared5)
	(calibration_target instrument44 GroundStation0)
	(calibration_target instrument44 GroundStation9)
	(calibration_target instrument44 Star2)
	(supports instrument45 infrared7)
	(supports instrument45 spectrograph2)
	(calibration_target instrument45 GroundStation8)
	(calibration_target instrument45 Star6)
	(supports instrument46 infrared5)
	(calibration_target instrument46 Star3)
	(calibration_target instrument46 Star2)
	(supports instrument47 infrared0)
	(calibration_target instrument47 GroundStation5)
	(supports instrument48 image3)
	(supports instrument48 spectrograph2)
	(supports instrument48 infrared5)
	(calibration_target instrument48 GroundStation0)
	(supports instrument49 infrared7)
	(supports instrument49 spectrograph2)
	(calibration_target instrument49 Star1)
	(supports instrument50 infrared0)
	(supports instrument50 infrared5)
	(supports instrument50 spectrograph2)
	(calibration_target instrument50 Star3)
	(supports instrument51 spectrograph9)
	(supports instrument51 image1)
	(supports instrument51 thermograph4)
	(calibration_target instrument51 Star3)
	(supports instrument52 infrared8)
	(supports instrument52 spectrograph2)
	(supports instrument52 infrared7)
	(calibration_target instrument52 Star1)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon15)
	(supports instrument53 spectrograph6)
	(supports instrument53 thermograph4)
	(supports instrument53 spectrograph9)
	(calibration_target instrument53 GroundStation7)
	(calibration_target instrument53 Star2)
	(supports instrument54 image1)
	(supports instrument54 thermograph4)
	(calibration_target instrument54 GroundStation5)
	(calibration_target instrument54 GroundStation4)
	(supports instrument55 spectrograph9)
	(supports instrument55 image3)
	(supports instrument55 infrared0)
	(calibration_target instrument55 GroundStation5)
	(calibration_target instrument55 GroundStation9)
	(calibration_target instrument55 Star1)
	(supports instrument56 spectrograph6)
	(supports instrument56 spectrograph2)
	(supports instrument56 image1)
	(calibration_target instrument56 GroundStation4)
	(calibration_target instrument56 GroundStation8)
	(supports instrument57 image1)
	(supports instrument57 infrared8)
	(calibration_target instrument57 Star6)
	(supports instrument58 spectrograph9)
	(supports instrument58 thermograph4)
	(calibration_target instrument58 GroundStation7)
	(supports instrument59 spectrograph2)
	(supports instrument59 infrared0)
	(supports instrument59 infrared8)
	(calibration_target instrument59 GroundStation9)
	(calibration_target instrument59 Star3)
	(supports instrument60 infrared7)
	(supports instrument60 image1)
	(supports instrument60 spectrograph2)
	(calibration_target instrument60 GroundStation9)
	(calibration_target instrument60 GroundStation8)
	(calibration_target instrument60 Star3)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(on_board instrument59 satellite9)
	(on_board instrument60 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star10)
)
(:goal (and
	(pointing satellite2 Planet11)
	(pointing satellite3 Star1)
	(pointing satellite5 Star16)
	(pointing satellite7 Phenomenon14)
	(pointing satellite8 Planet12)
	(have_image Star10 infrared5)
	(have_image Planet11 infrared5)
	(have_image Planet11 spectrograph9)
	(have_image Planet11 image1)
	(have_image Planet12 thermograph4)
	(have_image Star13 thermograph4)
	(have_image Star13 spectrograph6)
	(have_image Phenomenon14 infrared7)
	(have_image Phenomenon15 image1)
	(have_image Star16 spectrograph9)
	(have_image Planet17 spectrograph2)
	(have_image Planet17 spectrograph6)
	(have_image Planet17 spectrograph9)
	(have_image Star18 image3)
	(have_image Planet19 spectrograph2)
	(have_image Planet19 infrared7)
))

)
