(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite2 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite4 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite5 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite6 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	satellite7 - satellite
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	satellite8 - satellite
	instrument51 - instrument
	satellite9 - satellite
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	spectrograph8 - mode
	infrared0 - mode
	image4 - mode
	image1 - mode
	thermograph2 - mode
	spectrograph6 - mode
	infrared7 - mode
	infrared3 - mode
	spectrograph5 - mode
	image9 - mode
	Star8 - direction
	Star1 - direction
	Star2 - direction
	Star7 - direction
	GroundStation9 - direction
	GroundStation6 - direction
	Star5 - direction
	Star4 - direction
	Star0 - direction
	Star3 - direction
	Planet10 - direction
	Phenomenon11 - direction
	Star12 - direction
	Star13 - direction
	Planet14 - direction
	Planet15 - direction
	Star16 - direction
	Phenomenon17 - direction
	Phenomenon18 - direction
	Phenomenon19 - direction
)
(:init
	(supports instrument0 image9)
	(supports instrument0 image1)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 Star4)
	(supports instrument1 infrared0)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 Star0)
	(supports instrument2 image9)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 Star1)
	(supports instrument3 spectrograph8)
	(supports instrument3 spectrograph5)
	(supports instrument3 infrared3)
	(calibration_target instrument3 Star4)
	(calibration_target instrument3 Star2)
	(calibration_target instrument3 Star7)
	(supports instrument4 image9)
	(supports instrument4 image1)
	(supports instrument4 spectrograph5)
	(calibration_target instrument4 Star8)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 Star2)
	(supports instrument5 spectrograph6)
	(supports instrument5 image1)
	(calibration_target instrument5 Star5)
	(supports instrument6 image9)
	(supports instrument6 infrared3)
	(supports instrument6 spectrograph5)
	(calibration_target instrument6 Star8)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon11)
	(supports instrument7 infrared0)
	(supports instrument7 image9)
	(calibration_target instrument7 Star2)
	(calibration_target instrument7 Star1)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star5)
	(supports instrument9 spectrograph8)
	(supports instrument9 infrared3)
	(supports instrument9 spectrograph6)
	(calibration_target instrument9 Star0)
	(supports instrument10 image4)
	(supports instrument10 thermograph2)
	(supports instrument10 infrared3)
	(calibration_target instrument10 Star5)
	(supports instrument11 infrared3)
	(calibration_target instrument11 Star8)
	(calibration_target instrument11 Star4)
	(supports instrument12 infrared0)
	(supports instrument12 thermograph2)
	(supports instrument12 spectrograph5)
	(calibration_target instrument12 Star8)
	(calibration_target instrument12 Star2)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation6)
	(supports instrument13 image4)
	(calibration_target instrument13 Star4)
	(calibration_target instrument13 Star7)
	(calibration_target instrument13 GroundStation9)
	(supports instrument14 spectrograph6)
	(supports instrument14 spectrograph5)
	(calibration_target instrument14 Star1)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 Star7)
	(supports instrument15 spectrograph6)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 Star5)
	(calibration_target instrument15 Star2)
	(supports instrument16 infrared0)
	(supports instrument16 image1)
	(calibration_target instrument16 Star0)
	(calibration_target instrument16 GroundStation6)
	(supports instrument17 infrared0)
	(calibration_target instrument17 GroundStation9)
	(supports instrument18 spectrograph5)
	(supports instrument18 spectrograph8)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 Star4)
	(calibration_target instrument18 Star5)
	(supports instrument19 spectrograph8)
	(supports instrument19 infrared7)
	(supports instrument19 image9)
	(calibration_target instrument19 Star5)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star12)
	(supports instrument20 image4)
	(calibration_target instrument20 Star5)
	(supports instrument21 infrared0)
	(calibration_target instrument21 Star4)
	(supports instrument22 image9)
	(supports instrument22 spectrograph8)
	(supports instrument22 image1)
	(calibration_target instrument22 Star4)
	(calibration_target instrument22 Star7)
	(supports instrument23 thermograph2)
	(calibration_target instrument23 Star4)
	(supports instrument24 infrared3)
	(supports instrument24 image9)
	(supports instrument24 spectrograph8)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 Star7)
	(calibration_target instrument24 Star5)
	(supports instrument25 infrared3)
	(supports instrument25 spectrograph5)
	(calibration_target instrument25 Star4)
	(calibration_target instrument25 Star0)
	(supports instrument26 infrared3)
	(supports instrument26 thermograph2)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 Star7)
	(supports instrument27 image1)
	(supports instrument27 infrared7)
	(supports instrument27 image4)
	(calibration_target instrument27 Star8)
	(supports instrument28 spectrograph6)
	(calibration_target instrument28 Star8)
	(calibration_target instrument28 Star7)
	(supports instrument29 image1)
	(supports instrument29 infrared3)
	(calibration_target instrument29 Star5)
	(calibration_target instrument29 GroundStation6)
	(calibration_target instrument29 Star3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon11)
	(supports instrument30 spectrograph6)
	(supports instrument30 spectrograph5)
	(supports instrument30 infrared0)
	(calibration_target instrument30 Star7)
	(supports instrument31 infrared3)
	(calibration_target instrument31 Star2)
	(calibration_target instrument31 Star4)
	(supports instrument32 spectrograph8)
	(supports instrument32 image1)
	(supports instrument32 spectrograph6)
	(calibration_target instrument32 Star4)
	(calibration_target instrument32 Star8)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star12)
	(supports instrument33 spectrograph5)
	(supports instrument33 image1)
	(calibration_target instrument33 Star7)
	(supports instrument34 spectrograph6)
	(supports instrument34 image9)
	(calibration_target instrument34 Star3)
	(supports instrument35 infrared3)
	(supports instrument35 thermograph2)
	(calibration_target instrument35 Star5)
	(calibration_target instrument35 Star2)
	(supports instrument36 spectrograph6)
	(supports instrument36 spectrograph8)
	(calibration_target instrument36 Star8)
	(calibration_target instrument36 Star3)
	(calibration_target instrument36 GroundStation6)
	(supports instrument37 spectrograph8)
	(calibration_target instrument37 Star8)
	(calibration_target instrument37 GroundStation6)
	(supports instrument38 infrared3)
	(supports instrument38 spectrograph6)
	(calibration_target instrument38 GroundStation9)
	(calibration_target instrument38 Star1)
	(supports instrument39 spectrograph6)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 Star4)
	(calibration_target instrument39 GroundStation9)
	(supports instrument40 image1)
	(supports instrument40 image4)
	(supports instrument40 infrared7)
	(calibration_target instrument40 Star7)
	(calibration_target instrument40 Star0)
	(supports instrument41 spectrograph6)
	(supports instrument41 image4)
	(calibration_target instrument41 Star1)
	(calibration_target instrument41 GroundStation6)
	(supports instrument42 infrared3)
	(supports instrument42 image9)
	(supports instrument42 spectrograph5)
	(calibration_target instrument42 GroundStation9)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(on_board instrument42 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star13)
	(supports instrument43 image1)
	(supports instrument43 spectrograph8)
	(calibration_target instrument43 GroundStation9)
	(calibration_target instrument43 Star4)
	(supports instrument44 infrared7)
	(supports instrument44 image4)
	(calibration_target instrument44 Star4)
	(supports instrument45 spectrograph5)
	(supports instrument45 infrared0)
	(calibration_target instrument45 GroundStation9)
	(calibration_target instrument45 Star3)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star1)
	(supports instrument46 infrared3)
	(supports instrument46 spectrograph5)
	(supports instrument46 image9)
	(calibration_target instrument46 GroundStation6)
	(calibration_target instrument46 Star8)
	(supports instrument47 image4)
	(supports instrument47 infrared7)
	(supports instrument47 spectrograph8)
	(calibration_target instrument47 Star7)
	(calibration_target instrument47 Star2)
	(calibration_target instrument47 Star0)
	(supports instrument48 spectrograph5)
	(supports instrument48 infrared0)
	(calibration_target instrument48 Star4)
	(calibration_target instrument48 Star1)
	(supports instrument49 infrared7)
	(calibration_target instrument49 Star4)
	(supports instrument50 image9)
	(calibration_target instrument50 Star1)
	(calibration_target instrument50 Star0)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon17)
	(supports instrument51 image4)
	(supports instrument51 spectrograph6)
	(supports instrument51 spectrograph5)
	(calibration_target instrument51 Star4)
	(on_board instrument51 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet10)
	(supports instrument52 image1)
	(calibration_target instrument52 GroundStation6)
	(calibration_target instrument52 Star2)
	(calibration_target instrument52 Star7)
	(supports instrument53 spectrograph6)
	(calibration_target instrument53 Star7)
	(supports instrument54 spectrograph5)
	(calibration_target instrument54 Star5)
	(calibration_target instrument54 GroundStation9)
	(calibration_target instrument54 Star7)
	(supports instrument55 spectrograph6)
	(supports instrument55 image9)
	(supports instrument55 thermograph2)
	(calibration_target instrument55 Star4)
	(supports instrument56 spectrograph5)
	(supports instrument56 infrared7)
	(supports instrument56 image9)
	(calibration_target instrument56 Star4)
	(supports instrument57 infrared3)
	(calibration_target instrument57 GroundStation6)
	(calibration_target instrument57 Star5)
	(supports instrument58 spectrograph5)
	(supports instrument58 infrared3)
	(calibration_target instrument58 Star5)
	(calibration_target instrument58 Star3)
	(supports instrument59 spectrograph5)
	(calibration_target instrument59 Star0)
	(calibration_target instrument59 Star4)
	(supports instrument60 image9)
	(calibration_target instrument60 Star3)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(on_board instrument59 satellite9)
	(on_board instrument60 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon19)
)
(:goal (and
	(have_image Planet10 image4)
	(have_image Planet10 thermograph2)
	(have_image Planet10 spectrograph6)
	(have_image Phenomenon11 image1)
	(have_image Phenomenon11 thermograph2)
	(have_image Star12 spectrograph6)
	(have_image Star12 image4)
	(have_image Star12 infrared7)
	(have_image Star13 spectrograph8)
	(have_image Star13 infrared7)
	(have_image Star13 thermograph2)
	(have_image Planet14 spectrograph5)
	(have_image Planet14 infrared7)
	(have_image Planet14 image4)
	(have_image Planet15 image9)
	(have_image Phenomenon17 spectrograph6)
	(have_image Phenomenon17 infrared0)
	(have_image Phenomenon17 image1)
	(have_image Phenomenon18 spectrograph5)
	(have_image Phenomenon18 infrared7)
	(have_image Phenomenon19 infrared0)
	(have_image Phenomenon19 infrared3)
	(have_image Phenomenon19 image4)
))

)
