(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4)
	(:init (ontable block1) (on block2 block1) (clear block2) (on block3 block4) (clear block3) (ontable block4) (handempty))
	(:goal (and (on block1 block2) (ontable block2) (on block3 block4) (clear block3) (on block4 block1))))