(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4)
	(:init (on block1 block3) (clear block1) (on block2 block4) (clear block2) (ontable block3) (ontable block4) (handempty))
	(:goal (and (on block1 block4) (clear block1) (on block2 block3) (clear block2) (ontable block3) (ontable block4))))