(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (ontable block1) (on block2 block3) (clear block2) (ontable block3) (on block4 block6) (on block5 block4) (clear block5) (on block6 block1) (handempty))
	(:goal (and (on block1 block2) (ontable block2) (on block3 block6) (clear block3) (ontable block4) (on block5 block1) (clear block5) (on block6 block4))))