(define (problem pb7)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (ontable block1) (on block2 block4) (on block3 block2) (clear block3) (on block4 block5) (ontable block5) (on block6 block1) (clear block6) (handempty))
	(:goal (and (ontable block1) (clear block1) (on block2 block3) (ontable block3) (ontable block4) (on block5 block4) (clear block5) (on block6 block2) (clear block6))))