(define (problem pb9)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (ontable block1) (clear block1) (on block2 block6) (on block3 block5) (clear block3) (on block4 block2) (on block5 block4) (ontable block6) (handempty))
	(:goal (and (on block1 block4) (ontable block2) (ontable block3) (clear block3) (on block4 block6) (on block5 block1) (clear block5) (on block6 block2))))