(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (on block1 block6) (clear block1) (on block2 block3) (on block3 block5) (ontable block4) (on block5 block4) (on block6 block2) (handempty))
	(:goal (and (ontable block1) (clear block1) (on block2 block4) (on block3 block6) (on block4 block3) (on block5 block2) (clear block5) (ontable block6))))