(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (on block1 block2) (clear block1) (ontable block2) (ontable block3) (ontable block4) (clear block4) (on block5 block3) (clear block5) (handempty))
	(:goal (and (on block1 block5) (clear block1) (on block2 block3) (ontable block3) (on block4 block2) (on block5 block4))))