(define (problem pb0)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (ontable block1) (ontable block2) (ontable block3) (clear block3) (on block4 block1) (clear block4) (on block5 block2) (clear block5) (handempty))
	(:goal (and (ontable block1) (clear block1) (on block2 block3) (clear block2) (on block3 block5) (ontable block4) (on block5 block4))))