(define (problem pb9)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (on block1 block3) (ontable block2) (clear block2) (ontable block3) (on block4 block1) (on block5 block4) (clear block5) (handempty))
	(:goal (and (ontable block1) (on block2 block1) (on block3 block2) (clear block3) (on block4 block5) (clear block4) (ontable block5))))