(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (on block1 block2) (clear block1) (on block2 block3) (on block3 block5) (ontable block4) (on block5 block4) (handempty))
	(:goal (and (on block1 block4) (ontable block2) (on block3 block1) (clear block3) (on block4 block5) (on block5 block2))))