(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (ontable block1) (clear block1) (on block2 block4) (on block3 block2) (clear block3) (ontable block4) (ontable block5) (clear block5) (handempty))
	(:goal (and (on block1 block3) (clear block1) (ontable block2) (on block3 block4) (ontable block4) (on block5 block2) (clear block5))))