(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (on block1 block3) (clear block1) (ontable block2) (on block3 block2) (ontable block4) (on block5 block4) (clear block5) (handempty))
	(:goal (and (on block1 block4) (on block2 block5) (on block3 block2) (clear block3) (ontable block4) (on block5 block1))))