(define (problem pb2)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (ontable block1) (ontable block2) (clear block2) (ontable block3) (clear block3) (on block4 block7) (on block5 block4) (clear block5) (on block6 block1) (clear block6) (ontable block7) (handempty))
	(:goal (and (on block1 block7) (on block2 block1) (on block3 block5) (clear block3) (on block4 block2) (on block5 block4) (ontable block6) (on block7 block6))))