(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block5) (ontable block2) (on block3 block7) (clear block3) (on block4 block2) (on block5 block6) (on block6 block4) (on block7 block1) (handempty))
	(:goal (and (ontable block1) (on block2 block3) (on block3 block5) (ontable block4) (clear block4) (on block5 block7) (on block6 block2) (clear block6) (on block7 block1))))