(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (ontable block1) (clear block1) (on block2 block7) (on block3 block2) (on block4 block6) (on block5 block3) (clear block5) (ontable block6) (on block7 block4) (handempty))
	(:goal (and (on block1 block5) (clear block1) (ontable block2) (clear block2) (on block3 block6) (on block4 block3) (clear block4) (ontable block5) (ontable block6) (ontable block7) (clear block7))))