(define (problem pb0)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block2) (ontable block2) (ontable block3) (on block4 block5) (clear block4) (on block5 block1) (on block6 block3) (on block7 block6) (clear block7) (handempty))
	(:goal (and (on block1 block4) (ontable block2) (on block3 block5) (clear block3) (ontable block4) (on block5 block2) (on block6 block1) (on block7 block6) (clear block7))))