(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite3 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite6 - satellite
	instrument20 - instrument
	infrared4 - mode
	thermograph5 - mode
	image3 - mode
	spectrograph0 - mode
	image6 - mode
	image2 - mode
	thermograph1 - mode
	Star4 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	Star0 - direction
	GroundStation6 - direction
	Star3 - direction
	GroundStation5 - direction
	Planet7 - direction
	Star8 - direction
	Planet9 - direction
	Planet10 - direction
	Star11 - direction
	Star12 - direction
	Phenomenon13 - direction
)
(:init
	(supports instrument0 image6)
	(supports instrument0 thermograph5)
	(supports instrument0 thermograph1)
	(calibration_target instrument0 GroundStation6)
	(supports instrument1 infrared4)
	(supports instrument1 image3)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 image2)
	(calibration_target instrument2 GroundStation1)
	(supports instrument3 infrared4)
	(supports instrument3 image2)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 Star0)
	(supports instrument4 image3)
	(supports instrument4 infrared4)
	(calibration_target instrument4 GroundStation5)
	(supports instrument5 infrared4)
	(supports instrument5 thermograph1)
	(supports instrument5 thermograph5)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation2)
	(supports instrument6 thermograph5)
	(calibration_target instrument6 GroundStation5)
	(supports instrument7 spectrograph0)
	(supports instrument7 infrared4)
	(calibration_target instrument7 Star0)
	(calibration_target instrument7 Star3)
	(supports instrument8 thermograph1)
	(supports instrument8 infrared4)
	(supports instrument8 image3)
	(calibration_target instrument8 Star3)
	(calibration_target instrument8 GroundStation6)
	(supports instrument9 thermograph1)
	(supports instrument9 infrared4)
	(supports instrument9 image3)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 GroundStation1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument10 image6)
	(supports instrument10 thermograph5)
	(calibration_target instrument10 GroundStation1)
	(calibration_target instrument10 Star4)
	(supports instrument11 image2)
	(supports instrument11 image6)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 GroundStation6)
	(supports instrument12 thermograph5)
	(supports instrument12 image2)
	(calibration_target instrument12 GroundStation1)
	(supports instrument13 spectrograph0)
	(calibration_target instrument13 GroundStation1)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star4)
	(supports instrument14 infrared4)
	(calibration_target instrument14 Star4)
	(calibration_target instrument14 GroundStation5)
	(supports instrument15 image6)
	(supports instrument15 infrared4)
	(supports instrument15 image3)
	(calibration_target instrument15 GroundStation2)
	(calibration_target instrument15 GroundStation1)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star8)
	(supports instrument16 image3)
	(calibration_target instrument16 Star0)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument17 image6)
	(calibration_target instrument17 GroundStation6)
	(calibration_target instrument17 Star3)
	(supports instrument18 thermograph1)
	(supports instrument18 image3)
	(supports instrument18 thermograph5)
	(calibration_target instrument18 Star3)
	(supports instrument19 thermograph1)
	(supports instrument19 spectrograph0)
	(calibration_target instrument19 GroundStation5)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet7)
	(supports instrument20 thermograph1)
	(supports instrument20 image2)
	(supports instrument20 image6)
	(calibration_target instrument20 GroundStation5)
	(on_board instrument20 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet9)
)
(:goal (and
	(pointing satellite1 Star8)
	(pointing satellite3 Planet10)
	(pointing satellite4 Star0)
	(pointing satellite5 Star0)
	(pointing satellite6 Star12)
	(have_image Planet7 infrared4)
	(have_image Planet7 image6)
	(have_image Star8 infrared4)
	(have_image Planet9 image2)
	(have_image Planet10 spectrograph0)
	(have_image Planet10 image3)
	(have_image Star11 image3)
	(have_image Star12 spectrograph0)
	(have_image Star12 image3)
	(have_image Phenomenon13 infrared4)
	(have_image Phenomenon13 image3)
))

)
