(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite4 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite5 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite6 - satellite
	instrument23 - instrument
	thermograph0 - mode
	thermograph4 - mode
	image6 - mode
	infrared2 - mode
	image3 - mode
	infrared5 - mode
	spectrograph1 - mode
	GroundStation2 - direction
	Star0 - direction
	Star4 - direction
	Star1 - direction
	GroundStation5 - direction
	Star3 - direction
	Star6 - direction
	Phenomenon7 - direction
	Star8 - direction
	Phenomenon9 - direction
	Star10 - direction
	Planet11 - direction
	Star12 - direction
	Phenomenon13 - direction
)
(:init
	(supports instrument0 infrared2)
	(calibration_target instrument0 Star4)
	(supports instrument1 image3)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 GroundStation5)
	(supports instrument2 image3)
	(supports instrument2 thermograph4)
	(supports instrument2 image6)
	(calibration_target instrument2 Star1)
	(supports instrument3 thermograph4)
	(supports instrument3 infrared2)
	(calibration_target instrument3 Star4)
	(calibration_target instrument3 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star6)
	(supports instrument4 image6)
	(supports instrument4 spectrograph1)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 Star1)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation2)
	(supports instrument6 image6)
	(supports instrument6 image3)
	(calibration_target instrument6 Star0)
	(supports instrument7 thermograph4)
	(supports instrument7 thermograph0)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 Star1)
	(supports instrument8 thermograph4)
	(supports instrument8 infrared5)
	(supports instrument8 image3)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 Star4)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon13)
	(supports instrument9 image3)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 Star1)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon9)
	(supports instrument10 spectrograph1)
	(supports instrument10 infrared5)
	(calibration_target instrument10 Star4)
	(calibration_target instrument10 Star6)
	(supports instrument11 infrared2)
	(calibration_target instrument11 Star1)
	(supports instrument12 image6)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star1)
	(supports instrument13 thermograph0)
	(supports instrument13 infrared5)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 Star4)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 Star1)
	(calibration_target instrument14 GroundStation2)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star12)
	(supports instrument15 image6)
	(calibration_target instrument15 Star4)
	(calibration_target instrument15 GroundStation2)
	(supports instrument16 infrared5)
	(supports instrument16 image3)
	(supports instrument16 infrared2)
	(calibration_target instrument16 Star4)
	(calibration_target instrument16 GroundStation2)
	(supports instrument17 image6)
	(calibration_target instrument17 Star1)
	(supports instrument18 image6)
	(supports instrument18 image3)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 GroundStation2)
	(supports instrument19 image6)
	(supports instrument19 image3)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 Star1)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star6)
	(supports instrument20 spectrograph1)
	(calibration_target instrument20 Star4)
	(calibration_target instrument20 GroundStation5)
	(supports instrument21 infrared2)
	(supports instrument21 image3)
	(supports instrument21 spectrograph1)
	(calibration_target instrument21 Star1)
	(supports instrument22 image3)
	(supports instrument22 spectrograph1)
	(calibration_target instrument22 GroundStation5)
	(calibration_target instrument22 Star6)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star8)
	(supports instrument23 spectrograph1)
	(supports instrument23 infrared5)
	(supports instrument23 image3)
	(calibration_target instrument23 Star6)
	(calibration_target instrument23 Star3)
	(on_board instrument23 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star8)
)
(:goal (and
	(pointing satellite0 Star8)
	(pointing satellite3 Star3)
	(pointing satellite4 Star8)
	(pointing satellite5 Star6)
	(pointing satellite6 Star6)
	(have_image Phenomenon9 thermograph4)
	(have_image Phenomenon9 image3)
	(have_image Star10 infrared5)
	(have_image Planet11 image3)
	(have_image Star12 thermograph0)
	(have_image Phenomenon13 thermograph4)
))

)
