(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite5 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite6 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	infrared1 - mode
	image0 - mode
	spectrograph4 - mode
	spectrograph5 - mode
	thermograph3 - mode
	thermograph2 - mode
	image6 - mode
	Star3 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	Star0 - direction
	Star6 - direction
	GroundStation4 - direction
	Star5 - direction
	Planet7 - direction
	Phenomenon8 - direction
	Phenomenon9 - direction
	Star10 - direction
	Planet11 - direction
	Star12 - direction
	Planet13 - direction
)
(:init
	(supports instrument0 thermograph3)
	(supports instrument0 thermograph2)
	(supports instrument0 image6)
	(calibration_target instrument0 Star6)
	(supports instrument1 image6)
	(supports instrument1 thermograph2)
	(supports instrument1 thermograph3)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 spectrograph5)
	(supports instrument2 image0)
	(calibration_target instrument2 Star6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument3 image0)
	(calibration_target instrument3 Star5)
	(supports instrument4 image6)
	(supports instrument4 thermograph3)
	(supports instrument4 image0)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 Star6)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star12)
	(supports instrument5 image0)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 GroundStation4)
	(supports instrument6 image6)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 GroundStation2)
	(supports instrument7 thermograph2)
	(supports instrument7 image0)
	(supports instrument7 image6)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation4)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star5)
	(supports instrument9 spectrograph4)
	(calibration_target instrument9 GroundStation4)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet11)
	(supports instrument10 spectrograph5)
	(supports instrument10 image6)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 image6)
	(calibration_target instrument11 Star0)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(supports instrument12 thermograph3)
	(supports instrument12 image0)
	(calibration_target instrument12 GroundStation4)
	(calibration_target instrument12 Star6)
	(supports instrument13 thermograph3)
	(supports instrument13 spectrograph4)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation4)
	(supports instrument14 thermograph2)
	(supports instrument14 infrared1)
	(supports instrument14 spectrograph5)
	(calibration_target instrument14 Star0)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon9)
	(supports instrument15 spectrograph4)
	(supports instrument15 spectrograph5)
	(calibration_target instrument15 GroundStation2)
	(calibration_target instrument15 GroundStation1)
	(supports instrument16 infrared1)
	(supports instrument16 spectrograph5)
	(supports instrument16 image0)
	(calibration_target instrument16 GroundStation2)
	(supports instrument17 spectrograph4)
	(supports instrument17 image6)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 Star6)
	(supports instrument18 spectrograph5)
	(supports instrument18 image0)
	(calibration_target instrument18 Star5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon8)
	(supports instrument19 spectrograph4)
	(supports instrument19 infrared1)
	(calibration_target instrument19 GroundStation4)
	(supports instrument20 image0)
	(supports instrument20 thermograph3)
	(supports instrument20 spectrograph4)
	(calibration_target instrument20 Star6)
	(supports instrument21 image6)
	(supports instrument21 spectrograph5)
	(supports instrument21 spectrograph4)
	(calibration_target instrument21 GroundStation4)
	(supports instrument22 image6)
	(supports instrument22 thermograph2)
	(supports instrument22 thermograph3)
	(calibration_target instrument22 Star5)
	(on_board instrument19 satellite6)
	(on_board instrument20 satellite6)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation2)
)
(:goal (and
	(pointing satellite1 Phenomenon8)
	(pointing satellite2 GroundStation4)
	(pointing satellite4 Planet13)
	(pointing satellite5 Star10)
	(pointing satellite6 GroundStation2)
	(have_image Planet7 image0)
	(have_image Phenomenon8 image0)
	(have_image Phenomenon9 image0)
	(have_image Phenomenon9 thermograph3)
	(have_image Star10 spectrograph5)
	(have_image Planet11 image6)
	(have_image Planet11 infrared1)
	(have_image Star12 thermograph3)
	(have_image Planet13 spectrograph5)
))

)
