(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	instrument16 - instrument
	satellite4 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite5 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite6 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	spectrograph6 - mode
	spectrograph1 - mode
	thermograph5 - mode
	spectrograph2 - mode
	infrared4 - mode
	image0 - mode
	infrared3 - mode
	Star5 - direction
	Star4 - direction
	Star3 - direction
	GroundStation0 - direction
	GroundStation2 - direction
	GroundStation6 - direction
	Star1 - direction
	Star7 - direction
	Phenomenon8 - direction
	Phenomenon9 - direction
	Star10 - direction
	Planet11 - direction
	Planet12 - direction
	Phenomenon13 - direction
)
(:init
	(supports instrument0 thermograph5)
	(supports instrument0 infrared4)
	(calibration_target instrument0 Star4)
	(supports instrument1 image0)
	(supports instrument1 spectrograph2)
	(supports instrument1 spectrograph6)
	(calibration_target instrument1 GroundStation2)
	(supports instrument2 spectrograph1)
	(supports instrument2 spectrograph6)
	(calibration_target instrument2 GroundStation6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(supports instrument3 thermograph5)
	(supports instrument3 infrared4)
	(supports instrument3 image0)
	(calibration_target instrument3 Star4)
	(calibration_target instrument3 GroundStation6)
	(supports instrument4 thermograph5)
	(supports instrument4 image0)
	(calibration_target instrument4 GroundStation0)
	(calibration_target instrument4 Star4)
	(supports instrument5 infrared4)
	(supports instrument5 image0)
	(calibration_target instrument5 Star1)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 GroundStation6)
	(supports instrument7 spectrograph2)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 GroundStation0)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation0)
	(supports instrument8 infrared4)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 Star4)
	(supports instrument9 image0)
	(supports instrument9 spectrograph2)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 GroundStation6)
	(supports instrument10 spectrograph6)
	(supports instrument10 spectrograph1)
	(calibration_target instrument10 Star5)
	(calibration_target instrument10 Star1)
	(supports instrument11 spectrograph2)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 GroundStation2)
	(supports instrument12 spectrograph2)
	(supports instrument12 infrared4)
	(calibration_target instrument12 Star1)
	(supports instrument13 spectrograph2)
	(supports instrument13 infrared4)
	(supports instrument13 infrared3)
	(calibration_target instrument13 Star5)
	(calibration_target instrument13 Star1)
	(supports instrument14 infrared3)
	(calibration_target instrument14 GroundStation0)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation2)
	(supports instrument15 spectrograph6)
	(supports instrument15 thermograph5)
	(calibration_target instrument15 GroundStation0)
	(supports instrument16 spectrograph1)
	(supports instrument16 spectrograph2)
	(supports instrument16 infrared4)
	(calibration_target instrument16 GroundStation2)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation2)
	(supports instrument17 infrared4)
	(supports instrument17 thermograph5)
	(supports instrument17 image0)
	(calibration_target instrument17 GroundStation0)
	(calibration_target instrument17 Star1)
	(supports instrument18 spectrograph6)
	(supports instrument18 infrared4)
	(calibration_target instrument18 Star3)
	(supports instrument19 spectrograph1)
	(calibration_target instrument19 Star5)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star4)
	(supports instrument20 image0)
	(calibration_target instrument20 GroundStation0)
	(supports instrument21 infrared3)
	(calibration_target instrument21 GroundStation0)
	(supports instrument22 infrared3)
	(supports instrument22 spectrograph2)
	(supports instrument22 spectrograph1)
	(calibration_target instrument22 Star4)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star1)
	(supports instrument23 spectrograph2)
	(supports instrument23 spectrograph1)
	(supports instrument23 spectrograph6)
	(calibration_target instrument23 GroundStation6)
	(calibration_target instrument23 Star4)
	(supports instrument24 image0)
	(calibration_target instrument24 Star3)
	(supports instrument25 infrared3)
	(supports instrument25 infrared4)
	(supports instrument25 spectrograph2)
	(calibration_target instrument25 GroundStation0)
	(supports instrument26 spectrograph2)
	(supports instrument26 thermograph5)
	(calibration_target instrument26 GroundStation2)
	(supports instrument27 infrared3)
	(supports instrument27 image0)
	(supports instrument27 infrared4)
	(calibration_target instrument27 Star1)
	(calibration_target instrument27 GroundStation6)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(on_board instrument27 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star10)
)
(:goal (and
	(pointing satellite4 Phenomenon9)
	(have_image Star7 spectrograph2)
	(have_image Phenomenon8 image0)
	(have_image Phenomenon8 infrared3)
	(have_image Phenomenon9 thermograph5)
	(have_image Phenomenon9 image0)
	(have_image Star10 thermograph5)
	(have_image Star10 spectrograph2)
	(have_image Planet11 spectrograph1)
	(have_image Planet11 spectrograph6)
	(have_image Planet12 spectrograph1)
	(have_image Phenomenon13 infrared4)
	(have_image Phenomenon13 spectrograph1)
))

)
