(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite3 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite5 - satellite
	instrument18 - instrument
	instrument19 - instrument
	satellite6 - satellite
	instrument20 - instrument
	thermograph1 - mode
	thermograph6 - mode
	infrared5 - mode
	infrared3 - mode
	image0 - mode
	spectrograph2 - mode
	image4 - mode
	GroundStation1 - direction
	GroundStation4 - direction
	Star6 - direction
	Star2 - direction
	GroundStation0 - direction
	GroundStation5 - direction
	GroundStation3 - direction
	Phenomenon7 - direction
	Planet8 - direction
	Phenomenon9 - direction
	Phenomenon10 - direction
	Star11 - direction
	Phenomenon12 - direction
	Phenomenon13 - direction
)
(:init
	(supports instrument0 image0)
	(supports instrument0 infrared3)
	(supports instrument0 image4)
	(calibration_target instrument0 GroundStation3)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 infrared5)
	(supports instrument1 image0)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 image4)
	(calibration_target instrument2 GroundStation5)
	(calibration_target instrument2 GroundStation4)
	(supports instrument3 image0)
	(supports instrument3 infrared3)
	(supports instrument3 infrared5)
	(calibration_target instrument3 GroundStation0)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 thermograph1)
	(supports instrument4 infrared5)
	(calibration_target instrument4 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation5)
	(supports instrument5 infrared5)
	(supports instrument5 spectrograph2)
	(supports instrument5 image4)
	(calibration_target instrument5 GroundStation1)
	(calibration_target instrument5 GroundStation4)
	(supports instrument6 image4)
	(supports instrument6 image0)
	(calibration_target instrument6 Star6)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon12)
	(supports instrument7 thermograph6)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 GroundStation0)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 GroundStation0)
	(calibration_target instrument8 GroundStation1)
	(supports instrument9 image4)
	(supports instrument9 thermograph6)
	(calibration_target instrument9 Star6)
	(supports instrument10 infrared3)
	(supports instrument10 thermograph1)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 Star6)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon10)
	(supports instrument12 thermograph1)
	(calibration_target instrument12 GroundStation3)
	(supports instrument13 infrared5)
	(calibration_target instrument13 Star6)
	(calibration_target instrument13 GroundStation0)
	(supports instrument14 thermograph1)
	(supports instrument14 spectrograph2)
	(supports instrument14 thermograph6)
	(calibration_target instrument14 GroundStation4)
	(supports instrument15 image4)
	(supports instrument15 infrared5)
	(calibration_target instrument15 GroundStation5)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon13)
	(supports instrument16 image4)
	(supports instrument16 thermograph6)
	(supports instrument16 image0)
	(calibration_target instrument16 GroundStation0)
	(supports instrument17 thermograph6)
	(supports instrument17 spectrograph2)
	(supports instrument17 image4)
	(calibration_target instrument17 Star2)
	(calibration_target instrument17 Star6)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star11)
	(supports instrument18 infrared5)
	(supports instrument18 thermograph6)
	(supports instrument18 image4)
	(calibration_target instrument18 GroundStation0)
	(supports instrument19 image0)
	(supports instrument19 infrared3)
	(calibration_target instrument19 GroundStation5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet8)
	(supports instrument20 image4)
	(supports instrument20 spectrograph2)
	(calibration_target instrument20 GroundStation3)
	(on_board instrument20 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet8)
)
(:goal (and
	(pointing satellite3 Star6)
	(have_image Phenomenon7 spectrograph2)
	(have_image Planet8 image0)
	(have_image Phenomenon9 image0)
	(have_image Phenomenon9 image4)
	(have_image Star11 infrared3)
	(have_image Phenomenon12 infrared3)
	(have_image Phenomenon13 infrared3)
	(have_image Phenomenon13 image0)
))

)
