(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite4 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite5 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite6 - satellite
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	infrared3 - mode
	spectrograph2 - mode
	spectrograph5 - mode
	image6 - mode
	thermograph4 - mode
	infrared1 - mode
	thermograph0 - mode
	GroundStation3 - direction
	Star4 - direction
	GroundStation2 - direction
	GroundStation6 - direction
	GroundStation0 - direction
	Star5 - direction
	GroundStation1 - direction
	Planet7 - direction
	Planet8 - direction
	Planet9 - direction
	Star10 - direction
	Star11 - direction
	Star12 - direction
	Phenomenon13 - direction
)
(:init
	(supports instrument0 thermograph4)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 infrared1)
	(calibration_target instrument1 GroundStation3)
	(supports instrument2 infrared3)
	(supports instrument2 image6)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 GroundStation0)
	(calibration_target instrument2 GroundStation3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet7)
	(supports instrument3 image6)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 Star4)
	(supports instrument4 infrared3)
	(supports instrument4 infrared1)
	(calibration_target instrument4 GroundStation0)
	(calibration_target instrument4 GroundStation3)
	(supports instrument5 thermograph4)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation1)
	(calibration_target instrument5 GroundStation6)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument6 image6)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 GroundStation0)
	(supports instrument7 infrared3)
	(calibration_target instrument7 GroundStation1)
	(calibration_target instrument7 Star4)
	(supports instrument8 thermograph4)
	(supports instrument8 image6)
	(supports instrument8 spectrograph2)
	(calibration_target instrument8 GroundStation3)
	(supports instrument9 thermograph4)
	(supports instrument9 infrared3)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 GroundStation0)
	(calibration_target instrument9 Star4)
	(supports instrument10 thermograph0)
	(supports instrument10 spectrograph5)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 GroundStation0)
	(calibration_target instrument11 GroundStation3)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 GroundStation0)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon13)
	(supports instrument13 spectrograph5)
	(calibration_target instrument13 GroundStation3)
	(supports instrument14 infrared3)
	(supports instrument14 spectrograph5)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 GroundStation1)
	(supports instrument15 spectrograph5)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 GroundStation2)
	(supports instrument16 infrared1)
	(supports instrument16 infrared3)
	(supports instrument16 spectrograph2)
	(calibration_target instrument16 GroundStation1)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 GroundStation6)
	(supports instrument18 spectrograph2)
	(supports instrument18 infrared1)
	(calibration_target instrument18 GroundStation3)
	(calibration_target instrument18 GroundStation1)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation0)
	(supports instrument19 image6)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 thermograph0)
	(supports instrument20 spectrograph5)
	(calibration_target instrument20 GroundStation3)
	(calibration_target instrument20 Star5)
	(supports instrument21 spectrograph5)
	(calibration_target instrument21 GroundStation1)
	(calibration_target instrument21 GroundStation0)
	(supports instrument22 infrared1)
	(supports instrument22 spectrograph5)
	(supports instrument22 spectrograph2)
	(calibration_target instrument22 Star5)
	(calibration_target instrument22 GroundStation6)
	(supports instrument23 infrared1)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 GroundStation3)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation6)
	(supports instrument24 spectrograph2)
	(calibration_target instrument24 GroundStation3)
	(supports instrument25 image6)
	(supports instrument25 infrared3)
	(calibration_target instrument25 GroundStation3)
	(calibration_target instrument25 GroundStation0)
	(supports instrument26 spectrograph5)
	(supports instrument26 spectrograph2)
	(supports instrument26 thermograph0)
	(calibration_target instrument26 Star4)
	(calibration_target instrument26 GroundStation2)
	(supports instrument27 image6)
	(supports instrument27 thermograph0)
	(calibration_target instrument27 Star5)
	(calibration_target instrument27 Star4)
	(supports instrument28 infrared3)
	(supports instrument28 spectrograph2)
	(supports instrument28 image6)
	(calibration_target instrument28 Star4)
	(supports instrument29 infrared3)
	(supports instrument29 infrared1)
	(calibration_target instrument29 GroundStation0)
	(supports instrument30 thermograph0)
	(supports instrument30 spectrograph5)
	(supports instrument30 spectrograph2)
	(calibration_target instrument30 GroundStation6)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star4)
	(supports instrument31 spectrograph2)
	(calibration_target instrument31 GroundStation6)
	(calibration_target instrument31 Star5)
	(supports instrument32 image6)
	(supports instrument32 infrared1)
	(calibration_target instrument32 GroundStation0)
	(calibration_target instrument32 GroundStation1)
	(supports instrument33 spectrograph5)
	(supports instrument33 infrared1)
	(calibration_target instrument33 GroundStation6)
	(calibration_target instrument33 GroundStation2)
	(supports instrument34 infrared1)
	(supports instrument34 thermograph4)
	(supports instrument34 image6)
	(calibration_target instrument34 GroundStation0)
	(calibration_target instrument34 GroundStation1)
	(supports instrument35 thermograph0)
	(calibration_target instrument35 GroundStation1)
	(calibration_target instrument35 Star5)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet8)
)
(:goal (and
	(pointing satellite4 Star11)
	(have_image Planet8 infrared1)
	(have_image Planet9 thermograph4)
	(have_image Planet9 thermograph0)
	(have_image Star10 spectrograph5)
	(have_image Star10 spectrograph2)
	(have_image Star11 spectrograph5)
	(have_image Star12 image6)
	(have_image Star12 infrared1)
	(have_image Phenomenon13 infrared1)
))

)
