(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite5 - satellite
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite7 - satellite
	instrument19 - instrument
	instrument20 - instrument
	thermograph1 - mode
	thermograph4 - mode
	spectrograph7 - mode
	thermograph0 - mode
	spectrograph2 - mode
	spectrograph6 - mode
	image3 - mode
	infrared5 - mode
	Star1 - direction
	Star3 - direction
	Star5 - direction
	GroundStation0 - direction
	GroundStation6 - direction
	Star2 - direction
	GroundStation4 - direction
	GroundStation7 - direction
	Phenomenon8 - direction
	Planet9 - direction
	Star10 - direction
	Phenomenon11 - direction
	Phenomenon12 - direction
	Planet13 - direction
	Planet14 - direction
	Phenomenon15 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(supports instrument0 thermograph0)
	(supports instrument0 spectrograph7)
	(calibration_target instrument0 Star1)
	(supports instrument1 spectrograph2)
	(supports instrument1 spectrograph6)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 Star5)
	(supports instrument2 image3)
	(supports instrument2 thermograph1)
	(calibration_target instrument2 GroundStation7)
	(calibration_target instrument2 GroundStation0)
	(supports instrument3 spectrograph7)
	(supports instrument3 image3)
	(calibration_target instrument3 Star5)
	(calibration_target instrument3 GroundStation0)
	(supports instrument4 thermograph1)
	(supports instrument4 spectrograph2)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 GroundStation0)
	(calibration_target instrument4 Star2)
	(supports instrument5 infrared5)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 GroundStation7)
	(supports instrument6 infrared5)
	(supports instrument6 thermograph1)
	(supports instrument6 spectrograph6)
	(calibration_target instrument6 Star5)
	(supports instrument7 spectrograph7)
	(supports instrument7 spectrograph2)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 GroundStation4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star5)
	(supports instrument8 spectrograph6)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 GroundStation6)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon15)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 GroundStation7)
	(calibration_target instrument9 Star1)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 Star2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star2)
	(supports instrument11 spectrograph6)
	(supports instrument11 thermograph1)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 GroundStation0)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon8)
	(supports instrument12 spectrograph6)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 GroundStation4)
	(supports instrument13 infrared5)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 Star2)
	(calibration_target instrument13 GroundStation7)
	(supports instrument14 thermograph4)
	(supports instrument14 spectrograph6)
	(calibration_target instrument14 GroundStation4)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation4)
	(supports instrument15 image3)
	(supports instrument15 thermograph4)
	(supports instrument15 spectrograph7)
	(calibration_target instrument15 Star2)
	(calibration_target instrument15 GroundStation4)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation7)
	(supports instrument16 spectrograph7)
	(calibration_target instrument16 GroundStation6)
	(calibration_target instrument16 GroundStation0)
	(supports instrument17 spectrograph7)
	(calibration_target instrument17 Star2)
	(calibration_target instrument17 GroundStation6)
	(supports instrument18 infrared5)
	(calibration_target instrument18 Star2)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon11)
	(supports instrument19 spectrograph2)
	(supports instrument19 spectrograph6)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 GroundStation4)
	(supports instrument20 infrared5)
	(supports instrument20 image3)
	(supports instrument20 spectrograph6)
	(calibration_target instrument20 GroundStation7)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet14)
)
(:goal (and
	(pointing satellite2 Star2)
	(pointing satellite6 Star2)
	(have_image Phenomenon8 spectrograph7)
	(have_image Phenomenon8 spectrograph6)
	(have_image Planet9 infrared5)
	(have_image Planet9 thermograph1)
	(have_image Star10 image3)
	(have_image Star10 spectrograph7)
	(have_image Phenomenon11 spectrograph6)
	(have_image Phenomenon12 spectrograph6)
	(have_image Planet13 spectrograph7)
	(have_image Planet13 infrared5)
	(have_image Phenomenon15 infrared5)
	(have_image Phenomenon15 thermograph4)
))

)
