(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite3 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite4 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite5 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite6 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	satellite7 - satellite
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	thermograph7 - mode
	infrared3 - mode
	image2 - mode
	infrared4 - mode
	thermograph0 - mode
	thermograph1 - mode
	spectrograph5 - mode
	infrared6 - mode
	Star7 - direction
	Star3 - direction
	Star0 - direction
	Star6 - direction
	Star2 - direction
	Star1 - direction
	GroundStation5 - direction
	GroundStation4 - direction
	Phenomenon8 - direction
	Star9 - direction
	Phenomenon10 - direction
	Planet11 - direction
	Phenomenon12 - direction
	Planet13 - direction
	Star14 - direction
	Planet15 - direction
)
(:init
	(supports instrument0 thermograph0)
	(supports instrument0 infrared6)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 Star2)
	(supports instrument1 thermograph1)
	(supports instrument1 thermograph7)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 Star0)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 Star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(supports instrument3 spectrograph5)
	(supports instrument3 infrared3)
	(supports instrument3 thermograph7)
	(calibration_target instrument3 Star0)
	(supports instrument4 infrared4)
	(supports instrument4 infrared3)
	(supports instrument4 thermograph7)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 GroundStation4)
	(supports instrument5 image2)
	(supports instrument5 infrared3)
	(calibration_target instrument5 Star3)
	(supports instrument6 infrared4)
	(supports instrument6 image2)
	(supports instrument6 thermograph7)
	(calibration_target instrument6 Star7)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 Star2)
	(supports instrument8 image2)
	(supports instrument8 thermograph0)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 Star7)
	(supports instrument9 infrared6)
	(supports instrument9 thermograph0)
	(supports instrument9 image2)
	(calibration_target instrument9 Star7)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star3)
	(supports instrument10 infrared6)
	(supports instrument10 thermograph1)
	(supports instrument10 spectrograph5)
	(calibration_target instrument10 GroundStation5)
	(supports instrument11 infrared6)
	(supports instrument11 thermograph7)
	(calibration_target instrument11 GroundStation5)
	(calibration_target instrument11 Star2)
	(supports instrument12 thermograph7)
	(calibration_target instrument12 Star6)
	(calibration_target instrument12 Star7)
	(supports instrument13 infrared4)
	(supports instrument13 thermograph7)
	(calibration_target instrument13 Star6)
	(supports instrument14 spectrograph5)
	(supports instrument14 infrared3)
	(calibration_target instrument14 Star3)
	(supports instrument15 infrared6)
	(supports instrument15 infrared3)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 Star7)
	(supports instrument16 infrared3)
	(supports instrument16 thermograph0)
	(supports instrument16 thermograph7)
	(calibration_target instrument16 Star0)
	(calibration_target instrument16 Star6)
	(supports instrument17 infrared4)
	(supports instrument17 thermograph1)
	(calibration_target instrument17 Star1)
	(calibration_target instrument17 Star2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star2)
	(supports instrument18 thermograph1)
	(supports instrument18 thermograph0)
	(supports instrument18 thermograph7)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 Star1)
	(supports instrument19 thermograph7)
	(calibration_target instrument19 GroundStation5)
	(supports instrument20 thermograph7)
	(calibration_target instrument20 Star2)
	(supports instrument21 thermograph0)
	(supports instrument21 infrared6)
	(supports instrument21 spectrograph5)
	(calibration_target instrument21 Star3)
	(supports instrument22 infrared4)
	(supports instrument22 thermograph7)
	(calibration_target instrument22 GroundStation4)
	(supports instrument23 infrared6)
	(calibration_target instrument23 Star3)
	(calibration_target instrument23 Star1)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet15)
	(supports instrument24 thermograph1)
	(supports instrument24 infrared6)
	(supports instrument24 image2)
	(calibration_target instrument24 GroundStation4)
	(calibration_target instrument24 GroundStation5)
	(supports instrument25 thermograph7)
	(supports instrument25 infrared3)
	(supports instrument25 spectrograph5)
	(calibration_target instrument25 Star1)
	(calibration_target instrument25 Star7)
	(supports instrument26 thermograph0)
	(supports instrument26 thermograph1)
	(supports instrument26 infrared4)
	(calibration_target instrument26 GroundStation5)
	(calibration_target instrument26 Star1)
	(supports instrument27 infrared3)
	(calibration_target instrument27 Star7)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star14)
	(supports instrument28 thermograph0)
	(calibration_target instrument28 Star0)
	(supports instrument29 infrared3)
	(supports instrument29 image2)
	(calibration_target instrument29 Star1)
	(calibration_target instrument29 Star7)
	(supports instrument30 infrared4)
	(supports instrument30 thermograph0)
	(supports instrument30 image2)
	(calibration_target instrument30 Star7)
	(calibration_target instrument30 Star1)
	(supports instrument31 thermograph0)
	(supports instrument31 infrared6)
	(calibration_target instrument31 GroundStation4)
	(supports instrument32 image2)
	(supports instrument32 infrared6)
	(calibration_target instrument32 Star3)
	(calibration_target instrument32 Star2)
	(supports instrument33 infrared4)
	(supports instrument33 thermograph1)
	(supports instrument33 infrared3)
	(calibration_target instrument33 Star6)
	(supports instrument34 infrared4)
	(calibration_target instrument34 Star3)
	(calibration_target instrument34 GroundStation4)
	(supports instrument35 thermograph1)
	(supports instrument35 infrared4)
	(calibration_target instrument35 Star2)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon12)
	(supports instrument36 infrared3)
	(supports instrument36 thermograph7)
	(supports instrument36 spectrograph5)
	(calibration_target instrument36 Star3)
	(supports instrument37 infrared3)
	(supports instrument37 thermograph1)
	(supports instrument37 thermograph7)
	(calibration_target instrument37 Star6)
	(supports instrument38 image2)
	(calibration_target instrument38 Star2)
	(calibration_target instrument38 Star6)
	(supports instrument39 infrared6)
	(calibration_target instrument39 Star7)
	(calibration_target instrument39 Star0)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation5)
	(supports instrument40 image2)
	(supports instrument40 infrared4)
	(supports instrument40 thermograph1)
	(calibration_target instrument40 Star0)
	(calibration_target instrument40 Star3)
	(supports instrument41 thermograph0)
	(supports instrument41 thermograph1)
	(supports instrument41 infrared4)
	(calibration_target instrument41 Star2)
	(calibration_target instrument41 Star1)
	(supports instrument42 thermograph0)
	(supports instrument42 spectrograph5)
	(calibration_target instrument42 GroundStation4)
	(calibration_target instrument42 Star6)
	(supports instrument43 thermograph0)
	(calibration_target instrument43 GroundStation4)
	(supports instrument44 spectrograph5)
	(supports instrument44 thermograph1)
	(calibration_target instrument44 Star1)
	(calibration_target instrument44 Star2)
	(supports instrument45 infrared6)
	(calibration_target instrument45 GroundStation4)
	(calibration_target instrument45 GroundStation5)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star14)
)
(:goal (and
	(pointing satellite0 Phenomenon8)
	(pointing satellite2 Star9)
	(pointing satellite3 GroundStation5)
	(pointing satellite4 Star9)
	(pointing satellite5 Star14)
	(have_image Phenomenon8 image2)
	(have_image Star9 infrared4)
	(have_image Star9 infrared3)
	(have_image Phenomenon10 infrared6)
	(have_image Planet11 infrared4)
	(have_image Planet11 thermograph0)
	(have_image Phenomenon12 infrared3)
	(have_image Phenomenon12 thermograph0)
	(have_image Planet13 thermograph1)
	(have_image Planet13 thermograph0)
	(have_image Star14 thermograph0)
	(have_image Star14 image2)
	(have_image Planet15 image2)
	(have_image Planet15 thermograph0)
))

)
