(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	satellite5 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite6 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite7 - satellite
	instrument27 - instrument
	thermograph2 - mode
	image0 - mode
	thermograph7 - mode
	infrared4 - mode
	infrared5 - mode
	infrared1 - mode
	image3 - mode
	spectrograph6 - mode
	GroundStation3 - direction
	GroundStation4 - direction
	Star0 - direction
	GroundStation6 - direction
	GroundStation7 - direction
	Star1 - direction
	GroundStation2 - direction
	GroundStation5 - direction
	Phenomenon8 - direction
	Star9 - direction
	Planet10 - direction
	Planet11 - direction
	Planet12 - direction
	Planet13 - direction
	Star14 - direction
	Planet15 - direction
)
(:init
	(supports instrument0 image3)
	(calibration_target instrument0 GroundStation6)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star1)
	(supports instrument1 infrared1)
	(supports instrument1 thermograph2)
	(supports instrument1 infrared4)
	(calibration_target instrument1 GroundStation3)
	(supports instrument2 infrared1)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 GroundStation7)
	(supports instrument3 infrared5)
	(supports instrument3 image3)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 GroundStation3)
	(supports instrument4 image0)
	(supports instrument4 thermograph7)
	(calibration_target instrument4 Star1)
	(supports instrument5 infrared1)
	(calibration_target instrument5 Star1)
	(calibration_target instrument5 GroundStation7)
	(supports instrument6 infrared5)
	(supports instrument6 image0)
	(calibration_target instrument6 GroundStation3)
	(calibration_target instrument6 GroundStation6)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star14)
	(supports instrument7 spectrograph6)
	(supports instrument7 thermograph2)
	(supports instrument7 image3)
	(calibration_target instrument7 GroundStation5)
	(supports instrument8 thermograph7)
	(supports instrument8 spectrograph6)
	(calibration_target instrument8 GroundStation5)
	(calibration_target instrument8 GroundStation3)
	(supports instrument9 thermograph7)
	(calibration_target instrument9 GroundStation5)
	(calibration_target instrument9 Star1)
	(supports instrument10 image3)
	(calibration_target instrument10 GroundStation5)
	(supports instrument11 infrared4)
	(supports instrument11 image0)
	(supports instrument11 thermograph2)
	(calibration_target instrument11 Star0)
	(calibration_target instrument11 GroundStation3)
	(supports instrument12 infrared4)
	(supports instrument12 infrared5)
	(supports instrument12 infrared1)
	(calibration_target instrument12 GroundStation4)
	(calibration_target instrument12 Star0)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet12)
	(supports instrument13 image0)
	(supports instrument13 infrared1)
	(calibration_target instrument13 Star1)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
	(supports instrument14 infrared5)
	(supports instrument14 image0)
	(calibration_target instrument14 Star0)
	(on_board instrument14 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation5)
	(supports instrument15 infrared5)
	(calibration_target instrument15 GroundStation6)
	(calibration_target instrument15 GroundStation2)
	(supports instrument16 infrared4)
	(supports instrument16 thermograph7)
	(supports instrument16 infrared5)
	(calibration_target instrument16 Star0)
	(calibration_target instrument16 GroundStation5)
	(supports instrument17 thermograph2)
	(calibration_target instrument17 GroundStation2)
	(calibration_target instrument17 GroundStation3)
	(supports instrument18 infrared5)
	(calibration_target instrument18 GroundStation4)
	(supports instrument19 image3)
	(supports instrument19 image0)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 Star1)
	(supports instrument20 thermograph7)
	(calibration_target instrument20 GroundStation4)
	(calibration_target instrument20 Star1)
	(supports instrument21 image3)
	(supports instrument21 thermograph7)
	(calibration_target instrument21 Star1)
	(calibration_target instrument21 GroundStation4)
	(supports instrument22 infrared4)
	(supports instrument22 thermograph7)
	(calibration_target instrument22 Star0)
	(calibration_target instrument22 GroundStation6)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star0)
	(supports instrument23 spectrograph6)
	(calibration_target instrument23 GroundStation7)
	(calibration_target instrument23 GroundStation6)
	(supports instrument24 infrared5)
	(supports instrument24 infrared4)
	(calibration_target instrument24 GroundStation7)
	(supports instrument25 infrared1)
	(calibration_target instrument25 Star1)
	(supports instrument26 image3)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 GroundStation5)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet12)
	(supports instrument27 spectrograph6)
	(calibration_target instrument27 GroundStation5)
	(on_board instrument27 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star9)
)
(:goal (and
	(pointing satellite2 Planet12)
	(pointing satellite4 GroundStation3)
	(pointing satellite6 Star9)
	(pointing satellite7 GroundStation5)
	(have_image Phenomenon8 infrared4)
	(have_image Phenomenon8 image3)
	(have_image Star9 image3)
	(have_image Star9 image0)
	(have_image Planet10 infrared4)
	(have_image Planet11 infrared4)
	(have_image Planet12 spectrograph6)
	(have_image Planet13 image0)
	(have_image Planet13 infrared4)
	(have_image Star14 thermograph2)
	(have_image Planet15 image0)
	(have_image Planet15 spectrograph6)
))

)
