(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite3 - satellite
	instrument18 - instrument
	instrument19 - instrument
	satellite4 - satellite
	instrument20 - instrument
	satellite5 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite6 - satellite
	instrument25 - instrument
	satellite7 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	thermograph4 - mode
	spectrograph7 - mode
	spectrograph1 - mode
	infrared3 - mode
	spectrograph6 - mode
	spectrograph5 - mode
	image0 - mode
	image2 - mode
	GroundStation4 - direction
	GroundStation5 - direction
	Star3 - direction
	Star6 - direction
	GroundStation2 - direction
	GroundStation7 - direction
	GroundStation1 - direction
	GroundStation0 - direction
	Planet8 - direction
	Phenomenon9 - direction
	Planet10 - direction
	Planet11 - direction
	Planet12 - direction
	Star13 - direction
	Star14 - direction
	Phenomenon15 - direction
)
(:init
	(supports instrument0 spectrograph7)
	(calibration_target instrument0 Star6)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 thermograph4)
	(supports instrument1 image2)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 GroundStation0)
	(supports instrument2 spectrograph7)
	(supports instrument2 infrared3)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 GroundStation1)
	(calibration_target instrument2 Star6)
	(supports instrument3 spectrograph7)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star6)
	(supports instrument4 spectrograph5)
	(supports instrument4 image0)
	(calibration_target instrument4 Star3)
	(supports instrument5 spectrograph1)
	(supports instrument5 infrared3)
	(supports instrument5 image0)
	(calibration_target instrument5 GroundStation7)
	(supports instrument6 spectrograph6)
	(supports instrument6 spectrograph5)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 GroundStation0)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star3)
	(supports instrument8 spectrograph5)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 GroundStation5)
	(supports instrument9 image2)
	(supports instrument9 spectrograph6)
	(calibration_target instrument9 GroundStation0)
	(calibration_target instrument9 GroundStation7)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star6)
	(supports instrument10 spectrograph5)
	(supports instrument10 spectrograph1)
	(calibration_target instrument10 Star6)
	(calibration_target instrument10 GroundStation7)
	(supports instrument11 image0)
	(supports instrument11 spectrograph6)
	(calibration_target instrument11 Star3)
	(supports instrument12 spectrograph5)
	(supports instrument12 image0)
	(supports instrument12 spectrograph7)
	(calibration_target instrument12 Star3)
	(supports instrument13 spectrograph5)
	(supports instrument13 spectrograph6)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 Star3)
	(supports instrument14 spectrograph7)
	(supports instrument14 image0)
	(calibration_target instrument14 GroundStation1)
	(supports instrument15 image2)
	(supports instrument15 spectrograph5)
	(supports instrument15 spectrograph7)
	(calibration_target instrument15 GroundStation5)
	(calibration_target instrument15 GroundStation2)
	(supports instrument16 infrared3)
	(supports instrument16 spectrograph7)
	(calibration_target instrument16 GroundStation4)
	(supports instrument17 spectrograph1)
	(calibration_target instrument17 GroundStation4)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 GroundStation4)
	(supports instrument19 spectrograph7)
	(supports instrument19 spectrograph1)
	(calibration_target instrument19 GroundStation5)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet8)
	(supports instrument20 image2)
	(supports instrument20 spectrograph6)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 GroundStation0)
	(on_board instrument20 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet10)
	(supports instrument21 image0)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 GroundStation5)
	(supports instrument22 spectrograph7)
	(supports instrument22 image0)
	(calibration_target instrument22 Star3)
	(supports instrument23 image0)
	(supports instrument23 spectrograph6)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 image0)
	(supports instrument24 spectrograph1)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 Star3)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation7)
	(supports instrument25 infrared3)
	(supports instrument25 spectrograph1)
	(supports instrument25 image0)
	(calibration_target instrument25 Star6)
	(calibration_target instrument25 GroundStation2)
	(on_board instrument25 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon9)
	(supports instrument26 image2)
	(supports instrument26 infrared3)
	(calibration_target instrument26 GroundStation1)
	(supports instrument27 image2)
	(calibration_target instrument27 GroundStation0)
	(calibration_target instrument27 GroundStation2)
	(supports instrument28 spectrograph1)
	(supports instrument28 infrared3)
	(supports instrument28 image2)
	(calibration_target instrument28 GroundStation1)
	(supports instrument29 image2)
	(supports instrument29 spectrograph6)
	(supports instrument29 infrared3)
	(calibration_target instrument29 GroundStation7)
	(calibration_target instrument29 GroundStation2)
	(supports instrument30 image2)
	(supports instrument30 image0)
	(supports instrument30 spectrograph5)
	(calibration_target instrument30 GroundStation0)
	(calibration_target instrument30 GroundStation1)
	(on_board instrument26 satellite7)
	(on_board instrument27 satellite7)
	(on_board instrument28 satellite7)
	(on_board instrument29 satellite7)
	(on_board instrument30 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation5)
)
(:goal (and
	(pointing satellite0 Star14)
	(pointing satellite2 GroundStation5)
	(pointing satellite5 GroundStation1)
	(have_image Planet8 image2)
	(have_image Planet8 thermograph4)
	(have_image Phenomenon9 spectrograph7)
	(have_image Phenomenon9 infrared3)
	(have_image Planet10 spectrograph6)
	(have_image Planet10 infrared3)
	(have_image Planet11 image2)
	(have_image Planet11 thermograph4)
	(have_image Planet12 image2)
	(have_image Star13 thermograph4)
	(have_image Star14 image0)
))

)
