(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	satellite4 - satellite
	instrument15 - instrument
	satellite5 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite6 - satellite
	instrument18 - instrument
	instrument19 - instrument
	satellite7 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	spectrograph3 - mode
	thermograph0 - mode
	image6 - mode
	image4 - mode
	infrared2 - mode
	spectrograph7 - mode
	thermograph5 - mode
	infrared1 - mode
	GroundStation0 - direction
	GroundStation1 - direction
	Star2 - direction
	Star5 - direction
	Star6 - direction
	Star4 - direction
	GroundStation3 - direction
	Star7 - direction
	Planet8 - direction
	Planet9 - direction
	Star10 - direction
	Phenomenon11 - direction
	Star12 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
	Star15 - direction
)
(:init
	(supports instrument0 thermograph5)
	(supports instrument0 spectrograph3)
	(calibration_target instrument0 GroundStation3)
	(calibration_target instrument0 Star4)
	(supports instrument1 thermograph5)
	(calibration_target instrument1 Star6)
	(supports instrument2 spectrograph3)
	(supports instrument2 image6)
	(supports instrument2 infrared2)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 GroundStation0)
	(supports instrument3 image6)
	(supports instrument3 thermograph5)
	(calibration_target instrument3 Star6)
	(supports instrument4 image4)
	(calibration_target instrument4 GroundStation0)
	(calibration_target instrument4 Star2)
	(supports instrument5 spectrograph7)
	(supports instrument5 infrared2)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 Star5)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star4)
	(calibration_target instrument6 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation3)
	(supports instrument7 spectrograph7)
	(supports instrument7 image6)
	(supports instrument7 spectrograph3)
	(calibration_target instrument7 Star6)
	(supports instrument8 image6)
	(calibration_target instrument8 GroundStation0)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet9)
	(supports instrument9 image6)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 GroundStation1)
	(calibration_target instrument9 Star4)
	(supports instrument10 image6)
	(supports instrument10 infrared2)
	(supports instrument10 thermograph5)
	(calibration_target instrument10 GroundStation3)
	(calibration_target instrument10 GroundStation0)
	(supports instrument11 thermograph0)
	(calibration_target instrument11 GroundStation0)
	(calibration_target instrument11 Star4)
	(supports instrument12 infrared2)
	(supports instrument12 spectrograph7)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 Star2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon13)
	(supports instrument13 infrared2)
	(supports instrument13 image4)
	(calibration_target instrument13 Star5)
	(calibration_target instrument13 Star7)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 Star7)
	(calibration_target instrument14 GroundStation1)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star10)
	(supports instrument15 image6)
	(supports instrument15 image4)
	(calibration_target instrument15 GroundStation1)
	(calibration_target instrument15 Star7)
	(on_board instrument15 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star5)
	(supports instrument16 thermograph0)
	(supports instrument16 thermograph5)
	(supports instrument16 spectrograph3)
	(calibration_target instrument16 GroundStation3)
	(calibration_target instrument16 Star2)
	(supports instrument17 thermograph0)
	(supports instrument17 thermograph5)
	(calibration_target instrument17 Star4)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star7)
	(supports instrument18 spectrograph7)
	(supports instrument18 infrared2)
	(supports instrument18 thermograph5)
	(calibration_target instrument18 Star7)
	(calibration_target instrument18 Star5)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 GroundStation3)
	(calibration_target instrument19 Star6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon14)
	(supports instrument20 infrared2)
	(supports instrument20 image4)
	(supports instrument20 image6)
	(calibration_target instrument20 Star6)
	(calibration_target instrument20 Star4)
	(supports instrument21 thermograph5)
	(supports instrument21 spectrograph7)
	(calibration_target instrument21 GroundStation3)
	(calibration_target instrument21 Star4)
	(supports instrument22 infrared1)
	(calibration_target instrument22 Star7)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation3)
)
(:goal (and
	(pointing satellite0 GroundStation1)
	(pointing satellite1 GroundStation3)
	(pointing satellite3 Star6)
	(pointing satellite4 GroundStation1)
	(have_image Planet8 infrared1)
	(have_image Planet9 thermograph0)
	(have_image Planet9 spectrograph3)
	(have_image Phenomenon11 thermograph0)
	(have_image Star12 infrared2)
	(have_image Star12 spectrograph7)
	(have_image Phenomenon13 infrared1)
	(have_image Phenomenon13 image4)
	(have_image Phenomenon14 thermograph5)
	(have_image Phenomenon14 image6)
	(have_image Star15 image6)
))

)
