(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite4 - satellite
	instrument15 - instrument
	satellite5 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite6 - satellite
	instrument18 - instrument
	instrument19 - instrument
	satellite7 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	spectrograph3 - mode
	image7 - mode
	image0 - mode
	infrared4 - mode
	thermograph5 - mode
	spectrograph1 - mode
	thermograph2 - mode
	thermograph6 - mode
	GroundStation2 - direction
	GroundStation6 - direction
	GroundStation0 - direction
	GroundStation4 - direction
	GroundStation5 - direction
	Star1 - direction
	Star7 - direction
	GroundStation3 - direction
	Phenomenon8 - direction
	Star9 - direction
	Planet10 - direction
	Phenomenon11 - direction
	Star12 - direction
	Planet13 - direction
	Planet14 - direction
	Planet15 - direction
)
(:init
	(supports instrument0 image0)
	(calibration_target instrument0 GroundStation3)
	(calibration_target instrument0 GroundStation6)
	(supports instrument1 infrared4)
	(supports instrument1 thermograph5)
	(calibration_target instrument1 GroundStation2)
	(supports instrument2 thermograph2)
	(supports instrument2 spectrograph1)
	(supports instrument2 thermograph6)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 GroundStation0)
	(supports instrument3 spectrograph1)
	(supports instrument3 image0)
	(calibration_target instrument3 GroundStation0)
	(calibration_target instrument3 Star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation3)
	(supports instrument4 image0)
	(supports instrument4 spectrograph1)
	(supports instrument4 thermograph6)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 GroundStation2)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument5 image0)
	(supports instrument5 thermograph6)
	(calibration_target instrument5 GroundStation0)
	(supports instrument6 thermograph5)
	(supports instrument6 infrared4)
	(supports instrument6 spectrograph3)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 Star7)
	(supports instrument7 thermograph2)
	(calibration_target instrument7 GroundStation0)
	(calibration_target instrument7 GroundStation3)
	(supports instrument8 spectrograph3)
	(calibration_target instrument8 GroundStation6)
	(calibration_target instrument8 GroundStation0)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon8)
	(supports instrument9 image7)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 GroundStation5)
	(supports instrument10 thermograph6)
	(supports instrument10 image7)
	(calibration_target instrument10 GroundStation2)
	(calibration_target instrument10 GroundStation6)
	(supports instrument11 thermograph2)
	(supports instrument11 thermograph5)
	(calibration_target instrument11 GroundStation3)
	(supports instrument12 image0)
	(calibration_target instrument12 GroundStation4)
	(supports instrument13 spectrograph1)
	(supports instrument13 image0)
	(supports instrument13 image7)
	(calibration_target instrument13 GroundStation4)
	(calibration_target instrument13 Star7)
	(supports instrument14 thermograph5)
	(supports instrument14 thermograph2)
	(supports instrument14 thermograph6)
	(calibration_target instrument14 GroundStation2)
	(calibration_target instrument14 GroundStation4)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star7)
	(supports instrument15 thermograph5)
	(supports instrument15 image7)
	(calibration_target instrument15 Star1)
	(calibration_target instrument15 GroundStation2)
	(on_board instrument15 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation6)
	(supports instrument16 image7)
	(supports instrument16 thermograph2)
	(calibration_target instrument16 GroundStation6)
	(calibration_target instrument16 GroundStation3)
	(supports instrument17 image7)
	(supports instrument17 thermograph5)
	(calibration_target instrument17 Star1)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon8)
	(supports instrument18 thermograph2)
	(calibration_target instrument18 GroundStation6)
	(supports instrument19 thermograph5)
	(calibration_target instrument19 Star7)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation6)
	(supports instrument20 spectrograph1)
	(supports instrument20 thermograph2)
	(supports instrument20 image0)
	(calibration_target instrument20 GroundStation3)
	(calibration_target instrument20 GroundStation5)
	(supports instrument21 spectrograph1)
	(supports instrument21 image7)
	(calibration_target instrument21 GroundStation0)
	(calibration_target instrument21 GroundStation6)
	(supports instrument22 image7)
	(supports instrument22 thermograph6)
	(calibration_target instrument22 GroundStation4)
	(supports instrument23 thermograph2)
	(supports instrument23 image7)
	(supports instrument23 thermograph5)
	(calibration_target instrument23 Star7)
	(calibration_target instrument23 GroundStation5)
	(supports instrument24 thermograph6)
	(supports instrument24 spectrograph1)
	(supports instrument24 image0)
	(calibration_target instrument24 GroundStation5)
	(supports instrument25 thermograph5)
	(supports instrument25 infrared4)
	(calibration_target instrument25 Star7)
	(calibration_target instrument25 Star1)
	(supports instrument26 thermograph5)
	(supports instrument26 thermograph6)
	(calibration_target instrument26 Star7)
	(supports instrument27 thermograph6)
	(supports instrument27 thermograph2)
	(supports instrument27 spectrograph1)
	(calibration_target instrument27 GroundStation3)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(on_board instrument23 satellite7)
	(on_board instrument24 satellite7)
	(on_board instrument25 satellite7)
	(on_board instrument26 satellite7)
	(on_board instrument27 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon8)
)
(:goal (and
	(pointing satellite2 Star7)
	(pointing satellite3 Planet15)
	(pointing satellite6 GroundStation5)
	(have_image Phenomenon8 image7)
	(have_image Phenomenon8 thermograph6)
	(have_image Star9 image7)
	(have_image Planet10 thermograph6)
	(have_image Planet10 infrared4)
	(have_image Phenomenon11 thermograph2)
	(have_image Phenomenon11 thermograph6)
	(have_image Star12 thermograph6)
	(have_image Star12 image7)
	(have_image Planet13 thermograph2)
	(have_image Planet14 thermograph5)
	(have_image Planet14 spectrograph3)
	(have_image Planet15 infrared4)
))

)
