(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite3 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite4 - satellite
	instrument18 - instrument
	satellite5 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite6 - satellite
	instrument22 - instrument
	instrument23 - instrument
	satellite7 - satellite
	instrument24 - instrument
	image7 - mode
	spectrograph1 - mode
	spectrograph0 - mode
	image6 - mode
	spectrograph4 - mode
	thermograph2 - mode
	infrared5 - mode
	infrared3 - mode
	Star4 - direction
	Star7 - direction
	GroundStation3 - direction
	GroundStation1 - direction
	Star0 - direction
	Star6 - direction
	Star5 - direction
	GroundStation2 - direction
	Star8 - direction
	Star9 - direction
	Planet10 - direction
	Star11 - direction
	Planet12 - direction
	Star13 - direction
	Phenomenon14 - direction
	Planet15 - direction
)
(:init
	(supports instrument0 infrared5)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 GroundStation3)
	(supports instrument1 infrared3)
	(supports instrument1 image7)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 GroundStation2)
	(supports instrument2 thermograph2)
	(supports instrument2 spectrograph0)
	(supports instrument2 image7)
	(calibration_target instrument2 GroundStation1)
	(calibration_target instrument2 Star6)
	(supports instrument3 spectrograph4)
	(supports instrument3 image6)
	(supports instrument3 image7)
	(calibration_target instrument3 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument4 image6)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 Star7)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 GroundStation2)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star6)
	(calibration_target instrument6 Star0)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 GroundStation1)
	(supports instrument8 infrared3)
	(calibration_target instrument8 Star0)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet15)
	(supports instrument9 spectrograph0)
	(supports instrument9 infrared5)
	(supports instrument9 image7)
	(calibration_target instrument9 Star0)
	(supports instrument10 image6)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 spectrograph1)
	(supports instrument11 image7)
	(supports instrument11 thermograph2)
	(calibration_target instrument11 Star4)
	(supports instrument12 infrared3)
	(supports instrument12 thermograph2)
	(calibration_target instrument12 Star0)
	(supports instrument13 spectrograph1)
	(supports instrument13 image6)
	(supports instrument13 infrared5)
	(calibration_target instrument13 Star7)
	(calibration_target instrument13 Star0)
	(supports instrument14 thermograph2)
	(calibration_target instrument14 Star4)
	(supports instrument15 spectrograph1)
	(supports instrument15 infrared3)
	(calibration_target instrument15 GroundStation1)
	(calibration_target instrument15 Star4)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star6)
	(supports instrument16 infrared3)
	(calibration_target instrument16 Star4)
	(supports instrument17 thermograph2)
	(supports instrument17 infrared5)
	(calibration_target instrument17 GroundStation3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument18 image6)
	(supports instrument18 infrared3)
	(supports instrument18 spectrograph1)
	(calibration_target instrument18 Star7)
	(calibration_target instrument18 Star5)
	(on_board instrument18 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument19 spectrograph4)
	(supports instrument19 spectrograph1)
	(supports instrument19 infrared5)
	(calibration_target instrument19 Star7)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 image6)
	(supports instrument20 infrared3)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 GroundStation3)
	(supports instrument21 thermograph2)
	(supports instrument21 spectrograph4)
	(calibration_target instrument21 GroundStation1)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation3)
	(supports instrument22 infrared5)
	(calibration_target instrument22 Star0)
	(supports instrument23 thermograph2)
	(supports instrument23 spectrograph4)
	(calibration_target instrument23 Star6)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet12)
	(supports instrument24 infrared3)
	(supports instrument24 infrared5)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 Star5)
	(on_board instrument24 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
)
(:goal (and
	(pointing satellite1 Planet10)
	(pointing satellite4 GroundStation2)
	(have_image Star8 thermograph2)
	(have_image Star8 spectrograph0)
	(have_image Star9 image6)
	(have_image Planet10 spectrograph4)
	(have_image Planet10 image7)
	(have_image Star13 infrared5)
	(have_image Star13 image7)
	(have_image Phenomenon14 infrared5)
	(have_image Phenomenon14 thermograph2)
	(have_image Planet15 infrared3)
	(have_image Planet15 spectrograph1)
))

)
