(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (on block1 block9) (clear block1) (on block2 block8) (on block3 block5) (clear block3) (on block4 block7) (ontable block5) (on block6 block2) (ontable block7) (on block8 block4) (on block9 block6) (handempty))
	(:goal (and (ontable block1) (on block2 block1) (on block3 block2) (ontable block4) (clear block4) (ontable block5) (on block6 block8) (on block7 block6) (clear block7) (on block8 block3) (on block9 block5) (clear block9))))