(define (problem pb5)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (on block1 block7) (ontable block2) (on block3 block2) (on block4 block1) (clear block4) (ontable block5) (ontable block6) (clear block6) (on block7 block3) (ontable block8) (clear block8) (on block9 block5) (clear block9) (handempty))
	(:goal (and (ontable block1) (on block2 block8) (on block3 block5) (on block4 block2) (clear block4) (ontable block5) (on block6 block1) (clear block6) (on block7 block3) (on block8 block7) (ontable block9) (clear block9))))