(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite2 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite3 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite4 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite5 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	satellite6 - satellite
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite7 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	satellite8 - satellite
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	thermograph0 - mode
	spectrograph4 - mode
	image7 - mode
	image6 - mode
	spectrograph2 - mode
	infrared3 - mode
	thermograph5 - mode
	spectrograph1 - mode
	infrared8 - mode
	Star1 - direction
	GroundStation4 - direction
	GroundStation3 - direction
	Star7 - direction
	Star0 - direction
	Star5 - direction
	GroundStation2 - direction
	GroundStation6 - direction
	GroundStation8 - direction
	Phenomenon9 - direction
	Planet10 - direction
	Phenomenon11 - direction
	Planet12 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
	Phenomenon15 - direction
	Phenomenon16 - direction
	Star17 - direction
)
(:init
	(supports instrument0 infrared3)
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 Star0)
	(supports instrument1 thermograph5)
	(calibration_target instrument1 GroundStation2)
	(calibration_target instrument1 GroundStation4)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 Star0)
	(supports instrument3 thermograph5)
	(supports instrument3 image7)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 GroundStation4)
	(supports instrument4 spectrograph2)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 GroundStation8)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 Star5)
	(supports instrument5 thermograph0)
	(supports instrument5 image7)
	(calibration_target instrument5 Star1)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 Star7)
	(supports instrument6 thermograph5)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 Star1)
	(supports instrument7 infrared8)
	(supports instrument7 spectrograph4)
	(supports instrument7 spectrograph2)
	(calibration_target instrument7 GroundStation3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon16)
	(supports instrument8 image7)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 Star5)
	(supports instrument9 infrared8)
	(calibration_target instrument9 GroundStation3)
	(calibration_target instrument9 Star1)
	(supports instrument10 infrared3)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 Star7)
	(calibration_target instrument10 GroundStation3)
	(supports instrument11 infrared8)
	(supports instrument11 image6)
	(supports instrument11 spectrograph2)
	(calibration_target instrument11 GroundStation8)
	(calibration_target instrument11 GroundStation3)
	(supports instrument12 spectrograph4)
	(calibration_target instrument12 GroundStation6)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 GroundStation8)
	(supports instrument13 spectrograph4)
	(supports instrument13 infrared3)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 GroundStation6)
	(supports instrument14 thermograph5)
	(supports instrument14 image7)
	(supports instrument14 image6)
	(calibration_target instrument14 GroundStation3)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 GroundStation8)
	(supports instrument15 thermograph0)
	(supports instrument15 image7)
	(supports instrument15 infrared8)
	(calibration_target instrument15 Star1)
	(calibration_target instrument15 GroundStation4)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star1)
	(supports instrument16 spectrograph1)
	(supports instrument16 spectrograph4)
	(calibration_target instrument16 Star1)
	(calibration_target instrument16 GroundStation8)
	(calibration_target instrument16 GroundStation4)
	(supports instrument17 infrared3)
	(supports instrument17 image6)
	(calibration_target instrument17 Star5)
	(supports instrument18 infrared8)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 GroundStation3)
	(supports instrument19 thermograph0)
	(supports instrument19 thermograph5)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 GroundStation2)
	(calibration_target instrument19 Star7)
	(calibration_target instrument19 Star1)
	(supports instrument20 spectrograph1)
	(supports instrument20 infrared8)
	(supports instrument20 image6)
	(calibration_target instrument20 GroundStation2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation2)
	(supports instrument21 infrared8)
	(calibration_target instrument21 Star0)
	(calibration_target instrument21 GroundStation8)
	(supports instrument22 spectrograph2)
	(calibration_target instrument22 Star0)
	(supports instrument23 image6)
	(calibration_target instrument23 Star7)
	(calibration_target instrument23 Star5)
	(calibration_target instrument23 GroundStation8)
	(supports instrument24 spectrograph2)
	(calibration_target instrument24 Star7)
	(supports instrument25 image6)
	(calibration_target instrument25 GroundStation2)
	(calibration_target instrument25 Star5)
	(calibration_target instrument25 GroundStation8)
	(supports instrument26 thermograph0)
	(supports instrument26 image6)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 GroundStation6)
	(calibration_target instrument26 GroundStation8)
	(supports instrument27 image6)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 GroundStation6)
	(calibration_target instrument27 Star5)
	(supports instrument28 image6)
	(calibration_target instrument28 Star7)
	(calibration_target instrument28 Star5)
	(calibration_target instrument28 GroundStation8)
	(supports instrument29 infrared8)
	(calibration_target instrument29 Star5)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet12)
	(supports instrument30 image6)
	(supports instrument30 infrared3)
	(supports instrument30 spectrograph1)
	(calibration_target instrument30 GroundStation3)
	(calibration_target instrument30 Star0)
	(calibration_target instrument30 Star1)
	(supports instrument31 spectrograph2)
	(supports instrument31 infrared3)
	(supports instrument31 infrared8)
	(calibration_target instrument31 Star5)
	(calibration_target instrument31 GroundStation2)
	(calibration_target instrument31 GroundStation6)
	(supports instrument32 infrared3)
	(supports instrument32 spectrograph1)
	(calibration_target instrument32 Star5)
	(supports instrument33 thermograph0)
	(supports instrument33 thermograph5)
	(calibration_target instrument33 GroundStation8)
	(calibration_target instrument33 GroundStation3)
	(supports instrument34 image7)
	(supports instrument34 image6)
	(supports instrument34 thermograph5)
	(calibration_target instrument34 GroundStation2)
	(calibration_target instrument34 Star5)
	(calibration_target instrument34 GroundStation4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation4)
	(supports instrument35 image7)
	(supports instrument35 thermograph5)
	(supports instrument35 image6)
	(calibration_target instrument35 GroundStation6)
	(calibration_target instrument35 Star0)
	(calibration_target instrument35 Star7)
	(supports instrument36 infrared3)
	(supports instrument36 spectrograph1)
	(supports instrument36 thermograph5)
	(calibration_target instrument36 GroundStation3)
	(calibration_target instrument36 GroundStation2)
	(calibration_target instrument36 GroundStation4)
	(supports instrument37 image6)
	(calibration_target instrument37 Star0)
	(calibration_target instrument37 GroundStation6)
	(calibration_target instrument37 GroundStation2)
	(supports instrument38 infrared3)
	(supports instrument38 spectrograph2)
	(calibration_target instrument38 GroundStation3)
	(calibration_target instrument38 GroundStation2)
	(supports instrument39 thermograph0)
	(supports instrument39 thermograph5)
	(calibration_target instrument39 GroundStation2)
	(supports instrument40 image6)
	(supports instrument40 spectrograph4)
	(supports instrument40 spectrograph2)
	(calibration_target instrument40 GroundStation3)
	(calibration_target instrument40 GroundStation8)
	(calibration_target instrument40 GroundStation6)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation6)
	(supports instrument41 image6)
	(supports instrument41 spectrograph1)
	(supports instrument41 infrared3)
	(calibration_target instrument41 Star1)
	(calibration_target instrument41 Star5)
	(calibration_target instrument41 GroundStation4)
	(supports instrument42 thermograph5)
	(calibration_target instrument42 GroundStation4)
	(calibration_target instrument42 GroundStation2)
	(supports instrument43 thermograph5)
	(calibration_target instrument43 Star0)
	(supports instrument44 spectrograph1)
	(supports instrument44 image6)
	(supports instrument44 infrared8)
	(calibration_target instrument44 GroundStation2)
	(calibration_target instrument44 GroundStation4)
	(calibration_target instrument44 Star5)
	(supports instrument45 infrared3)
	(supports instrument45 image7)
	(supports instrument45 spectrograph1)
	(calibration_target instrument45 GroundStation3)
	(calibration_target instrument45 GroundStation8)
	(calibration_target instrument45 Star7)
	(supports instrument46 image7)
	(supports instrument46 spectrograph4)
	(calibration_target instrument46 GroundStation6)
	(supports instrument47 spectrograph2)
	(calibration_target instrument47 Star0)
	(calibration_target instrument47 GroundStation6)
	(calibration_target instrument47 Star7)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(on_board instrument46 satellite6)
	(on_board instrument47 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet10)
	(supports instrument48 infrared3)
	(calibration_target instrument48 Star7)
	(supports instrument49 image6)
	(calibration_target instrument49 GroundStation6)
	(calibration_target instrument49 GroundStation3)
	(supports instrument50 spectrograph1)
	(supports instrument50 thermograph5)
	(supports instrument50 thermograph0)
	(calibration_target instrument50 Star5)
	(calibration_target instrument50 GroundStation4)
	(supports instrument51 spectrograph4)
	(supports instrument51 image7)
	(calibration_target instrument51 GroundStation3)
	(calibration_target instrument51 Star1)
	(calibration_target instrument51 GroundStation6)
	(supports instrument52 thermograph0)
	(calibration_target instrument52 Star1)
	(calibration_target instrument52 Star7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation2)
	(supports instrument53 image7)
	(supports instrument53 infrared3)
	(calibration_target instrument53 GroundStation2)
	(calibration_target instrument53 GroundStation3)
	(calibration_target instrument53 Star5)
	(supports instrument54 spectrograph1)
	(calibration_target instrument54 GroundStation3)
	(calibration_target instrument54 GroundStation4)
	(calibration_target instrument54 Star7)
	(supports instrument55 thermograph5)
	(supports instrument55 spectrograph4)
	(calibration_target instrument55 GroundStation2)
	(supports instrument56 infrared3)
	(supports instrument56 image7)
	(calibration_target instrument56 Star0)
	(calibration_target instrument56 GroundStation6)
	(calibration_target instrument56 Star7)
	(supports instrument57 image6)
	(supports instrument57 thermograph5)
	(supports instrument57 spectrograph1)
	(calibration_target instrument57 Star5)
	(supports instrument58 infrared8)
	(supports instrument58 infrared3)
	(supports instrument58 spectrograph2)
	(calibration_target instrument58 GroundStation6)
	(calibration_target instrument58 GroundStation2)
	(supports instrument59 infrared8)
	(supports instrument59 spectrograph1)
	(supports instrument59 thermograph5)
	(calibration_target instrument59 GroundStation8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet12)
)
(:goal (and
	(pointing satellite2 Phenomenon16)
	(pointing satellite4 Star0)
	(pointing satellite5 GroundStation2)
	(pointing satellite7 Phenomenon9)
	(pointing satellite8 Phenomenon11)
	(have_image Phenomenon9 thermograph0)
	(have_image Phenomenon9 spectrograph1)
	(have_image Phenomenon9 thermograph5)
	(have_image Planet10 thermograph5)
	(have_image Phenomenon11 spectrograph1)
	(have_image Planet12 infrared8)
	(have_image Planet12 thermograph0)
	(have_image Planet12 spectrograph4)
	(have_image Phenomenon13 thermograph5)
	(have_image Phenomenon13 infrared3)
	(have_image Phenomenon13 infrared8)
	(have_image Phenomenon14 thermograph5)
	(have_image Phenomenon15 spectrograph4)
	(have_image Phenomenon16 spectrograph4)
	(have_image Star17 infrared3)
))

)
