(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite2 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite3 - satellite
	instrument21 - instrument
	satellite4 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite5 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite6 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	satellite7 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	satellite8 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	spectrograph2 - mode
	image4 - mode
	spectrograph3 - mode
	infrared8 - mode
	thermograph5 - mode
	spectrograph7 - mode
	spectrograph0 - mode
	infrared1 - mode
	spectrograph6 - mode
	GroundStation0 - direction
	GroundStation2 - direction
	Star3 - direction
	GroundStation8 - direction
	GroundStation7 - direction
	GroundStation6 - direction
	GroundStation4 - direction
	GroundStation5 - direction
	Star1 - direction
	Planet9 - direction
	Planet10 - direction
	Star11 - direction
	Star12 - direction
	Phenomenon13 - direction
	Planet14 - direction
	Star15 - direction
	Star16 - direction
	Phenomenon17 - direction
)
(:init
	(supports instrument0 spectrograph3)
	(supports instrument0 infrared8)
	(supports instrument0 infrared1)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 Star3)
	(supports instrument1 image4)
	(supports instrument1 spectrograph6)
	(calibration_target instrument1 GroundStation2)
	(supports instrument2 infrared8)
	(calibration_target instrument2 GroundStation6)
	(supports instrument3 spectrograph6)
	(supports instrument3 spectrograph3)
	(supports instrument3 image4)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 GroundStation8)
	(supports instrument4 spectrograph3)
	(calibration_target instrument4 Star1)
	(supports instrument5 spectrograph6)
	(supports instrument5 thermograph5)
	(calibration_target instrument5 GroundStation7)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 Star3)
	(supports instrument6 infrared1)
	(supports instrument6 spectrograph3)
	(supports instrument6 infrared8)
	(calibration_target instrument6 GroundStation4)
	(calibration_target instrument6 GroundStation8)
	(supports instrument7 infrared1)
	(supports instrument7 image4)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation2)
	(supports instrument8 spectrograph3)
	(calibration_target instrument8 GroundStation8)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star12)
	(supports instrument9 spectrograph7)
	(supports instrument9 infrared1)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 GroundStation8)
	(supports instrument10 image4)
	(supports instrument10 spectrograph6)
	(supports instrument10 thermograph5)
	(calibration_target instrument10 Star3)
	(supports instrument11 thermograph5)
	(supports instrument11 infrared1)
	(supports instrument11 image4)
	(calibration_target instrument11 GroundStation8)
	(calibration_target instrument11 Star1)
	(supports instrument12 spectrograph3)
	(calibration_target instrument12 GroundStation0)
	(calibration_target instrument12 GroundStation8)
	(calibration_target instrument12 Star1)
	(supports instrument13 spectrograph7)
	(calibration_target instrument13 GroundStation6)
	(calibration_target instrument13 GroundStation8)
	(supports instrument14 spectrograph3)
	(supports instrument14 spectrograph0)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 GroundStation7)
	(supports instrument15 spectrograph6)
	(supports instrument15 thermograph5)
	(calibration_target instrument15 GroundStation5)
	(supports instrument16 spectrograph2)
	(supports instrument16 infrared1)
	(supports instrument16 thermograph5)
	(calibration_target instrument16 Star1)
	(supports instrument17 image4)
	(supports instrument17 spectrograph0)
	(supports instrument17 spectrograph7)
	(calibration_target instrument17 GroundStation5)
	(calibration_target instrument17 GroundStation7)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(on_board instrument17 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet9)
	(supports instrument18 spectrograph0)
	(supports instrument18 image4)
	(calibration_target instrument18 GroundStation0)
	(calibration_target instrument18 GroundStation2)
	(calibration_target instrument18 GroundStation7)
	(supports instrument19 spectrograph7)
	(supports instrument19 spectrograph0)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 GroundStation2)
	(calibration_target instrument19 GroundStation4)
	(supports instrument20 spectrograph2)
	(supports instrument20 infrared8)
	(calibration_target instrument20 GroundStation7)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 Star3)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star15)
	(supports instrument21 spectrograph2)
	(calibration_target instrument21 GroundStation8)
	(on_board instrument21 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet14)
	(supports instrument22 spectrograph6)
	(supports instrument22 thermograph5)
	(supports instrument22 image4)
	(calibration_target instrument22 GroundStation8)
	(supports instrument23 thermograph5)
	(calibration_target instrument23 Star1)
	(calibration_target instrument23 GroundStation0)
	(supports instrument24 infrared1)
	(supports instrument24 spectrograph0)
	(calibration_target instrument24 GroundStation4)
	(supports instrument25 infrared8)
	(calibration_target instrument25 GroundStation8)
	(calibration_target instrument25 GroundStation6)
	(supports instrument26 spectrograph3)
	(calibration_target instrument26 GroundStation8)
	(calibration_target instrument26 GroundStation4)
	(supports instrument27 spectrograph7)
	(calibration_target instrument27 GroundStation8)
	(supports instrument28 thermograph5)
	(calibration_target instrument28 GroundStation7)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon17)
	(supports instrument29 infrared1)
	(calibration_target instrument29 GroundStation8)
	(calibration_target instrument29 Star1)
	(calibration_target instrument29 Star3)
	(supports instrument30 spectrograph7)
	(supports instrument30 spectrograph2)
	(calibration_target instrument30 GroundStation8)
	(supports instrument31 image4)
	(calibration_target instrument31 GroundStation0)
	(supports instrument32 infrared1)
	(supports instrument32 spectrograph3)
	(supports instrument32 thermograph5)
	(calibration_target instrument32 GroundStation4)
	(calibration_target instrument32 GroundStation7)
	(calibration_target instrument32 GroundStation0)
	(supports instrument33 spectrograph0)
	(supports instrument33 spectrograph7)
	(calibration_target instrument33 GroundStation7)
	(calibration_target instrument33 GroundStation8)
	(supports instrument34 spectrograph3)
	(calibration_target instrument34 GroundStation2)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation7)
	(supports instrument35 spectrograph3)
	(supports instrument35 spectrograph7)
	(calibration_target instrument35 GroundStation8)
	(calibration_target instrument35 GroundStation6)
	(calibration_target instrument35 Star1)
	(supports instrument36 image4)
	(calibration_target instrument36 Star1)
	(supports instrument37 thermograph5)
	(supports instrument37 spectrograph6)
	(supports instrument37 spectrograph0)
	(calibration_target instrument37 GroundStation6)
	(calibration_target instrument37 GroundStation8)
	(supports instrument38 thermograph5)
	(calibration_target instrument38 GroundStation0)
	(calibration_target instrument38 Star1)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star1)
	(supports instrument39 spectrograph3)
	(calibration_target instrument39 GroundStation7)
	(supports instrument40 infrared8)
	(supports instrument40 spectrograph6)
	(calibration_target instrument40 GroundStation2)
	(supports instrument41 spectrograph6)
	(supports instrument41 spectrograph0)
	(supports instrument41 thermograph5)
	(calibration_target instrument41 Star3)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star1)
	(supports instrument42 spectrograph7)
	(supports instrument42 spectrograph6)
	(calibration_target instrument42 GroundStation5)
	(calibration_target instrument42 GroundStation8)
	(calibration_target instrument42 GroundStation4)
	(supports instrument43 spectrograph0)
	(supports instrument43 spectrograph3)
	(calibration_target instrument43 GroundStation6)
	(supports instrument44 spectrograph0)
	(calibration_target instrument44 GroundStation8)
	(calibration_target instrument44 Star3)
	(supports instrument45 infrared1)
	(calibration_target instrument45 GroundStation7)
	(calibration_target instrument45 Star1)
	(supports instrument46 spectrograph6)
	(supports instrument46 infrared8)
	(supports instrument46 infrared1)
	(calibration_target instrument46 GroundStation5)
	(supports instrument47 spectrograph6)
	(calibration_target instrument47 Star1)
	(calibration_target instrument47 GroundStation6)
	(supports instrument48 thermograph5)
	(supports instrument48 spectrograph6)
	(supports instrument48 infrared1)
	(calibration_target instrument48 GroundStation7)
	(supports instrument49 spectrograph0)
	(supports instrument49 spectrograph7)
	(supports instrument49 thermograph5)
	(calibration_target instrument49 Star1)
	(calibration_target instrument49 GroundStation4)
	(calibration_target instrument49 GroundStation6)
	(supports instrument50 spectrograph6)
	(supports instrument50 infrared1)
	(calibration_target instrument50 Star1)
	(calibration_target instrument50 GroundStation5)
	(calibration_target instrument50 GroundStation4)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation7)
)
(:goal (and
	(pointing satellite0 Star12)
	(pointing satellite2 GroundStation2)
	(pointing satellite3 GroundStation2)
	(pointing satellite5 Star11)
	(have_image Planet9 image4)
	(have_image Planet10 infrared8)
	(have_image Planet10 thermograph5)
	(have_image Star11 infrared1)
	(have_image Star12 infrared1)
	(have_image Planet14 infrared8)
	(have_image Star15 spectrograph2)
	(have_image Star15 infrared8)
	(have_image Star15 spectrograph0)
	(have_image Star16 infrared8)
))

)
