(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite3 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite4 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite5 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite6 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite7 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	satellite8 - satellite
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	infrared3 - mode
	spectrograph5 - mode
	infrared7 - mode
	image2 - mode
	thermograph6 - mode
	infrared4 - mode
	infrared1 - mode
	infrared0 - mode
	thermograph8 - mode
	Star2 - direction
	Star4 - direction
	GroundStation7 - direction
	GroundStation0 - direction
	GroundStation1 - direction
	GroundStation8 - direction
	Star3 - direction
	Star5 - direction
	GroundStation6 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Phenomenon11 - direction
	Star12 - direction
	Planet13 - direction
	Phenomenon14 - direction
	Phenomenon15 - direction
	Phenomenon16 - direction
	Star17 - direction
)
(:init
	(supports instrument0 infrared0)
	(supports instrument0 thermograph8)
	(calibration_target instrument0 Star4)
	(calibration_target instrument0 Star3)
	(supports instrument1 infrared1)
	(supports instrument1 infrared7)
	(calibration_target instrument1 Star4)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 Star3)
	(supports instrument2 thermograph6)
	(supports instrument2 infrared3)
	(supports instrument2 infrared1)
	(calibration_target instrument2 GroundStation8)
	(calibration_target instrument2 Star2)
	(supports instrument3 thermograph8)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 Star5)
	(calibration_target instrument3 GroundStation6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation6)
	(supports instrument4 spectrograph5)
	(supports instrument4 infrared3)
	(calibration_target instrument4 Star4)
	(supports instrument5 infrared3)
	(supports instrument5 infrared1)
	(supports instrument5 infrared4)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 GroundStation7)
	(supports instrument6 infrared3)
	(supports instrument6 infrared0)
	(supports instrument6 spectrograph5)
	(calibration_target instrument6 Star2)
	(calibration_target instrument6 GroundStation8)
	(supports instrument7 infrared1)
	(supports instrument7 spectrograph5)
	(calibration_target instrument7 GroundStation8)
	(supports instrument8 thermograph8)
	(calibration_target instrument8 Star4)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 Star3)
	(supports instrument9 image2)
	(supports instrument9 spectrograph5)
	(calibration_target instrument9 GroundStation8)
	(calibration_target instrument9 GroundStation6)
	(supports instrument10 spectrograph5)
	(calibration_target instrument10 GroundStation6)
	(calibration_target instrument10 GroundStation1)
	(calibration_target instrument10 GroundStation8)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon16)
	(supports instrument11 infrared0)
	(supports instrument11 infrared7)
	(supports instrument11 spectrograph5)
	(calibration_target instrument11 Star2)
	(calibration_target instrument11 GroundStation7)
	(supports instrument12 spectrograph5)
	(supports instrument12 infrared4)
	(supports instrument12 thermograph6)
	(calibration_target instrument12 GroundStation1)
	(calibration_target instrument12 Star5)
	(supports instrument13 image2)
	(calibration_target instrument13 GroundStation1)
	(calibration_target instrument13 Star2)
	(supports instrument14 spectrograph5)
	(supports instrument14 infrared7)
	(supports instrument14 infrared4)
	(calibration_target instrument14 GroundStation1)
	(calibration_target instrument14 GroundStation8)
	(calibration_target instrument14 GroundStation0)
	(supports instrument15 thermograph6)
	(calibration_target instrument15 GroundStation8)
	(calibration_target instrument15 GroundStation6)
	(calibration_target instrument15 Star2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation0)
	(supports instrument16 image2)
	(supports instrument16 infrared3)
	(supports instrument16 thermograph8)
	(calibration_target instrument16 GroundStation8)
	(calibration_target instrument16 GroundStation0)
	(supports instrument17 spectrograph5)
	(supports instrument17 thermograph8)
	(calibration_target instrument17 GroundStation8)
	(calibration_target instrument17 Star5)
	(supports instrument18 infrared3)
	(supports instrument18 thermograph8)
	(calibration_target instrument18 GroundStation0)
	(calibration_target instrument18 Star4)
	(calibration_target instrument18 Star3)
	(supports instrument19 infrared1)
	(supports instrument19 infrared3)
	(supports instrument19 image2)
	(calibration_target instrument19 GroundStation6)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 infrared4)
	(supports instrument20 infrared7)
	(supports instrument20 spectrograph5)
	(calibration_target instrument20 GroundStation1)
	(calibration_target instrument20 Star5)
	(calibration_target instrument20 GroundStation8)
	(supports instrument21 infrared1)
	(supports instrument21 spectrograph5)
	(supports instrument21 infrared3)
	(calibration_target instrument21 GroundStation6)
	(calibration_target instrument21 GroundStation7)
	(calibration_target instrument21 Star5)
	(supports instrument22 infrared7)
	(supports instrument22 spectrograph5)
	(supports instrument22 thermograph8)
	(calibration_target instrument22 GroundStation6)
	(supports instrument23 thermograph8)
	(supports instrument23 infrared0)
	(supports instrument23 infrared7)
	(calibration_target instrument23 GroundStation8)
	(calibration_target instrument23 GroundStation7)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 infrared7)
	(supports instrument24 thermograph6)
	(calibration_target instrument24 Star3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon15)
	(supports instrument25 image2)
	(supports instrument25 infrared0)
	(supports instrument25 infrared3)
	(calibration_target instrument25 GroundStation6)
	(supports instrument26 spectrograph5)
	(supports instrument26 thermograph8)
	(supports instrument26 image2)
	(calibration_target instrument26 Star3)
	(supports instrument27 infrared0)
	(supports instrument27 thermograph8)
	(supports instrument27 infrared4)
	(calibration_target instrument27 GroundStation7)
	(supports instrument28 infrared0)
	(supports instrument28 infrared4)
	(calibration_target instrument28 GroundStation7)
	(calibration_target instrument28 GroundStation1)
	(supports instrument29 infrared1)
	(calibration_target instrument29 Star4)
	(calibration_target instrument29 GroundStation6)
	(calibration_target instrument29 Star2)
	(supports instrument30 image2)
	(supports instrument30 thermograph8)
	(calibration_target instrument30 Star2)
	(supports instrument31 infrared0)
	(supports instrument31 image2)
	(supports instrument31 infrared1)
	(calibration_target instrument31 Star5)
	(calibration_target instrument31 Star3)
	(calibration_target instrument31 Star4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument32 infrared3)
	(calibration_target instrument32 GroundStation0)
	(calibration_target instrument32 Star4)
	(calibration_target instrument32 Star5)
	(supports instrument33 infrared4)
	(supports instrument33 infrared3)
	(supports instrument33 spectrograph5)
	(calibration_target instrument33 Star3)
	(supports instrument34 thermograph8)
	(calibration_target instrument34 GroundStation6)
	(calibration_target instrument34 GroundStation8)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon11)
	(supports instrument35 infrared1)
	(supports instrument35 infrared7)
	(calibration_target instrument35 Star5)
	(supports instrument36 thermograph8)
	(calibration_target instrument36 Star4)
	(supports instrument37 spectrograph5)
	(supports instrument37 image2)
	(calibration_target instrument37 Star4)
	(calibration_target instrument37 Star3)
	(calibration_target instrument37 GroundStation6)
	(supports instrument38 infrared0)
	(supports instrument38 spectrograph5)
	(calibration_target instrument38 Star2)
	(supports instrument39 infrared1)
	(supports instrument39 thermograph6)
	(supports instrument39 image2)
	(calibration_target instrument39 GroundStation0)
	(supports instrument40 image2)
	(supports instrument40 thermograph6)
	(calibration_target instrument40 Star5)
	(calibration_target instrument40 GroundStation0)
	(supports instrument41 thermograph8)
	(calibration_target instrument41 Star5)
	(supports instrument42 thermograph6)
	(supports instrument42 infrared0)
	(supports instrument42 thermograph8)
	(calibration_target instrument42 Star5)
	(calibration_target instrument42 GroundStation7)
	(calibration_target instrument42 Star2)
	(supports instrument43 thermograph6)
	(supports instrument43 image2)
	(supports instrument43 infrared7)
	(calibration_target instrument43 GroundStation1)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet9)
	(supports instrument44 spectrograph5)
	(calibration_target instrument44 Star2)
	(supports instrument45 infrared0)
	(supports instrument45 spectrograph5)
	(calibration_target instrument45 Star4)
	(supports instrument46 image2)
	(calibration_target instrument46 GroundStation6)
	(calibration_target instrument46 GroundStation8)
	(calibration_target instrument46 GroundStation7)
	(supports instrument47 image2)
	(calibration_target instrument47 Star4)
	(calibration_target instrument47 Star5)
	(calibration_target instrument47 GroundStation7)
	(supports instrument48 infrared4)
	(supports instrument48 infrared3)
	(supports instrument48 infrared1)
	(calibration_target instrument48 GroundStation7)
	(calibration_target instrument48 Star2)
	(supports instrument49 infrared7)
	(supports instrument49 infrared1)
	(calibration_target instrument49 GroundStation1)
	(supports instrument50 infrared0)
	(supports instrument50 thermograph6)
	(supports instrument50 spectrograph5)
	(calibration_target instrument50 GroundStation0)
	(supports instrument51 image2)
	(supports instrument51 infrared3)
	(calibration_target instrument51 Star4)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation7)
	(supports instrument52 spectrograph5)
	(supports instrument52 infrared4)
	(calibration_target instrument52 GroundStation1)
	(supports instrument53 thermograph6)
	(supports instrument53 infrared4)
	(calibration_target instrument53 GroundStation7)
	(calibration_target instrument53 Star4)
	(calibration_target instrument53 Star3)
	(supports instrument54 infrared7)
	(calibration_target instrument54 Star5)
	(calibration_target instrument54 GroundStation0)
	(calibration_target instrument54 GroundStation8)
	(supports instrument55 infrared7)
	(supports instrument55 image2)
	(calibration_target instrument55 GroundStation8)
	(calibration_target instrument55 GroundStation1)
	(supports instrument56 infrared0)
	(supports instrument56 thermograph8)
	(calibration_target instrument56 Star5)
	(supports instrument57 thermograph6)
	(supports instrument57 infrared0)
	(supports instrument57 image2)
	(calibration_target instrument57 GroundStation8)
	(calibration_target instrument57 GroundStation0)
	(supports instrument58 infrared0)
	(supports instrument58 infrared1)
	(supports instrument58 infrared4)
	(calibration_target instrument58 GroundStation8)
	(calibration_target instrument58 GroundStation1)
	(calibration_target instrument58 Star5)
	(supports instrument59 thermograph8)
	(calibration_target instrument59 GroundStation6)
	(calibration_target instrument59 Star5)
	(calibration_target instrument59 Star3)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon16)
)
(:goal (and
	(pointing satellite0 Planet9)
	(pointing satellite1 Star5)
	(pointing satellite3 GroundStation7)
	(pointing satellite5 GroundStation1)
	(pointing satellite6 Phenomenon15)
	(pointing satellite7 GroundStation1)
	(have_image Planet9 thermograph8)
	(have_image Planet9 infrared0)
	(have_image Planet9 infrared7)
	(have_image Phenomenon10 image2)
	(have_image Phenomenon11 infrared4)
	(have_image Phenomenon11 infrared7)
	(have_image Star12 infrared4)
	(have_image Planet13 infrared1)
	(have_image Phenomenon14 thermograph8)
	(have_image Phenomenon15 thermograph8)
	(have_image Phenomenon15 infrared0)
	(have_image Phenomenon15 infrared3)
	(have_image Phenomenon16 image2)
	(have_image Phenomenon16 infrared3)
	(have_image Phenomenon16 infrared7)
	(have_image Star17 thermograph6)
))

)
