(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite5 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite6 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite7 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite8 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	image6 - mode
	spectrograph4 - mode
	spectrograph3 - mode
	image1 - mode
	image0 - mode
	infrared5 - mode
	infrared8 - mode
	thermograph7 - mode
	image2 - mode
	Star7 - direction
	GroundStation6 - direction
	GroundStation1 - direction
	Star5 - direction
	GroundStation2 - direction
	Star0 - direction
	Star3 - direction
	Star4 - direction
	GroundStation8 - direction
	Phenomenon9 - direction
	Phenomenon10 - direction
	Planet11 - direction
	Phenomenon12 - direction
	Star13 - direction
	Star14 - direction
	Phenomenon15 - direction
	Phenomenon16 - direction
	Phenomenon17 - direction
)
(:init
	(supports instrument0 image0)
	(supports instrument0 spectrograph3)
	(calibration_target instrument0 GroundStation1)
	(calibration_target instrument0 Star5)
	(supports instrument1 infrared5)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 Star0)
	(supports instrument2 infrared8)
	(supports instrument2 spectrograph4)
	(calibration_target instrument2 GroundStation1)
	(supports instrument3 image2)
	(supports instrument3 spectrograph4)
	(calibration_target instrument3 Star4)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 infrared8)
	(calibration_target instrument4 Star7)
	(supports instrument5 image2)
	(supports instrument5 infrared8)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 Star4)
	(calibration_target instrument5 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation8)
	(supports instrument6 image6)
	(supports instrument6 image0)
	(supports instrument6 spectrograph4)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 Star7)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star13)
	(supports instrument7 image0)
	(calibration_target instrument7 Star5)
	(calibration_target instrument7 GroundStation8)
	(supports instrument8 infrared5)
	(supports instrument8 image2)
	(supports instrument8 infrared8)
	(calibration_target instrument8 Star0)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet11)
	(supports instrument9 spectrograph3)
	(supports instrument9 infrared5)
	(calibration_target instrument9 Star3)
	(supports instrument10 infrared5)
	(supports instrument10 infrared8)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 Star4)
	(calibration_target instrument10 GroundStation2)
	(supports instrument11 image2)
	(supports instrument11 image1)
	(calibration_target instrument11 GroundStation1)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon9)
	(supports instrument12 infrared8)
	(calibration_target instrument12 GroundStation8)
	(supports instrument13 infrared8)
	(supports instrument13 image6)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation8)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 spectrograph4)
	(supports instrument14 spectrograph3)
	(supports instrument14 image2)
	(calibration_target instrument14 Star0)
	(calibration_target instrument14 GroundStation8)
	(calibration_target instrument14 Star3)
	(supports instrument15 image6)
	(supports instrument15 spectrograph3)
	(calibration_target instrument15 Star4)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 GroundStation1)
	(supports instrument16 image0)
	(calibration_target instrument16 Star4)
	(supports instrument17 spectrograph4)
	(calibration_target instrument17 Star3)
	(calibration_target instrument17 Star7)
	(supports instrument18 thermograph7)
	(supports instrument18 image2)
	(calibration_target instrument18 Star7)
	(calibration_target instrument18 GroundStation2)
	(calibration_target instrument18 Star0)
	(supports instrument19 image6)
	(supports instrument19 image1)
	(supports instrument19 infrared8)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 GroundStation2)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star13)
	(supports instrument20 image2)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 GroundStation6)
	(supports instrument21 spectrograph3)
	(supports instrument21 thermograph7)
	(calibration_target instrument21 Star3)
	(calibration_target instrument21 GroundStation6)
	(calibration_target instrument21 Star4)
	(supports instrument22 infrared5)
	(calibration_target instrument22 GroundStation6)
	(calibration_target instrument22 Star3)
	(supports instrument23 spectrograph3)
	(supports instrument23 spectrograph4)
	(supports instrument23 image2)
	(calibration_target instrument23 GroundStation8)
	(calibration_target instrument23 Star5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon16)
	(supports instrument24 image0)
	(supports instrument24 image2)
	(calibration_target instrument24 Star4)
	(supports instrument25 thermograph7)
	(supports instrument25 image0)
	(supports instrument25 infrared8)
	(calibration_target instrument25 Star5)
	(calibration_target instrument25 Star4)
	(calibration_target instrument25 GroundStation6)
	(supports instrument26 infrared5)
	(calibration_target instrument26 Star3)
	(supports instrument27 image6)
	(supports instrument27 infrared5)
	(supports instrument27 spectrograph4)
	(calibration_target instrument27 Star5)
	(supports instrument28 spectrograph4)
	(calibration_target instrument28 GroundStation2)
	(calibration_target instrument28 GroundStation8)
	(supports instrument29 infrared5)
	(calibration_target instrument29 GroundStation1)
	(supports instrument30 spectrograph4)
	(calibration_target instrument30 GroundStation2)
	(calibration_target instrument30 GroundStation8)
	(supports instrument31 thermograph7)
	(calibration_target instrument31 GroundStation1)
	(calibration_target instrument31 GroundStation2)
	(calibration_target instrument31 Star5)
	(supports instrument32 spectrograph4)
	(supports instrument32 spectrograph3)
	(supports instrument32 image2)
	(calibration_target instrument32 Star5)
	(calibration_target instrument32 Star4)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(on_board instrument27 satellite6)
	(on_board instrument28 satellite6)
	(on_board instrument29 satellite6)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet11)
	(supports instrument33 thermograph7)
	(calibration_target instrument33 Star5)
	(calibration_target instrument33 Star4)
	(supports instrument34 spectrograph4)
	(supports instrument34 spectrograph3)
	(calibration_target instrument34 GroundStation1)
	(calibration_target instrument34 GroundStation2)
	(supports instrument35 image6)
	(supports instrument35 spectrograph4)
	(calibration_target instrument35 GroundStation1)
	(calibration_target instrument35 Star4)
	(calibration_target instrument35 Star0)
	(supports instrument36 image2)
	(calibration_target instrument36 GroundStation8)
	(supports instrument37 infrared5)
	(supports instrument37 image1)
	(calibration_target instrument37 Star5)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument38 infrared5)
	(supports instrument38 spectrograph3)
	(supports instrument38 image6)
	(calibration_target instrument38 Star3)
	(calibration_target instrument38 GroundStation2)
	(supports instrument39 image0)
	(supports instrument39 spectrograph4)
	(calibration_target instrument39 Star0)
	(supports instrument40 spectrograph3)
	(calibration_target instrument40 Star3)
	(supports instrument41 image0)
	(supports instrument41 image1)
	(calibration_target instrument41 Star3)
	(calibration_target instrument41 Star0)
	(supports instrument42 infrared5)
	(calibration_target instrument42 Star4)
	(calibration_target instrument42 GroundStation8)
	(supports instrument43 image2)
	(supports instrument43 thermograph7)
	(supports instrument43 infrared8)
	(calibration_target instrument43 GroundStation8)
	(on_board instrument38 satellite8)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star0)
)
(:goal (and
	(pointing satellite2 Planet11)
	(pointing satellite7 GroundStation8)
	(pointing satellite8 Phenomenon17)
	(have_image Phenomenon9 image1)
	(have_image Phenomenon9 spectrograph3)
	(have_image Phenomenon10 image2)
	(have_image Phenomenon10 spectrograph3)
	(have_image Phenomenon10 thermograph7)
	(have_image Planet11 image0)
	(have_image Planet11 infrared5)
	(have_image Phenomenon12 infrared5)
	(have_image Phenomenon12 spectrograph3)
	(have_image Star13 infrared8)
	(have_image Star13 image0)
	(have_image Star14 thermograph7)
	(have_image Star14 infrared5)
	(have_image Star14 image0)
	(have_image Phenomenon15 spectrograph3)
	(have_image Phenomenon15 image6)
	(have_image Phenomenon16 image2)
	(have_image Phenomenon16 image0)
	(have_image Phenomenon17 infrared8)
))

)
