(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite4 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite6 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite7 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite8 - satellite
	instrument35 - instrument
	infrared4 - mode
	infrared6 - mode
	thermograph8 - mode
	thermograph1 - mode
	spectrograph0 - mode
	spectrograph3 - mode
	spectrograph5 - mode
	spectrograph2 - mode
	thermograph7 - mode
	GroundStation5 - direction
	GroundStation8 - direction
	Star0 - direction
	GroundStation1 - direction
	Star3 - direction
	Star4 - direction
	Star2 - direction
	GroundStation7 - direction
	Star6 - direction
	Phenomenon9 - direction
	Star10 - direction
	Star11 - direction
	Star12 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
	Planet15 - direction
	Phenomenon16 - direction
	Star17 - direction
)
(:init
	(supports instrument0 thermograph1)
	(calibration_target instrument0 GroundStation8)
	(calibration_target instrument0 Star6)
	(calibration_target instrument0 GroundStation5)
	(supports instrument1 infrared6)
	(supports instrument1 infrared4)
	(supports instrument1 thermograph8)
	(calibration_target instrument1 Star3)
	(supports instrument2 spectrograph2)
	(calibration_target instrument2 Star3)
	(supports instrument3 infrared4)
	(supports instrument3 spectrograph2)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 Star2)
	(calibration_target instrument3 Star0)
	(supports instrument4 thermograph1)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 GroundStation8)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet15)
	(supports instrument5 thermograph1)
	(supports instrument5 thermograph8)
	(supports instrument5 infrared4)
	(calibration_target instrument5 GroundStation8)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star2)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 GroundStation7)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star12)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 GroundStation1)
	(calibration_target instrument7 Star2)
	(supports instrument8 thermograph8)
	(calibration_target instrument8 GroundStation7)
	(calibration_target instrument8 Star3)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star12)
	(supports instrument9 thermograph8)
	(calibration_target instrument9 Star4)
	(calibration_target instrument9 GroundStation8)
	(calibration_target instrument9 Star2)
	(supports instrument10 spectrograph0)
	(supports instrument10 thermograph7)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 GroundStation7)
	(supports instrument11 infrared4)
	(supports instrument11 spectrograph3)
	(supports instrument11 thermograph8)
	(calibration_target instrument11 Star6)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 Star0)
	(supports instrument12 thermograph8)
	(supports instrument12 spectrograph3)
	(supports instrument12 spectrograph5)
	(calibration_target instrument12 GroundStation8)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation7)
	(supports instrument13 thermograph1)
	(calibration_target instrument13 Star2)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 Star4)
	(supports instrument14 spectrograph2)
	(supports instrument14 infrared6)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 Star2)
	(supports instrument15 thermograph7)
	(supports instrument15 infrared6)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 GroundStation5)
	(supports instrument16 thermograph7)
	(calibration_target instrument16 Star2)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet15)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 GroundStation1)
	(calibration_target instrument17 GroundStation8)
	(calibration_target instrument17 Star2)
	(supports instrument18 thermograph8)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 GroundStation8)
	(supports instrument19 thermograph7)
	(supports instrument19 spectrograph0)
	(calibration_target instrument19 Star2)
	(calibration_target instrument19 GroundStation8)
	(calibration_target instrument19 Star0)
	(supports instrument20 spectrograph2)
	(supports instrument20 thermograph8)
	(supports instrument20 thermograph7)
	(calibration_target instrument20 GroundStation1)
	(calibration_target instrument20 Star6)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star0)
	(supports instrument21 spectrograph2)
	(supports instrument21 thermograph8)
	(supports instrument21 thermograph1)
	(calibration_target instrument21 GroundStation8)
	(calibration_target instrument21 Star4)
	(calibration_target instrument21 Star6)
	(supports instrument22 infrared6)
	(calibration_target instrument22 Star2)
	(calibration_target instrument22 GroundStation7)
	(calibration_target instrument22 Star0)
	(supports instrument23 spectrograph5)
	(supports instrument23 infrared6)
	(supports instrument23 spectrograph3)
	(calibration_target instrument23 Star2)
	(calibration_target instrument23 Star4)
	(supports instrument24 thermograph7)
	(supports instrument24 spectrograph0)
	(supports instrument24 infrared6)
	(calibration_target instrument24 Star0)
	(supports instrument25 spectrograph0)
	(supports instrument25 spectrograph2)
	(supports instrument25 thermograph1)
	(calibration_target instrument25 Star0)
	(calibration_target instrument25 Star6)
	(supports instrument26 infrared4)
	(supports instrument26 spectrograph3)
	(supports instrument26 thermograph8)
	(calibration_target instrument26 Star3)
	(supports instrument27 spectrograph5)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 Star0)
	(calibration_target instrument27 GroundStation7)
	(supports instrument28 spectrograph0)
	(supports instrument28 infrared6)
	(supports instrument28 spectrograph5)
	(calibration_target instrument28 Star0)
	(supports instrument29 thermograph8)
	(calibration_target instrument29 Star6)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(on_board instrument27 satellite6)
	(on_board instrument28 satellite6)
	(on_board instrument29 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation7)
	(supports instrument30 spectrograph3)
	(supports instrument30 thermograph1)
	(supports instrument30 thermograph7)
	(calibration_target instrument30 GroundStation1)
	(calibration_target instrument30 Star6)
	(supports instrument31 thermograph7)
	(supports instrument31 spectrograph2)
	(calibration_target instrument31 Star4)
	(supports instrument32 spectrograph0)
	(supports instrument32 thermograph7)
	(supports instrument32 spectrograph3)
	(calibration_target instrument32 Star2)
	(calibration_target instrument32 GroundStation1)
	(supports instrument33 spectrograph3)
	(calibration_target instrument33 Star4)
	(calibration_target instrument33 Star3)
	(supports instrument34 spectrograph5)
	(calibration_target instrument34 GroundStation7)
	(calibration_target instrument34 Star2)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation7)
	(supports instrument35 thermograph7)
	(supports instrument35 spectrograph2)
	(calibration_target instrument35 Star6)
	(calibration_target instrument35 GroundStation7)
	(on_board instrument35 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star0)
)
(:goal (and
	(pointing satellite0 Star3)
	(pointing satellite1 Phenomenon9)
	(pointing satellite2 Phenomenon14)
	(pointing satellite5 Star12)
	(pointing satellite6 Star2)
	(pointing satellite8 Phenomenon16)
	(have_image Phenomenon9 infrared6)
	(have_image Phenomenon9 thermograph8)
	(have_image Star10 spectrograph2)
	(have_image Star10 infrared4)
	(have_image Star11 spectrograph5)
	(have_image Star11 spectrograph2)
	(have_image Star12 infrared4)
	(have_image Star12 spectrograph5)
	(have_image Star12 infrared6)
	(have_image Phenomenon13 thermograph7)
	(have_image Phenomenon13 infrared6)
	(have_image Phenomenon14 thermograph7)
	(have_image Planet15 thermograph8)
	(have_image Planet15 thermograph7)
	(have_image Planet15 spectrograph3)
	(have_image Phenomenon16 thermograph8)
	(have_image Phenomenon16 spectrograph5)
	(have_image Phenomenon16 spectrograph2)
	(have_image Star17 thermograph8)
	(have_image Star17 infrared6)
	(have_image Star17 thermograph1)
))

)
