(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite4 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite5 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite6 - satellite
	instrument22 - instrument
	satellite7 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite8 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	spectrograph7 - mode
	infrared6 - mode
	image2 - mode
	infrared0 - mode
	infrared1 - mode
	spectrograph3 - mode
	image8 - mode
	infrared5 - mode
	thermograph4 - mode
	GroundStation8 - direction
	Star5 - direction
	Star3 - direction
	GroundStation2 - direction
	GroundStation0 - direction
	Star7 - direction
	Star1 - direction
	Star4 - direction
	Star6 - direction
	Star9 - direction
	Phenomenon10 - direction
	Star11 - direction
	Planet12 - direction
	Phenomenon13 - direction
	Star14 - direction
	Phenomenon15 - direction
	Planet16 - direction
	Phenomenon17 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 infrared0)
	(supports instrument0 image8)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 Star6)
	(supports instrument1 thermograph4)
	(supports instrument1 image2)
	(supports instrument1 infrared1)
	(calibration_target instrument1 GroundStation2)
	(supports instrument2 infrared6)
	(supports instrument2 infrared5)
	(supports instrument2 spectrograph7)
	(calibration_target instrument2 GroundStation0)
	(supports instrument3 spectrograph7)
	(supports instrument3 infrared0)
	(supports instrument3 infrared5)
	(calibration_target instrument3 Star5)
	(supports instrument4 infrared1)
	(supports instrument4 image8)
	(calibration_target instrument4 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star9)
	(supports instrument5 infrared0)
	(supports instrument5 image2)
	(supports instrument5 spectrograph7)
	(calibration_target instrument5 Star4)
	(calibration_target instrument5 Star3)
	(supports instrument6 spectrograph3)
	(calibration_target instrument6 Star3)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star5)
	(supports instrument7 infrared5)
	(supports instrument7 image2)
	(calibration_target instrument7 Star7)
	(calibration_target instrument7 GroundStation8)
	(calibration_target instrument7 Star1)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet16)
	(supports instrument8 thermograph4)
	(supports instrument8 spectrograph3)
	(calibration_target instrument8 GroundStation0)
	(calibration_target instrument8 Star4)
	(supports instrument9 infrared5)
	(calibration_target instrument9 GroundStation8)
	(supports instrument10 image8)
	(calibration_target instrument10 GroundStation8)
	(supports instrument11 infrared6)
	(supports instrument11 spectrograph7)
	(calibration_target instrument11 Star4)
	(supports instrument12 infrared6)
	(calibration_target instrument12 GroundStation0)
	(calibration_target instrument12 Star1)
	(calibration_target instrument12 Star3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star11)
	(supports instrument13 spectrograph3)
	(calibration_target instrument13 Star6)
	(supports instrument14 image2)
	(supports instrument14 infrared5)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 Star4)
	(supports instrument15 image8)
	(calibration_target instrument15 Star5)
	(supports instrument16 infrared5)
	(supports instrument16 image2)
	(supports instrument16 image8)
	(calibration_target instrument16 Star1)
	(calibration_target instrument16 Star3)
	(calibration_target instrument16 Star7)
	(supports instrument17 image2)
	(supports instrument17 infrared6)
	(calibration_target instrument17 GroundStation2)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 GroundStation0)
	(supports instrument18 spectrograph3)
	(calibration_target instrument18 GroundStation8)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon13)
	(supports instrument19 infrared0)
	(supports instrument19 spectrograph3)
	(calibration_target instrument19 GroundStation8)
	(calibration_target instrument19 Star4)
	(calibration_target instrument19 Star6)
	(supports instrument20 spectrograph7)
	(supports instrument20 thermograph4)
	(supports instrument20 infrared0)
	(calibration_target instrument20 Star5)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 Star6)
	(supports instrument21 infrared0)
	(supports instrument21 image2)
	(calibration_target instrument21 Star3)
	(calibration_target instrument21 Star5)
	(calibration_target instrument21 GroundStation0)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument22 spectrograph3)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 GroundStation0)
	(on_board instrument22 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star4)
	(supports instrument23 thermograph4)
	(supports instrument23 infrared5)
	(calibration_target instrument23 GroundStation2)
	(supports instrument24 infrared1)
	(calibration_target instrument24 Star1)
	(supports instrument25 infrared0)
	(supports instrument25 image2)
	(calibration_target instrument25 GroundStation0)
	(calibration_target instrument25 Star4)
	(supports instrument26 spectrograph7)
	(supports instrument26 infrared5)
	(supports instrument26 thermograph4)
	(calibration_target instrument26 Star1)
	(calibration_target instrument26 Star7)
	(calibration_target instrument26 Star6)
	(supports instrument27 infrared5)
	(calibration_target instrument27 GroundStation2)
	(on_board instrument23 satellite7)
	(on_board instrument24 satellite7)
	(on_board instrument25 satellite7)
	(on_board instrument26 satellite7)
	(on_board instrument27 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation2)
	(supports instrument28 image2)
	(supports instrument28 infrared6)
	(calibration_target instrument28 Star5)
	(supports instrument29 infrared1)
	(supports instrument29 image8)
	(supports instrument29 infrared0)
	(calibration_target instrument29 Star6)
	(calibration_target instrument29 Star3)
	(supports instrument30 infrared1)
	(supports instrument30 infrared0)
	(calibration_target instrument30 Star6)
	(calibration_target instrument30 GroundStation2)
	(calibration_target instrument30 Star4)
	(supports instrument31 infrared5)
	(calibration_target instrument31 GroundStation0)
	(supports instrument32 infrared1)
	(supports instrument32 infrared5)
	(supports instrument32 spectrograph3)
	(calibration_target instrument32 Star7)
	(supports instrument33 image8)
	(supports instrument33 spectrograph3)
	(supports instrument33 thermograph4)
	(calibration_target instrument33 Star1)
	(supports instrument34 thermograph4)
	(supports instrument34 infrared5)
	(calibration_target instrument34 Star6)
	(calibration_target instrument34 Star4)
	(on_board instrument28 satellite8)
	(on_board instrument29 satellite8)
	(on_board instrument30 satellite8)
	(on_board instrument31 satellite8)
	(on_board instrument32 satellite8)
	(on_board instrument33 satellite8)
	(on_board instrument34 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet16)
)
(:goal (and
	(pointing satellite0 Planet12)
	(pointing satellite2 Planet16)
	(pointing satellite4 Star11)
	(pointing satellite6 Star9)
	(pointing satellite7 Star3)
	(pointing satellite8 Star9)
	(have_image Star9 spectrograph3)
	(have_image Star9 infrared1)
	(have_image Phenomenon10 infrared1)
	(have_image Star11 spectrograph7)
	(have_image Star11 infrared6)
	(have_image Planet12 thermograph4)
	(have_image Phenomenon13 spectrograph7)
	(have_image Phenomenon13 spectrograph3)
	(have_image Phenomenon13 infrared1)
	(have_image Star14 image8)
	(have_image Star14 infrared0)
	(have_image Phenomenon15 infrared5)
	(have_image Phenomenon17 infrared5)
))

)
