(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite2 - satellite
	instrument13 - instrument
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite4 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite5 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite6 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite7 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	satellite8 - satellite
	instrument40 - instrument
	infrared1 - mode
	spectrograph0 - mode
	infrared3 - mode
	spectrograph6 - mode
	spectrograph8 - mode
	infrared2 - mode
	spectrograph4 - mode
	image5 - mode
	image7 - mode
	GroundStation3 - direction
	Star6 - direction
	GroundStation8 - direction
	GroundStation5 - direction
	GroundStation7 - direction
	Star4 - direction
	GroundStation2 - direction
	Star0 - direction
	Star1 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Star11 - direction
	Star12 - direction
	Phenomenon13 - direction
	Planet14 - direction
	Phenomenon15 - direction
	Planet16 - direction
	Planet17 - direction
)
(:init
	(supports instrument0 image5)
	(supports instrument0 infrared2)
	(calibration_target instrument0 GroundStation3)
	(calibration_target instrument0 Star0)
	(supports instrument1 infrared3)
	(supports instrument1 image5)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 Star6)
	(calibration_target instrument1 GroundStation2)
	(supports instrument2 spectrograph6)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 GroundStation8)
	(calibration_target instrument2 GroundStation5)
	(supports instrument3 spectrograph4)
	(supports instrument3 image5)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 GroundStation7)
	(calibration_target instrument3 GroundStation3)
	(supports instrument4 spectrograph8)
	(supports instrument4 spectrograph0)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 GroundStation5)
	(supports instrument5 spectrograph6)
	(supports instrument5 infrared3)
	(supports instrument5 image5)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 Star0)
	(calibration_target instrument5 GroundStation3)
	(supports instrument6 infrared1)
	(supports instrument6 spectrograph6)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 GroundStation7)
	(calibration_target instrument6 GroundStation3)
	(supports instrument7 spectrograph8)
	(supports instrument7 spectrograph6)
	(calibration_target instrument7 Star6)
	(calibration_target instrument7 GroundStation8)
	(supports instrument8 image5)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 GroundStation8)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon15)
	(supports instrument9 image7)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 Star6)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 image7)
	(supports instrument10 spectrograph4)
	(calibration_target instrument10 GroundStation3)
	(supports instrument11 image5)
	(supports instrument11 spectrograph6)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 GroundStation8)
	(supports instrument12 spectrograph8)
	(supports instrument12 infrared1)
	(supports instrument12 image7)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star1)
	(calibration_target instrument12 Star6)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star11)
	(supports instrument13 infrared1)
	(calibration_target instrument13 Star6)
	(calibration_target instrument13 GroundStation8)
	(supports instrument14 infrared2)
	(supports instrument14 infrared3)
	(calibration_target instrument14 GroundStation7)
	(calibration_target instrument14 GroundStation2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation3)
	(supports instrument15 infrared1)
	(calibration_target instrument15 GroundStation2)
	(calibration_target instrument15 Star4)
	(supports instrument16 infrared3)
	(supports instrument16 infrared2)
	(supports instrument16 image5)
	(calibration_target instrument16 GroundStation8)
	(calibration_target instrument16 GroundStation5)
	(supports instrument17 spectrograph8)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 Star4)
	(supports instrument18 spectrograph4)
	(supports instrument18 infrared3)
	(calibration_target instrument18 Star6)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation7)
	(supports instrument19 spectrograph4)
	(calibration_target instrument19 Star6)
	(supports instrument20 infrared2)
	(supports instrument20 spectrograph6)
	(supports instrument20 image5)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 GroundStation7)
	(supports instrument21 spectrograph0)
	(supports instrument21 spectrograph4)
	(calibration_target instrument21 Star6)
	(calibration_target instrument21 Star4)
	(calibration_target instrument21 Star0)
	(supports instrument22 spectrograph8)
	(calibration_target instrument22 Star4)
	(calibration_target instrument22 GroundStation5)
	(calibration_target instrument22 GroundStation3)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star1)
	(supports instrument23 image5)
	(supports instrument23 spectrograph8)
	(calibration_target instrument23 GroundStation2)
	(calibration_target instrument23 Star0)
	(supports instrument24 infrared2)
	(calibration_target instrument24 GroundStation5)
	(calibration_target instrument24 Star6)
	(supports instrument25 image7)
	(supports instrument25 infrared3)
	(supports instrument25 spectrograph8)
	(calibration_target instrument25 GroundStation7)
	(calibration_target instrument25 Star6)
	(supports instrument26 spectrograph4)
	(calibration_target instrument26 GroundStation3)
	(supports instrument27 infrared3)
	(supports instrument27 infrared2)
	(supports instrument27 spectrograph6)
	(calibration_target instrument27 Star1)
	(calibration_target instrument27 GroundStation5)
	(calibration_target instrument27 GroundStation8)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation2)
	(supports instrument28 spectrograph8)
	(calibration_target instrument28 GroundStation7)
	(supports instrument29 image5)
	(supports instrument29 spectrograph8)
	(supports instrument29 infrared1)
	(calibration_target instrument29 Star4)
	(calibration_target instrument29 GroundStation3)
	(supports instrument30 spectrograph4)
	(calibration_target instrument30 GroundStation3)
	(supports instrument31 spectrograph4)
	(supports instrument31 image7)
	(supports instrument31 infrared2)
	(calibration_target instrument31 GroundStation8)
	(supports instrument32 spectrograph6)
	(supports instrument32 image5)
	(supports instrument32 infrared3)
	(calibration_target instrument32 GroundStation7)
	(calibration_target instrument32 Star4)
	(calibration_target instrument32 GroundStation3)
	(on_board instrument28 satellite6)
	(on_board instrument29 satellite6)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star0)
	(supports instrument33 image7)
	(calibration_target instrument33 GroundStation5)
	(calibration_target instrument33 Star6)
	(calibration_target instrument33 Star1)
	(supports instrument34 spectrograph8)
	(supports instrument34 spectrograph6)
	(calibration_target instrument34 GroundStation8)
	(calibration_target instrument34 Star0)
	(calibration_target instrument34 GroundStation7)
	(supports instrument35 infrared3)
	(calibration_target instrument35 Star1)
	(supports instrument36 spectrograph6)
	(supports instrument36 infrared2)
	(calibration_target instrument36 Star1)
	(calibration_target instrument36 GroundStation5)
	(supports instrument37 spectrograph0)
	(calibration_target instrument37 Star4)
	(calibration_target instrument37 GroundStation7)
	(supports instrument38 spectrograph4)
	(supports instrument38 spectrograph6)
	(supports instrument38 infrared3)
	(calibration_target instrument38 GroundStation2)
	(supports instrument39 infrared2)
	(supports instrument39 spectrograph8)
	(supports instrument39 spectrograph6)
	(calibration_target instrument39 GroundStation2)
	(calibration_target instrument39 Star4)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star6)
	(supports instrument40 image7)
	(supports instrument40 image5)
	(supports instrument40 spectrograph4)
	(calibration_target instrument40 Star1)
	(calibration_target instrument40 Star0)
	(on_board instrument40 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation7)
)
(:goal (and
	(pointing satellite7 Planet17)
	(have_image Planet9 infrared2)
	(have_image Planet9 spectrograph8)
	(have_image Planet9 spectrograph6)
	(have_image Phenomenon10 infrared3)
	(have_image Phenomenon10 spectrograph8)
	(have_image Star11 infrared2)
	(have_image Star11 infrared1)
	(have_image Star12 image5)
	(have_image Star12 spectrograph8)
	(have_image Planet14 image7)
	(have_image Phenomenon15 infrared2)
	(have_image Phenomenon15 spectrograph0)
	(have_image Phenomenon15 infrared1)
	(have_image Planet16 spectrograph6)
	(have_image Planet16 infrared1)
	(have_image Planet17 spectrograph0)
))

)
