(define (problem pb0)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (on block1 block6) (clear block1) (on block2 block3) (clear block2) (on block3 block5) (ontable block4) (on block5 block4) (ontable block6) (ontable block7) (on block8 block7) (clear block8) (ontable block9) (clear block9) (ontable block10) (clear block10) (handempty))
	(:goal (and (ontable block1) (ontable block2) (clear block2) (on block3 block9) (on block4 block8) (clear block4) (on block5 block7) (clear block5) (on block6 block10) (on block7 block6) (on block8 block3) (ontable block9) (on block10 block1))))