(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (ontable block1) (on block2 block5) (on block3 block1) (ontable block4) (clear block4) (ontable block5) (on block6 block9) (on block7 block8) (clear block7) (on block8 block6) (on block9 block2) (on block10 block3) (clear block10) (handempty))
	(:goal (and (on block1 block4) (ontable block2) (on block3 block1) (on block4 block10) (on block5 block6) (on block6 block7) (on block7 block8) (on block8 block2) (on block9 block3) (clear block9) (on block10 block5))))