(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (ontable block1) (ontable block2) (on block3 block2) (clear block3) (on block4 block5) (on block5 block7) (on block6 block1) (ontable block7) (on block8 block6) (clear block8) (ontable block9) (clear block9) (on block10 block4) (clear block10) (handempty))
	(:goal (and (on block1 block2) (clear block1) (on block2 block9) (on block3 block6) (clear block3) (ontable block4) (on block5 block4) (on block6 block7) (on block7 block8) (on block8 block10) (ontable block9) (on block10 block5))))