(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (ontable block1) (on block2 block3) (on block3 block6) (ontable block4) (on block5 block2) (on block6 block1) (on block7 block8) (on block8 block5) (on block9 block7) (clear block9) (on block10 block4) (clear block10) (handempty))
	(:goal (and (ontable block1) (on block2 block1) (clear block2) (on block3 block4) (clear block3) (ontable block4) (on block5 block7) (clear block5) (on block6 block9) (on block7 block10) (ontable block8) (on block9 block8) (on block10 block6))))