(define (problem pb7)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (on block1 block5) (ontable block2) (on block3 block4) (clear block3) (on block4 block10) (ontable block5) (on block6 block9) (clear block6) (on block7 block8) (clear block7) (on block8 block1) (ontable block9) (on block10 block2) (handempty))
	(:goal (and (ontable block1) (ontable block2) (clear block2) (on block3 block6) (on block4 block1) (on block5 block3) (on block6 block9) (on block7 block5) (clear block7) (ontable block8) (on block9 block8) (on block10 block4) (clear block10))))